### ISSUE TITLE
Content properties growth

### ISSUE THREAD

**Issue by imorales** [alkacon/opencms-core#100]
When you have multisite or single site, but you have multiple properties associated to the content. The administration in the workplace is hard because in the advanced properties view the properties are all listed. There isn´t any grouping or clasification by site or by folder or any ... only all properties listed. That listing it´s ok when haven a few of properties but hard when you have a lot of different properties.

**Comment by aKandzior** [comment]
These are 2 different issues or feature requests. 

Issue 1 is fixed since OpenCms 9 with the new property dialog.

Issue 2 will be fixed in OpenCms 10 where sorting by column and filtering is available in the Explorer.

Closing this ticket.
