### ISSUE TITLE
Filter on multiple categories

### ISSUE THREAD

**Issue by Fr3z** [alkacon/opencms-core#140]
Maybe a good idea for the categorie filter when you are searching for something.

You can select multiple categories, for example color:red , type:flower but these are combined via an OR statement, meaning you will get all things with the color red and also combined with all things of type flowers.

Could it be possible to also make an AND statement so that in my example you only get red flowers?

**Comment by aKandzior** [comment]
This is a feature request, but we are not going to implement it anytime soon.
