### ISSUE TITLE
OpenCMS Forums?

### ISSUE THREAD

**Issue by soulgriever** [alkacon/opencms-core#162]
Is there anyway to integrate a forums with Open CMS, what I mean by this is have a user login to the site but once they have logged into the site have them logged into a forum such as the way enjin does

**Comment by ashishcsc** [comment]
Hi,
I have just finished the installation of OpenCms on my machine. Everything seems installed but at the end it shows following error on the browser.

Also, when I tried to open the below url on the browser, it shows HTTP status 500 error.

http://localhost:8080/opencms/opencms/system/login/

HTTP Status 500
OpenCms is not properly initialized!
Please make sure that the OpenCms setup wizard has been run once and is disabled now.
Could anyone please help on this?

Regards,
Ashish

**Comment by akuckartz** [comment]
@ashishcsc Are you aware that you submitted your problem description as a comment to another closed issue?! My suggestion is that you create a new issue for your problem...

**Comment by ashishcsc** [comment]
I am sorry, i didn't notice that. I will open a new ticket for this issue.

Thanks,
Ashish
