### ISSUE TITLE
System error message i18n character set problem

### ISSUE THREAD

**Issue by pStrudthoff** [alkacon/opencms-core#19]
During translation of OpenCms 8.0.3 error related with result message encoding
for Cyrillic characters was founded.

The system error messages in property files (for example,
/system/workplace/locales/ru/messages/org/opencms/db/generic/messages_<locale>.properties)
are displayed with incorrect encoding on the error message page.

The reason is absent of response encoding UTF-8 in the
org.opencms.main.OpenCmsCore.errorHandling method - UTF-8 encoding should be
set here.

As temporal decision we are using custom HTTP filter to set character set for
all responses which have no explicitly set encoding (Filter class is attached).

**Comment by aKandzior** [comment]
Old issue, not longer relevant.
