### ISSUE TITLE
Disable Static Export Issue

### ISSUE THREAD

**Issue by edwin19xx** [alkacon/opencms-core#197]
In OpenCms 7.5, it is easy to disable the static export with setting <staticexport enabled="false"> in opencms-importexport.xml. It is no problem with both demo and workplace. 

However, in 9.0, I try to disable it in the same way, the css or other static resources path still pointing to /export/. 

I tried to modify the org.opencms.staticexport.CmsStaticExportManager.isExportLink() method. It's seems OK but not yet fully tested.

Below code fragment shown the modification.

The vfs/rfs path of the exported resources may cache in the search index. So you need to clean / rebuild the search index after deployed this changes.

Thanks
Edwin

    public boolean isExportLink(CmsObject cms, String vfsName) {

        LOG.info("isExportLink? " + vfsName);
        String siteRoot = cms.getRequestContext().getSiteRoot();
        // vfsname may still be a root path for a site with a different site root 
        CmsSite site = OpenCms.getSiteManager().getSiteForRootPath(vfsName);
        if (site != null) {
            siteRoot = site.getSiteRoot();
            vfsName = CmsStringUtil.joinPaths("/", vfsName.substring(siteRoot.length()));
        }
        String cacheKey = getCacheKey(siteRoot, vfsName);
        Boolean exportResource = getCacheExportLinks().get(cacheKey);
        if (exportResource != null) {
            return exportResource.booleanValue();
        }

        boolean result = false;
        try {

            //Start: Check the static export enabled
            boolean staticExportEnabled = this.isStaticExportEnabled();
            LOG.debug("staticExportEnabled = " + staticExportEnabled);            
            
            if (!staticExportEnabled) {
                throw new CmsException(Messages.get().container(Messages.INIT_STATIC_EXPORT_DISABLED_0));
            } 
            //End: Check the static export enabled
        	
            // static export must always be checked with the export users permissions,
            // not the current users permissions
            CmsObject exportCms = OpenCms.initCmsObject(OpenCms.getDefaultUsers().getUserExport());
            exportCms.getRequestContext().setSiteRoot(siteRoot);
            // let's look up export property in VFS
            CmsResource exportRes = CmsDetailPageUtil.lookupPage(exportCms, vfsName);
            String exportValue = exportCms.readPropertyObject(
                exportCms.getSitePath(exportRes),
                CmsPropertyDefinition.PROPERTY_EXPORT,
                true).getValue();
            if (exportValue == null) {
                // no setting found for "export" property
                if (getExportPropertyDefault()) {
                    // if the default is "true" we always export
                    result = true;
                } else {
                    // check if the resource is exportable by suffix
                    result = isSuffixExportable(vfsName);
                }
            } else {
                // "export" value found, if it was "true" we export
                result = Boolean.valueOf(exportValue).booleanValue();
            }
        } catch (CmsException e) {
            // no export required (probably security issues, e.g. no access for export user)
            LOG.debug(e.getLocalizedMessage(), e);
        }
        getCacheExportLinks().put(cacheKey, Boolean.valueOf(result));

        return result;
    }

**Comment by gWestenberger** [comment]
Fixed in upcoming OpenCms 9.5.1.
