### ISSUE TITLE
Problem with Element Settings order in ADE

### ISSUE THREAD

**Issue by serrapos** [alkacon/opencms-core#213]
I have tested the Element Setting config in resource formatter_config and I have found a error with the order.

I add 3 settings but when I view the form in ADE, the order is diferent to the config.

How can I put my custom ordern in element settings?

**Comment by aKandzior** [comment]
Please check if this was solved in 9.5. or 10.

**Comment by gWestenberger** [comment]
This is already fixed in 9.5.
