### ISSUE TITLE
collector should not list a structured document if it doesn't have the current locale

### ISSUE THREAD

**Issue by pStrudthoff** [alkacon/opencms-core#22]
In a multilanguage site, the collector should not list a structured document if
it doesn't have the current locale. Otherwise, the pagination fails because the
documented is counted and listed, even if no content is shown.
You can see this behavior in the Flower Demo by deleting a localized content in
a news element.
The right behavior is the one of the search, where documents without the set
locale are not listed.

**Comment by aKandzior** [comment]
Old issue, not longer relevant.
