### ISSUE TITLE
Image preview dialog i18n field names

### ISSUE THREAD

**Issue by chirkovmail** [alkacon/opencms-core#224]
org.opencms.ade.galleries.client.preview.ui.CmsImageInfoDisplay class constructor contains non-i18n field names ("Path", "Name", "Title", etc.)
Such field names should be changed to corresponding i18n messages to make possible translate ImagePreview dialog.

**Comment by aKandzior** [comment]
GWT client side localization is unfortunately very tricky, as it requires to recompile the GWT module multiple times for different languages. So just replacing keys is not a solution, one would need to recompile the GWT module and provide an updated opencms core.

OpenCms 10 will use Vaadin where these issues have been solved (i.e. server side keys work again as expected). Closing this ticket as WONTFIX for 9.x.
