### ISSUE TITLE
Can not remove Availability dates

### ISSUE THREAD

**Issue by VitalySolntsev** [alkacon/opencms-core#226]
If was Availability dates (Release and Expiration dates) there are no any ways to remove it.

"Delete Availability@" function doesn't work - it hides dates from "Availability" tab but it still applying.

![im1](https://f.cloud.github.com/assets/5821444/2293154/870a6fc6-a067-11e3-8b16-9f1279eb5bad.png)
![im2](https://f.cloud.github.com/assets/5821444/2293155/8a710aa8-a067-11e3-9e79-0aae24dd9c44.png)
![im3](https://f.cloud.github.com/assets/5821444/2293156/8c53fd1c-a067-11e3-9702-fe418de957a9.png)
![im4](https://f.cloud.github.com/assets/5821444/2293157/8e4298fe-a067-11e3-9c90-90d00a97af05.png)

**Comment by aKandzior** [comment]
Was fixed with OpenCms 9.5.
