### ISSUE TITLE
complier error? 

### ISSUE THREAD

**Issue by trainkg** [alkacon/opencms-core#228]
HOHO  this's funny 

I download the newest code, but when i import into IDE , I can't pass complier 

I write some here

such as 

class 
<code>
import com.google.gwt.dom.client.Element;
public class CmsAdeDownloadGalleryWidgetFactory implements I_WidgetFactory, I_CmsHasInit 
....
</code>

class I_WidgetFactory defined like this 

<code>
import com.google.gwt.user.client.Element;

/**
 * Generates an editing widget with the given configuration.<p>
 */
public interface I_WidgetFactory {
    ....
    /**
     * Wraps an existing DOM element to create an inline editing widget.<p>
     * 
     * @param configuration the widget configuration
     * @param element the element to wrap
     * 
     * @return the widget
     */
    I_EditWidget createInlineWidget(String configuration, Element element);
}
</code>

param type out of step

hoho 
in interface is com.google.gwt.user.client.Element

in  IMPL is com.google.gwt.dom.client.Element

and  com.google.gwt.user.client.Element is  a subclass of com.google.gwt.dom.client.Element

JVM support this? why i don't know this

**Comment by aKandzior** [comment]
This is a support question. Closing this ticket.
