### ISSUE TITLE
Auto generate empty folders when new user logging in

### ISSUE THREAD

**Issue by edwin19xx** [alkacon/opencms-core#229]
Hi Team,

Since 9.0.0, I observed that when I created a new account and logging in with this new account, the system will automatically created several empty folder under ".content" by "Admin" user. Whatever I deleted these empty folder with "Admin", they still created automatically after the new user logging in. Please refer the screen capture below.

![untitled](https://f.cloud.github.com/assets/5944327/2354810/c35c1b96-a5cb-11e3-99a8-eaa67f8eba14.png)

Thanks
Edwin

**Comment by aKandzior** [comment]
This issue is solved in the upcoming OpenCms 10 release.
