### ISSUE TITLE
OpenCms 9.0.1 Setup proccess with SQL Server: COLLATION Issue

### ISSUE THREAD

**Issue by rgaviras** [alkacon/opencms-core#231]
When the setup create the database uses the sentence:

    CREATE DATABASE ${database} COLLATE SQL_Latin1_General_CP1_CS_AS;

which is located in  opencms.war --> \setup\database\mssql\create_db.sql

This command create de Database in CS mode: Case Sensitive.

Opencms 9.0.1  creates all tables with uppercase names and fields

But opencms.jar --> \org\opencms\db\generic\query.properties there are queries with names in lowercase. As Database is created in CS mode those queries will fail.

One solution is chage the COLLATE to  SQL_Latin1_General_CP1_CI_AS or chage the queries to upper case on  query.properties file

**Comment by gWestenberger** [comment]
Fixed in 9.5.3.
