### ISSUE TITLE
Availability to store opencms modules in VCS.

### ISSUE THREAD

**Issue by Areks** [alkacon/opencms-core#233]
Now, OpenCms haven't any tools that allow store their modules in VCS (Version control systems). Because standard file for OpenCms include content and properties and if we developing module in team we need to have ability store it in any VCS. Will be good if you can think about this problem for your next release.

**Comment by aKandzior** [comment]
Apparently this is a feature request and a solution is already available. Moreover, OpenCms 10 will support Git module checkouts with the new Git App.

Closing this ticket.
