### ISSUE TITLE
 $wnd.VIE is not a constructor error when viewing a container page in the ADE

### ISSUE THREAD

**Issue by dyeubicast** [alkacon/opencms-core#237]
After installing the following packages (com.alkacon.bootstrap.basics-9.0.1.zip,
com.alkacon.bootstrap.schemas-9.0.1.zip,
com.alkacon.bootstrap.formatters-9.0.1.zip,
com.alkacon.bootstrap.contents-9.0.1.zip) from the "branch_9_0_x" branch of "modules-v8" into an instance of opencms core built using "build_9_0_1", the following error appears on the screen when viewing any of the installed example container pages (e.g. /tutorial/start-exploring-opencms/index.html):
"$wnd.VIE is not a constructor"

The error seems to resolve itself if the "vie-gwt-server-2.0.jar" is replaced with one built using code from the latest master branch of "alkacon/vie-gwt". Not sure exactly why this is happening though but would appreciate it if you can investigate this problem.

**Comment by aKandzior** [comment]
The VIE component was removed in 9.5, so this issue should not longer occur.
