### ISSUE TITLE
Malfunctioning "invalid date" error message in structured document editor (since 9.0.1 up to 9.5.1)

### ISSUE THREAD

**Issue by amagnolo** [alkacon/opencms-core#240]
In the structured document editor, if an invalid date is manually entered (not using the date picker), the error message is not visible when the mouse cursor is not hovering over the date field. Moreover, the "save" button is not disabled, so the user can save the document without realizing that the saved date will not be what he expected (it will silently remain with the value it had before opening the editor).

Sometimes, instead, the "save" button is disabled (as it should be) and it is not easy to understand that the problem lies in a wrong date. 

I wasn't able to reliably reproduce the conditions when the "save" button gets disabled and when not; in either case, the "wrong date format" error message should be prominent and inhibit the "save" button.

**Comment by amagnolo** [comment]
This bug is still present in OpenCms 9.5.0, you can see it using a blog entry in the demo site. 
It is very annoying because users can't realize the problem until it's too late, and this is happening with every user that inputs dates by hand (rather than using the calendar widget).
The bug was verified with Firefox and Chrome, on Linux and Windows clients.

**Comment by gWestenberger** [comment]
We changed date select widgets with invalid dates to be more visible in the upcoming OpenCms 9.5.1.

**Comment by amagnolo** [comment]
This bug is still present in 9.5.1.
It has actually got worse, you don't even need steps 3 and 4 above to reproduce it.
Just enter anything invalid in a date field and it will be happily ignored by the form.

**Comment by gWestenberger** [comment]
This should finally work correctly in the upcoming version 9.5.3.
