### ISSUE TITLE
OpenCms 9.0.1 config question

### ISSUE THREAD

**Issue by pftender** [alkacon/opencms-core#241]
Hello everybody,I don't konw how to config our project into OpenCms 9.0.1,when i click 
index.jsp(my project) ,i wanto to add pag with OpenCms view,but the following error message : Searching for "org.opencms.search.galleries.CmsGallerySearchParameters@bc713e" failed.

error Id：1397720062776.

 I need your help ,thank you.

**Comment by aKandzior** [comment]
Sorry but his is a bug tracker, not a support forum. Closing this issue.
