### ISSUE TITLE
User settings:  default Project

### ISSUE THREAD

**Issue by fanimo** [alkacon/opencms-core#251]
Hello, 
I think I found a bug in version 9.0.1: 
In the window "Edit User" panel "Settings" you can specify the user project's default, but this setting is ignored. 
Therefore all users except the user "Guest" access to the project "Offline", and they see the ADE toolbar. 
I looked at the file "/ system / modules / com.alkacon.bootstrap.formatters / elements / login.jsp", and I saw that the project is always set to "Offline" :

login.login (request.getParameter ("name"), request.getParameter ("password"), "Offline", request.getParameter ("requestedResource")); 

I tried to replace "Offline" with "null", but in this case remains set to the previous project.

**Comment by aKandzior** [comment]
We have multiple confirmations that this feature works as expected. Closing this issue.
