### ISSUE TITLE
Url-Mapping does not work with "real" locales (language/country combination, eg. "de_DE")

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#258]
After wondering, why the url mapping does not work even though it is configured correctly in the appropriate xsd, I found out that it can't handle locales with language **and** country, like "de_DE".

The database entry for the mapping is written using Locale.toString():
```
[...]
cms.writeUrlNameMapping(
    nameSeq,
    resourceForUrlNameMapping.getStructureId(),
    value.getLocale().toString());
[...]
```
(CmsDefaultXmlContentHandler#resolveMapping(), line 1423ff)

But when readling the mapping only Locale.getLanguage() is used:
```
[...]
Locale bestLocale = localeManager.getBestMatchingLocale(locale, defaultLocales, availableLocales);
String bestLocaleStr = bestLocale.getLanguage();
for (CmsUrlNameMappingEntry entry : lastEntries) {
    if (entry.getLocale().equals(bestLocaleStr)) {
        return entry.getName();
    }
}
[...]
```
(CmsDriverManager#readBestUrlName(), line 6360ff)

So no mapping will be found and the structure id will be used.

**Comment by gWestenberger** [comment]
Fixed in upcoming release.
