### ISSUE TITLE
XSS vulnerabilities within OpenCMS 9.0.1 workplace

### ISSUE THREAD

**Issue by Shaand** [alkacon/opencms-core#261]
The OpenCMS workplace do not properly validate pages and parameters throughout the application. We identified the following pages as few examples:

Url 1:
/system/workplace/admin/linkvalidation/external/validateexternallinks.jsp

Parameters affected:
reporttype
style
threadhasnext

Url 2:
/system/workplace/admin/linkvalidation/internallinks.jsp

Parameters Affected:
resources.0

Url 3:
/system/workplace/explorer/search/index.jsp

Parameters Affected:
settings.userSettings.workplaceSearchIndexName.0

Url 4:
/system/workplace/views/admin/admin-main.jsp

Parameters Affected:
reporttype
style
threadhasnext

Url 5:
/system/workplace/views/explorer/contextmenu.jsp

Parameters Affected:
acttarget

Steps to simulate url 1 issue:

1. Set up a proxy tool to view web traffic such as Burp Suite Proxy.
2. Log into the application.
3. Browse to /system/workplace/admin/linkvalidation/external/validateexternallinks.jsp
4. Intercept the GET request and change the contents of the parameter "reporttype" to:
extended-->";</script>%253cscript%2b%253ealert%25282252%2529%253b%253c%252fscript%2b%253e
5. Note that the JavaScript gets executed at the end user’s browser (screenshot attached)

Please advise if the above XSS issues can be looked in to and addressed at the earliest?

![opencms_github](https://cloud.githubusercontent.com/assets/7913072/3301044/547706e4-f627-11e3-987b-a89729daee57.png)

**Comment by mkannikanti** [comment]
Any thoughts/further inputs on this please?

**Comment by aKandzior** [comment]
These issues all require OpenCms Workplace access, so they will be a problem only with registered and known system users. Therefore the security risk is very low.

These issues will be fixed when we release the new Workplace for OpenCms 10. Will be closing the issue after the release of OpenCms 10.

**Comment by aKandzior** [comment]
These issues should not affect OpenCms 10.
