### ISSUE TITLE
CmsDefaultLinkSubstitutionHandler.getRootPath returns wrong path

### ISSUE THREAD

**Issue by cff3** [alkacon/opencms-core#268]
The implementation of 
<pre>
org.opencms.staticexport.CmsDefaultLinkSubstitutionHandler
     .getRootPath(CmsObject cms, String targetUri, String basePath)  
</pre>
in OpenCms 9.0.1
does the following.

1. it builds a "simpleRootPath" from the targetUri. This simpleRootPath does not take detailUrls into account
1. it tries to convert the targetUri into a detailUrl.
1. if a detailUrl can be found it discards the simpleRootPath without any further reasoning and returns the detailUri

This algorithm seems to be wrong to me. Instead of returning the detailUri without further checking, the implementation should first determine whether the targetUri can be resolved entirely in the VFS. If so, it should return the simpleRootPath and should not try to resolve a detailUri.

In our case it happens that we ask for the rootpath of a category ("/_categories/foo") and get the root path of some other content (for example "/.content/articles/foo") just because the detail name of the latter is foo.

This is really unexpected behavior and I would consider it as a major bug. Please correct me, if I'm wrong.

**Comment by rohtake** [comment]
I am waiting for this bug to be revised.

**Comment by aKandzior** [comment]
Sorry for the delayed answer. 

We are considering to solve this issue for OpenCms 9.5.3.

**Comment by cff3** [comment]
Wow. Danke. Besser spät als nie :)
Das gute an Bugtrackern ist, dass nichts verloren geht …

> Am 08.01.2016 um 13:55 schrieb Alexander Kandzior <notifications@github.com>:
> 
> Sorry for the delayed answer.
> 
> We are considering to solve this issue for OpenCms 9.5.3.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/alkacon/opencms-core/issues/268#issuecomment-169992857>.
> 

-------------------------------------------------
Christoph Fröhlich
Folge 3 GmbH
Sternstraße 5b
20357 Hamburg

+49 40  79 69 48 78
cf@folge3.de
http://www.folge3.de
-------------------------------------------------
Geschäftsführer: Christoph Fröhlich, Anja Künzel
Handelsregister: HRB 105806, Amtsgericht Hamburg

**Comment by gWestenberger** [comment]
This was already fixed in 9.5.0.
