### ISSUE TITLE
Inline editor not working anymore after editing inline and publishing directly

### ISSUE THREAD

**Issue by Anne-VI** [alkacon/opencms-core#270]
Version: OpenCms 9.0.1

After

1. Editing content in inline editor
2. Pulishing page directly without leaving inline editor by clicking the publish button in toolbar and
3. Confirming publishing page

the inline editing is not working for the edited content (1.) anymore.

Please make inline editing possible after publishing directly after inline edit. A proposal for solution could be to hide publish button in toolbar while editing inline.

**Comment by aKandzior** [comment]
This issue has been fixed in OpenCms 9.5.
