### ISSUE TITLE
Reloading images and style sheet

### ISSUE THREAD

**Issue by npoza** [alkacon/opencms-core#272]
I have looked online and have not found an answer, but if one exists, please excuse me and point me to it. I apologize in advance if this question has already been asked and resolved. 

I am new to OpenCMS and built a website. So far so good. But now, for some reason, when I upload new images to the .galleries, it does not show up on the page. Everything was working fine, but suddenly it stopped and I am not sure what I changed inadvertantly. 

I have noticed that it tried to take all the images from the 'export/' folder and I also did a static export. The images are there on the <rfs>. 

Also, the link to the stylesheet under the handler/template does not work any more. It does not link to the file any more. Once again, <cms:link> appends the '/export' to the path. 

What is strange is, everything was working well and maybe I changed something. Now I have no idea how to fix it. 
Please help. I am really stuck. 

I am using Apache, tomcat 7 and mysql.

**Comment by aKandzior** [comment]
Closing this issue as it is clearly a support request and outdated.
