### ISSUE TITLE
CMSShell exit problem after replaceModule

### ISSUE THREAD

**Issue by asdcdow** [alkacon/opencms-core#274]
I am trying to use the CMSShell to automate the update of of a module.  To do this, I am using a shell script that calls CMSShell.  The important section out of the script is:

```bash
cms-shell <<HERE
    login Admin admin
    replaceModule 'com.asd.datatypes' '$module'
    exit
HERE
```

This appears to run correctly and everything finishes.  The problem is that after this is run, none of the formatters in the module are found when trying to edit container pages.  The files exist in the VFS.  They just can't be found when editing the container pages.  If I open the container pages for editing, in the workspace, I get the the message 'Resource not found' on all of the formatter files.

It appears that this is caused by the 'Gallery Index' not including the new formatters.  Forcing the 'Gallery Index' to update makes these errors go away.  It looks like the CMSShell is trying to add the new files to the index but doesn't finish before the shell exits.  If add a command that takes a long time, such as `perf`, right before the `exit` command, then this problem disappears.  However, this seems kind of hacky and might not always work if the index update takes longer.  I can also add a command that forces the index to update, but that can take a long time.

Please make the `exit` command wait for the new files to be added to the index.

**Comment by gWestenberger** [comment]
It seems like you are using the OpenCms shell while the OpenCms web application is running. This is currently not supported, you should only use the shell when the web application is shut down.

**Comment by asdcdow** [comment]
This is occurring when the OpenCms web application is turned off.

**Comment by asdcdow** [comment]
Any chance this issue can be reopened?
