### ISSUE TITLE
cms:container tag cannot be used in a parameter to cms:include

### ISSUE THREAD

**Issue by asdcdow** [alkacon/opencms-core#275]
Whenever I use a `cms:container` tag as a parameter to a `cms:include` tag, as part of a container page template, the rendered page is ends up being just the contents of the first `cms:container` tag in the page.  This problem only occurs when viewing pages on the 'Online' site or if the pages are statically exported.

An exmple of this woud be if I have a `cms:template` that looks like this:

```
<!-- lets call this layout.jsp -->
<%@ page pageEncoding="UTF-8" %>
<%@ taglib prefix="cms" uri="http://www.opencms.org/taglib/cms" %>

<cms:template>
<!doctype html>
<html>
    <head>
    </head>
    <body>
        ${param.body}
    </body>
</html>
</cms:template>
```

and I have a container page template  that looks like this:

```
<%@ page pageEncoding="UTF-8" %>
<%@ taglib prefix="cms" uri="http://www.opencms.org/taglib/cms" %>

<cms:include file="layout.jsp">
    <cms:param name="body">
        <cms:container name="nav" type="nav"/>
        <cms:container name="main" type="main"/>
    </cms:param>
</cms:include>
```

Container pages rendered with the above template, will give me the correct output on the 'Offline' site.  However, if I view the same page on the 'Online' site, or as a statically exported page, I only see the output of whatever is in the 'nav' container.

I think this is a problem with the `cms:container` tag since I appear to get the same problem if I wrap a `cms:container` tag with a `c:set` tag.

**Comment by tHerrmann** [comment]
This is not the intended use of the container tag.
