### ISSUE TITLE
Got CmsInitException while installation

### ISSUE THREAD

**Issue by liweinan0423** [alkacon/opencms-core#276]
I got the following error when I was setting up the opencms.
org.opencms.main.CmsInitException: The CmsUUID cannot be initilized with the invalid ethernet address "".
![image](https://cloud.githubusercontent.com/assets/646159/4298491/e56a5e96-3e23-11e4-87cd-0c3f902f4b98.png)

I left the MAC address as empty or put down my MAC address, both approaches not working.

**Comment by aKandzior** [comment]
Closing this issue as it more a support question, plus apparently it works for all other users.
