### ISSUE TITLE
Inheritance group bug

### ISSUE THREAD

**Issue by serrapos** [alkacon/opencms-core#277]
To reproduce this bug you have to follow those steps:

- Create an an Inheritance Group Resource and drag and drop it in a Container page
- Drag and drop an "in memory" resource into this Inheritance Group.
- Edit and save this new resource.
- Refresh the browser.

When you reproduce this situation the inheritance group disappears from the container page and you have to drag and drop it again in the container page.

**Comment by aKandzior** [comment]
Sorry for not responding earlier to this issue.

Can you still reproduce this in a recent OpenCms version?

**Comment by serrapos** [comment]
I've just tried it in OpenCms 9.5.2 and now it works

**Comment by aKandzior** [comment]
Great, thank you for the feedback!
