### ISSUE TITLE
Limmited support in Java 8: Image processing works but result does not exactly match

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#279]
I've built and installed opencms-core branch_9_0_x (commit ff14759846d476bed2f7957b365a1b1a4ebec2af) on a Tomcat 7 using Java 8. During the component checks of the setup, OpenCms issues an "Image Processing" warning with the hint "Image processing works but result does not exactly match." (See attached image)

Downgrading to Java 7 solves the problem.

The corresponding dialog content:
<pre>
Image processing works but result does not exactly match
Folder Permissions: 	passed 	 
JDK Version: 	1.8.0_20 	 
Temp Directory: 	/home/myuser/usr/apache-tomcat-7.0.55/temp 	 
Operating System: 	Linux 3.13.3-gentoo 	 
Servlet Container: 	Apache Tomcat/7.0.55 	 
Image Processing: 	warning! 	 
Unpacked WAR File: 	passed 	 
Xerces Version: 	Xerces-J 2.11.0 	 
XML API: 	passed 	 
 
	Your system uses components which have not been tested to work with Alkacon OpenCms. It is possible that OpenCms will not run on your system.

Please check the following images for visible differences:
</pre>

![alkacon_opencms_setup_wizard_-_component_tests_-_2014-09-30_07 56 39](https://cloud.githubusercontent.com/assets/790448/4454379/db234c40-486e-11e4-9db2-3784c005c338.png)

**Comment by jimatwood** [comment]
I just got this very same result when installing OpenCMS on a Tomcat 7 using Java 8.  Has this been fixed or do I also need to downgrade to Java 7.  I've been using Java 8 for other projects.  Thanks very much.

**Comment by jimatwood** [comment]
Just downgraded to Java 7 from Java 8 and now everything works.  Thanks.

**Comment by tHerrmann** [comment]
Fixed in branch_9_5_x will be released in version 9.5.3.
