### ISSUE TITLE
Encoding problems after updading from Version 7 to 8 or 9

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#285]
The upgrade wizard does not remove "\" for jdbc url params in opencms.properties ("db.pool.default.jdbcUrl.params=?characterEncoding\=UTF-8"), what results in encoding problems when adding special chars to property values of a resource.

**Comment by gWestenberger** [comment]
Fixed in upcoming release - the backslash is now interpreted as an escape character in opencms.properties again.
