### ISSUE TITLE
Missing filetranslations after updading from Version 7 to 9

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#286]
The upgrade wizard does not add all &lt;translation&gt;'s to opencms-vfs.xml.
After a fresh installation of OpenCms 9 there are much more.

**Comment by tHerrmann** [comment]
We don't consider this a bug. File translation rules are not upgraded intentionally, as they are often adjusted to specific needs. So we rather leave this kind of setting untouched during setup.
