### ISSUE TITLE
Direct Edit

### ISSUE THREAD

**Issue by pStrudthoff** [alkacon/opencms-core#29]
Issue:
   Editor displayed when Direct Edit is used has changed since updating our
system from opencms 8.0 to 8.1. 

   The Direct Edit for 8.0 displays a black border around the edit information.
This editor is preserving request parameters.   The Direct Edit for 8.1/8.2 is
not, thus the other is desired.
   Both of these setups had the following in opencms-workplace.xml
   <directeditprovider
class="org.opencms.ade.editprovider.CmsToolbarDirectEditProvider">

History:
   I am developer working for a corporation that was using opencms 6 and have
updated their website to use 8.0.  We have synced our website using webdav and
our development work is being done with Rational Application Developer.  Have
done configuration changes such using the app as ROOT, created custom
collectors, filestypes, etc.

**Comment by aKandzior** [comment]
Old issue, not longer relevant.
