### ISSUE TITLE
Assign categories error(opencms 9.5.0)

### ISSUE THREAD

**Issue by superc** [alkacon/opencms-core#291]
When i use <cms:editable/> tag and click  Show menu - Advanced - Assign categories show error in opencms 9.5.0.

appears the following message:
'org_opencms_ade_galleries_clientmessages' is not a JavaScript object and cannot be used as a Dictionary

How to resolve this error or hide Assign categories in opencms 9.5.0?

![1113230734](https://cloud.githubusercontent.com/assets/3608960/5030900/3504cabc-6b8e-11e4-99c0-392400ccf567.png)

**Comment by gWestenberger** [comment]
Fixed in upcoming release.
