### ISSUE TITLE
Nested Containers: page reload required after adding a nested container

### ISSUE THREAD

**Issue by tomwolfgang** [alkacon/opencms-core#293]
Given two resource types: tabs and article.

tabs is a nested container resource type that has a container that accepts the article type.
on a fresh/clean page - I want to be able to add a tab and then an article - but the article is disabled until I refresh the page.

**Comment by tomwolfgang** [comment]
From the release notes of OpenCms 9.5.2:

"Fixed issue where the types in the container page editor's 'Add' menu were not updated after changes to nested containers."

Is this the issue I'm talking about?

**Comment by tHerrmann** [comment]
Sorry for the late reply. Yes, it is.
