### ISSUE TITLE
Content-Definition with XSD: Wrong order for choice elements after XSD change or saving in control code editor

### ISSUE THREAD

**Issue by mwxwidmann** [alkacon/opencms-core#296]
When a content type definition uses a choice element that has maxOccurs > 1, then the "correctXmlStructure" functionality that is triggered by XSD changes or when the XML control code is edited and saved in OpenCms is causing a faulty ordering of child elements.

Simplified parent XSD:

```xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xsd:include schemaLocation="opencms://opencms-xmlcontent.xsd"/>
	<xsd:include schemaLocation="opencms://system/modules/com.mediaworx.weisseliste.opencms.formgenerator/schemas/nested/formFields.xsd"/>

	<xsd:element name="Forms" type="OpenCmsForms"/>

	<xsd:complexType name="OpenCmsForms">
		<xsd:sequence>
			<xsd:element name="Form" type="OpenCmsForm" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="OpenCmsForm">
		<xsd:sequence>
			<xsd:element name="Title" type="OpenCmsString" />
			<xsd:element name="FormFields" type="OpenCmsFormFields" minOccurs="0"/>
			<xsd:element name="SubmitText" type="OpenCmsString" />
		</xsd:sequence>
		<xsd:attribute name="language" type="OpenCmsLocale" use="required"/>
	</xsd:complexType>

	<xsd:annotation>
		<xsd:appinfo>
		</xsd:appinfo>
	</xsd:annotation>
</xsd:schema>
```

Spimplified child XSD:

```xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xsd:include schemaLocation="opencms://opencms-xmlcontent.xsd"/>
	
<xsd:element name="FormFieldss" type="OpenCmsFormFieldss"/>

<xsd:complexType name="OpenCmsFormFieldss">
	<xsd:sequence>
		<xsd:element name="FormFields" type="OpenCmsFormFields" minOccurs="0" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="OpenCmsFormFields">
	<xsd:choice minOccurs="0" maxOccurs="1000">
		<xsd:element name="Input" type="OpenCmsString" minOccurs="0"/>
		<xsd:element name="Select" type="OpenCmsString" minOccurs="0"/>
		<xsd:element name="Radio" type="OpenCmsString" minOccurs="0"/>
	</xsd:choice>
	<xsd:attribute name="language" type="OpenCmsLocale" use="optional"/>
</xsd:complexType>

<xsd:annotation>
	<xsd:appinfo>
	</xsd:appinfo>
</xsd:annotation>
</xsd:schema>
```

When the content type definition is changed and the content is edited again or when the XML control code of the content is edited and saved, the Method A-CmsXmlDocument.correctXmlStructure is triggered. And here's what happens:

Order of the form fields before correctXmlStructure:

* Select 1
* Input 1
* Input 2
* Radio 1
* Input 3
* Select 2
* Radio 2 

Order of the form fields after correctXmlStructure:

* Input 1
* Input 2
* Input 3
* Select 1
* Select 2
* Radio 1
* Radio 2 

So correctXmlStructure sorts the fields by type in the order of the choice definition. This is unexpected behaviour and it breaks the content every time the content type xsd is changed (or the control code is edited and saved).

**Comment by aKandzior** [comment]
This is ok in general but keep in mind to remove items from the choice list XML in case the choice definition is removed.

A test case would be great. Existing test class for XML content schema modifications is:

test/org.opencms.xml.content.TestCmsXmlContentSchemaModifications

**Comment by aKandzior** [comment]
Closed as the PR for this has been merged into the core.
