### ISSUE TITLE
Timezone inconsistency when editing dates

### ISSUE THREAD

**Issue by parakelian** [alkacon/opencms-core#300]
For example, when editing `Date released` or `Date expired` from the workplace (right-click on resource -> Advanced -> Availability), the user's time zone is ignored and the time is saved with the server's timezone setting as is.

When editing a date that is mapped to `Date released`, however (with just right-click -> Edit), the user's timezone is taken into account when converting to the server's timezone.

This different behavior on different screens is causing confusion. Is it possible to make this consistent?

From what I can tell, the time zone being taken into account began with version 8.5, and it's been that way since. So I'm guessing this was intentional, but it simply wasn't implemented everywhere throughout the workplace. Should it be? I think so, but could anyone confirm this? Thank you.

**Comment by gWestenberger** [comment]
It is the "old" workplace date picker widgets that use the server time zone, while the newer code using GWT uses the client time zone. Fixing this in the old workplace is not really on top of our priorities, but we will likely make it consistent in the new workplace we are working on for OpenCms 10.
