### ISSUE TITLE
Can't update to version 9.5.1 from OpenCms 9.5.0 versions

### ISSUE THREAD

**Issue by superc** [alkacon/opencms-core#303]
Can't update to version 9.5.1 from OpenCms 9.5.0 versions.
Access the following URL had no response.
$SERVER_NAME/$CONTEXT_NAME/update/ 

Test environment:
Windows7 JDK6 Tomcat7

**Comment by aKandzior** [comment]
Apparently your config is mixed up. Closing as this is not a support forum.
