### ISSUE TITLE
Add to navigation issue(opencms 9.5.1)

### ISSUE THREAD

**Issue by superc** [alkacon/opencms-core#305]
No add to navigation checkbox select in opencms 9.5.1 when click "Change navigation" in the resource's context menu.
![20150305125909](https://cloud.githubusercontent.com/assets/3608960/6499634/e4c26cd6-c339-11e4-8500-3a6ce81d44e7.png)

**Comment by dSeidel** [comment]
If you add a navigation text, the resource will automatically appear in the navigation. Thus, the checkbox was superfluous.
