### ISSUE TITLE
Can't operating resources of plain type (opencms 9.5.1)

### ISSUE THREAD

**Issue by superc** [alkacon/opencms-core#308]
Can't operating resources of plain type after import template Two Module.

![0313171732](https://cloud.githubusercontent.com/assets/3608960/6636558/34876136-c9ac-11e4-99b3-8c0183977133.png)

**Comment by dSeidel** [comment]
Hi,
you can open resources of type plain. But, throughflowers.html is actually an xmlpage. To use it, uncomment the explorertype definition for xmlpage in the opencms-workplace.xml.
