### ISSUE TITLE
[ENHANCEMENT] Mysql Innodb support

### ISSUE THREAD

**Issue by cernio** [alkacon/opencms-core#310]
We are setting up a high performance, high availability system with Percona XtraDB Cluster, which needs all tables to be InnoDB in order to enable replication.
We altered all tables successfully except for CMS_ALIASES. 
Mysql error is:
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes

The origin of this is the "path" field, which is varchar(256). We manually altered the table to varchar(255) in order to convert this table to InnoDB, but we are not sure (yet!) that this does not compromise the correct functioning of opencms.

**Comment by cernio** [comment]
Sorry, a less invasive edit is to set up primary key with a shorter path:
CREATE TABLE CMS_ALIASES
  (
     path         VARCHAR(255) NOT NULL,
     site_root    VARCHAR(64) NOT NULL,
     alias_mode   INTEGER NOT NULL,
     structure_id VARCHAR(36) NOT NULL,
     PRIMARY KEY (path(255), site_root)
  )
ENGINE = INNODB
CHARACTER SET UTF8;

**Comment by dSeidel** [comment]
The fix you provided with the pull request #312 will be included in OpenCms 9.5.2. Thanks for the fix.
