### ISSUE TITLE
tab can't swtich at online

### ISSUE THREAD

**Issue by lztang1964** [alkacon/opencms-core#313]
opencms 9.5 formattorr  tabs-standard.jsp is work fine on offline,but don't work on online,it can't switched,the HTML   outputed by tab-standar.jsp shows div class="tab-pane"  hasn't "id" attrubite., it should be   equal to  href attribue of <a tag. 

![opencms](https://cloud.githubusercontent.com/assets/12093283/7340286/b881e96a-ecbc-11e4-8fee-1a7d14df64eb.JPG)

this picture shows the HTML output by tab formattor.

**Comment by lztang1964** [comment]
sorry,I don't know how to past HTML code!  The problem is : tab-pane hasn't id  attribute,so it can't swtich!

**Comment by lztang1964** [comment]
ok,just add a tag="div id=" param to <cms:container,the tab-standard.jsp will work well

**Comment by lztang1964** [comment]
after add tag="div id=xxx" to Container tag,the tab-standart works,but the html it output add id also to < /   div  id="xxx"> ,it isn't a well fine HTML document

**Comment by dSeidel** [comment]
Hi, the problem is, that the ids on div's generated by the container tag are only attached offline (for nested containers).
You solved the problem. But, the solution may influence ADE-functionality.
OpenCms 9.5.2 will provide a fixed formatter that introduces an additional div. Here's the part containing the fixed lines:

	<div class="tab-v1">
		<ul class="nav nav-tabs">
			<c:forEach var="label" items="${content.valueList.Label}" varStatus="status">
				<li class="${status.first? 'active':''}"><a href="#${cms.element.instanceId}-tab-${status.count}" data-toggle="tab">${label}</a></li>
			</c:forEach>
		</ul>

		<div class="tab-content">
			<c:forEach var="label" items="${content.valueList.Label}" varStatus="status">
				<div id="${cms.element.instanceId}-tab-${status.count}" class="tab-pane ${status.first? 'active':''}">
					<cms:container name="tab-container${status.count}" type="layoutrowsonly" maxElements="2">
						<div class="alert alert-warning fade in">
							<h4><fmt:message key="bootstrap.tabs.emptycontainer.headline"/></h4>
							<p><fmt:message key="bootstrap.tabs.emptycontainer.text"/></p>           
						</div>     				
					</cms:container>
				</div>
			</c:forEach>
		</div>
	</div>
