### ISSUE TITLE
Issue while installing OpenCms

### ISSUE THREAD

**Issue by ashishcsc** [alkacon/opencms-core#317]
Hi,
I have just finished the installation of OpenCms on my machine. Everything seems installed but at the end it shows following error on the browser.

Also, when I tried to open the below url on the browser, it shows HTTP status 500 error.

http://localhost:8080/opencms/opencms/system/login/

HTTP Status 500
OpenCms is not properly initialized!
Please make sure that the OpenCms setup wizard has been run once and is disabled now.
Could anyone please help on this?

Regards,
Ashish

**Comment by ashishcsc** [comment]
Could anyone assist on this?

**Comment by ashishcsc** [comment]
I have tried to download from  http://localhost:8080/opencms/setup. But I got some error which says "The alkacon OpenCms setup wizard has not been started correctly".
![installation-finished](https://cloud.githubusercontent.com/assets/12484135/7782267/cfe9c60e-012a-11e5-86a3-070f1e5d1c11.png)
![Uploading Installation-FInished.png…]()
![error](https://cloud.githubusercontent.com/assets/12484135/7782270/da36957e-012a-11e5-991d-72d8f4fc7eca.png)


See attached screenshot.

**Comment by ashishcsc** [comment]
I have started the OpenCms setup again 2-3 times but everytime I am getting the same message.

Could anyone help on this please?

**Comment by akuckartz** [comment]
> Please make sure that the OpenCms setup wizard has been run once and is disabled now.

In my experience the setup wizard often did not automatically disable itself.

It might help to manually disable the setup wizard (http://www.opencms-wiki.org/wiki/Opencms.properties). Then try to access http://localhost:8080/opencms/opencms/system/login/ again.

**Comment by ashishcsc** [comment]
Thanks it worked for me.

Where I can get the documentation for creating new website using new
version of OpenCms 9.5?

I have seen the demo video for editing existing website but there is no
video/tutorials available to create new website using OpenCms 9.5.



On Sat, May 23, 2015 at 11:51 AM, Andreas Kuckartz <notifications@github.com
