### ISSUE TITLE
the resources Type of xmlpage in opencms 9.5 

### ISSUE THREAD

**Issue by sunxy521** [alkacon/opencms-core#318]
When create a new file,can not find the file type xmlpage,
However, when editing the /system/modules/com.alkacon.bootstrap.formatters/.config file, add the resource type, and this type of the drop box

**Comment by dSeidel** [comment]
It's because the explorer type configuration is commented out (since xmlpage is usually not used anymore when designing a website), but the resource type definition is still there, because some xmlpages are used internally.
