### ISSUE TITLE
Error while importing module OAMP

### ISSUE THREAD

**Issue by ashishcsc** [alkacon/opencms-core#319]
When I am trying to import the module through import module from server, I am getting below error.

Error uploading the module alkacon-oamp-branch_9_0_x.zip.
Manifest file missing in module C:\apache-tomcat-7.0.62\webapps\opencms\WEB-INF\packages\modules\alkacon-oamp-branch_9_0_x.zip.

What could be the issue? Please help if anyone have idea?

**Comment by dSeidel** [comment]
You need to import the modules - not the source code .zip. You can build modules yourself or download them at http://www.alkacon.com/en/products/oamp/
