### ISSUE TITLE
Increase contrast for details in workplace

### ISSUE THREAD

**Issue by pStrudthoff** [alkacon/opencms-core#32]
Some views in the workplace, like for example "Administration View >  Account
Management >  Organizational Unit: root organizational unit >  User Management:
root organizational unit " 
show details (Groups or Roles for example) in a light gray, which is difficult
to read since it has only little contrast to the white background.

Please change the color in new-admin.css, td.listdetailitem from "threedshadow"
to something like #666666

td.listdetailitem {
    color: #666666;
    font-size: 10px;
    padding-left: 10px;
}

**Comment by aKandzior** [comment]
Will be fixed with the new workplace design in OpenCms 10.
