### ISSUE TITLE
tabs standard can not switch after I logoff Admin

### ISSUE THREAD

**Issue by BiWu** [alkacon/opencms-core#320]
This is a very confusing problem, I created tabs by "Tabs standard formatter", the tabs can  switched when i click each tab  after I logged in as Admin. but they can not switch if I logoff.  this problem blocked me for a long time, Who can give me a solution? Thank you very much.

**Comment by dSeidel** [comment]
Hi, the problem is, that the ids on div's generated by the container tag are only attached offline.
OpenCms 9.5.2 will provide a fixed formatter that introduces an additional div. Here's the part containing the fixed lines:

	<div class="tab-v1">
		<ul class="nav nav-tabs">
			<c:forEach var="label" items="${content.valueList.Label}" varStatus="status">
				<li class="${status.first? 'active':''}"><a href="#${cms.element.instanceId}-tab-${status.count}" data-toggle="tab">${label}</a></li>
			</c:forEach>
		</ul>

		<div class="tab-content">
			<c:forEach var="label" items="${content.valueList.Label}" varStatus="status">
				<div id="${cms.element.instanceId}-tab-${status.count}" class="tab-pane ${status.first? 'active':''}">
					<cms:container name="tab-container${status.count}" type="layoutrowsonly" maxElements="2">
						<div class="alert alert-warning fade in">
							<h4><fmt:message key="bootstrap.tabs.emptycontainer.headline"/></h4>
							<p><fmt:message key="bootstrap.tabs.emptycontainer.text"/></p>           
						</div>     				
					</cms:container>
				</div>
			</c:forEach>
		</div>
	</div>
