### ISSUE TITLE
Section "Site Management" not translated to Russian and Japanese

### ISSUE THREAD

**Issue by chirkovmail** [alkacon/opencms-core#323]
OpenCms 9.5.2 binary distribution (http://www.opencms.org/downloads/opencms/opencms-9.5.2.zip) doesn't contains Russian and Japanese localization to "Site Management" interface. But this section was translated (at least for Russian) and corresponding changes where committed.

Please check why this section stay not translated in binary distribution.

**Comment by dSeidel** [comment]
I just integrated your pull request and checked if "something" was russian. All your files were already included. But the manifest file was missing some entries - e.g., the one for the bundle for the site management. It's fixed now in the repository.

**Comment by chirkovmail** [comment]
Ok, thank you
