### ISSUE TITLE
Blog entry always point to grid-demo

### ISSUE THREAD

**Issue by BiWu** [alkacon/opencms-core#324]
I create my own site based on default "Demo Content".  I build a folder name "HealthInfor" to put new blog in it, So,
   1)   I build a containerpage named "index.html" in which I put a bs-list named "l_00002.xml" in "HealthInfo --> .content --> lists" folder. the formatter for "l_00002.xml" is "/system/modules/com.alkacon.bootstrap.formatters/formatters/list-small.jsp".  
   2) the "Create Path" of "l_00002.xml " is "/sites/default/healthinfor/.content/blogentries/be_%(number:5).xml"
   3) I create "/healthinfor/.content/ugc_config/ugc_config-00001.xml",  the "Content Folder " is "/healthinfor/.content/blogentries/", the uploader folder is "/healthinfor/.content/blogentries/images-ugc/"
   
![1](https://cloud.githubusercontent.com/assets/12797556/8459883/c032419a-2052-11e5-9aae-16c296855fde.JPG)

4) I login in as "Admin", open Index.html, add a new blog on page directly. 

![2](https://cloud.githubusercontent.com/assets/12797556/8460057/0d65bb58-2054-11e5-877f-e4339f020bc6.JPG)

 Then I have a very strange problem: when i click one of the blog in order to see the detail of the blog,, i found the link point to "grid-demo/blog/blog-entries/-00066/" folder. Why?
![3](https://cloud.githubusercontent.com/assets/12797556/8460172/d879d040-2054-11e5-8924-d28672e271fe.JPG)

**Comment by lztang1964** [comment]
编辑.content文件夹下.config,设置为local

**Comment by tHerrmann** [comment]
The demo template is maintained in another repository, please report this issue over at [module-v8](http://www.github.com/alkacon/modules-v8).
