### ISSUE TITLE
Export the specified directory

### ISSUE THREAD

**Issue by linghaowangluo** [alkacon/opencms-core#325]
I want to export the specified directory.
Does this feature requires  needs   develop myself ?

**Comment by tHerrmann** [comment]
If you have questions regarding the usage of OpenCms, please use the OpenCms mailing list http://www.opencms.org/en/development/mailinglist.html. This issue list is for bug tracking only.

To export a specific folder go to Administration View > Database Management > Export Database and export the resources of your choice. 
Keep in mind, that the export and import feature in OpenCms is site specific, so you can choose to export a folder from site 'A' and import it to another OpenCms instance into site 'B'. Depending on the site selected in the workplace tool bar.
