### ISSUE TITLE
Wrong access to NavStartLevel in navigation-side.jsp of bootstrap

### ISSUE THREAD

**Issue by mtvweb** [alkacon/opencms-core#327]
formatters/navigation-side.jsp
accesses param.level instead:

  c:set var="navStartLevel" value="${value.NavStartLevel.getToInteger() + 1}"

is working. Conversion is required, because NavStartLevel is a string in the schema

**Comment by tHerrmann** [comment]
The demo template is maintained in another repository, please report this issue over at [module-v8](http://www.github.com/alkacon/modules-v8).
