### ISSUE TITLE
Wrong calculation of permalink in shared folder

### ISSUE THREAD

**Issue by jplette** [alkacon/opencms-core#331]
org.opencms.staticexport.CmsLinkManager.getPermalink(CmsObject cms, String resourceName, CmsUUID detailContentId)

Line:332
String serverPrefix = OpenCms.getSiteManager().getCurrentSite(cms).getServerPrefix(cms, resourceName);

If a resource is stored in the shared folder (which has no site configured) the serverPrefix "*://*:0/" is returned. Instead the serverPrefix of the default site (or a configurable site) should be returned in case of shared folder items.

**Comment by gWestenberger** [comment]
Fixed in release 9.5.3.
