### ISSUE TITLE
Permission change does not set modification date

### ISSUE THREAD

**Issue by veggie** [alkacon/opencms-core#332]
If I change the permission of a resource in explorer view, the "date last modified" is not changed but the explorer view shows the resources as changed (red font color and yellow flag). The last modified user is changed as well.
So what is the correct behaviour?

**Comment by tHerrmann** [comment]
This behaviour is intended. As the last modified date is often used to sort content collector lists, we did not want a permission change to effect this. You can use the 'touch' functionallity to set the last modified date explicitley.
