### ISSUE TITLE
Build script: restlet not found

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#337]
For the record:

The configurations `default, gwtRuntime, modulesRuntime, runtime, setupRuntime` are (implicitly) declared as transitive. All of them declare the dependency `org.apache.solr:solr-core:4.3.0`. This depends on `org.restlet.jee:org.restlet:2.1.1` and `org.apache.solr:solr-parent:4.3.0`, and this last one in turn declares in its pom the "_Public online Restlet repository_" `http://maven.restlet.org`.

But [Gradle doesn't honor repositories declared in POMs](http://stackoverflow.com/a/17036916/413020), so  `gradle -q dependencies` warns about failing to fetch `org.restlet.jee:org.restlet:2.1.1`

I'm not sure how relevant all of this is, as it seems I still can compile and build a working webapp, but my IDE complains and throws and exception upon opening the project.

**Comment by gallardo** [comment]
This could be fixed in `build.gradle` by adding the missing repository:

```groovy
repositories {
    mavenLocal()
    if (project.hasProperty('additional_repositories')){
        additional_repositories.split(';').each{ repo ->
            maven { url repo }
        }
    }
    mavenCentral()

    // Workaround for org.netbeans.gradle.model.util.TransferableExceptionWrapper:
    // org.gradle.internal.resolve.ModuleVersionNotFoundException: 
    // Could not find org.restlet.jee:org.restlet:2.1.1.
    maven {
        url "http://maven.restlet.org/" 
    }
}
```

or by declaring these configurations as non-transitive (as example, I declare all configurations as non-transitive):

```groovy
configurations.each {
    it.transitive = false;
}
```

I'm not filing a PR because I'm not sure that this doesn't have collateral unwanted effects.

**Comment by gallardo** [comment]
I think that it suffices that `solr-core` is declared in `dependencies.gradle` as `distribution` dependency.

Apparently, the distributables will be built using this dependency, so we can safely ignore all `*Runtime` configurations. As for the `default` configuration, it is only relevant for gradle projects depending on this gradle build. If this were a problem, it should be reported.

**Comment by tHerrmann** [comment]
This has not been an issue with our IDE (Eclipse) and all gradle task required to build any OpenCms artefacts work without any problems. So in my view, the gradle integration of your IDE is at fault here.

Having said that, in branch 10.0.x we have added restlet as a direct dependency to OpenCms and also added the additional repository to the build script. So this issue will be resolved for the upcoming releases.
