### ISSUE TITLE
htmlwidget: stylesformat not recognized #regression #9.5.2

### ISSUE THREAD

**Issue by cernio** [alkacon/opencms-core#339]
On Opencms 9.5.2, setting the styleformat option on a field with layout HtmlWidget does not have any effect.
Code portion of our schema:
```xml
<layout element="Text" widget="HtmlWidget" configuration="source,stylesformat:/system/modules/it.tiscali.schema/resources/common.js"/>
```
common.js is 
```javascript
[
	{
		title: 'Virgolettato',
		block: 'span',
		styles: {color: '#ff0000'},
		classes: 'quoted'
	},
	{
		title: 'Video',
		block: 'section',
		styles: {color: '#ff0000'},
		classes: 'video2'		
	},
	{
		title: 'Immagine',
		block: 'section',
		styles: {color: '#ff0000'},
		classes: 'image2'		
	},
	{
		title: 'Photobox',
		block: 'section',
		styles: {color: 'green'},
		classes: 'photobox2'		
	}	
]

```
We ran the same schema (and associated stylesformat resource) on opencms 9.5.1 and opencms 9.5.2 docker images (simple flavor) and it shows different behavior: stylesformat is working on 9.5.1, whilst it is not on 9.5.2.

Watching the html source code in the wp editor, it looks like the 
```html
<meta name="com_alkacon_acacia_shared_ContentDefinition" content="..." />
```
is correctly populated in both versions.

**Comment by cernio** [comment]
Issue has been found on Mozilla firefox 40 
![opencms952](https://cloud.githubusercontent.com/assets/3693594/9600970/b88395b2-509e-11e5-904d-42ea89ecf3b3.png)
![opencms951](https://cloud.githubusercontent.com/assets/3693594/9600971/b8858a98-509e-11e5-89eb-3a57a96748e7.png)

**Comment by gWestenberger** [comment]
9.5.2 requires the "style" configuration option to be explicitly set in addition to "stylesformat" to enable the style select box. This will be no longer required in 9.5.3.
