### ISSUE TITLE
Document "stream" and "bypass" cache directives

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#341]
These values are valid values for jsp pages, but they are not yet documented in [the corresponding section](http://documentation.opencms.org/opencms-documentation/caching-in-opencms/the-flex-cache/#2)

During a bug hunting I came across [this code fragment](https://github.com/alkacon/opencms-core/blob/branch_9_5_x/src/org/opencms/loader/CmsJspLoader.java#L485)

```java
// read "cache" property for requested VFS resource to check for special "stream" and "bypass" values
String cacheProperty = cms.readPropertyObject(file, CmsPropertyDefinition.PROPERTY_CACHE, true).getValue();
if (cacheProperty != null) {
    cacheProperty = cacheProperty.trim();
    if (CACHE_PROPERTY_STREAM.equals(cacheProperty)) {
        streaming = true;
    } else if (CACHE_PROPERTY_BYPASS.equals(cacheProperty)) {
        streaming = true;
        bypass = true;
    }
}

```

It turns out that this affects how jsp are delivered. In fact, my hunted bug is fixed by turning `cache=bypass`: the servlet forwards the request, instead of including it, allowing for headers resetting.

Apparently, there was already one more issue (https://github.com/alkacon/opencms-core/issues/37) related with an incorrect `cache` setting.

**Comment by tHerrmann** [comment]
I am not sure what you are getting at. Do you think there is a bug related to the cache property handling, or do you think, the documentation on this should be improved?

**Comment by gallardo** [comment]
This is just documentation enhancement request. The bug was in our JSP code because we were not setting `cache=bypass`. In fact, this value is not documented. I was just hoping the docs are extended to cover these possible settings, and the use cases Alkacon envisioned when introducing them, i.e. how and when are they supposed to be used.

**Comment by dSeidel** [comment]
Hi,
I added the values to the documentation to make them more visible, thought not with detailed documentation yet.
