### ISSUE TITLE
Feature Request: database export / import with versions

### ISSUE THREAD

**Issue by veggie4ever** [alkacon/opencms-core#342]
Add support for OpenCms database export (and import) with all history versions.
That is an important feature when upgrading OpenCms and it is not possible to use the upgrade wizard.

**Comment by gallardo** [comment]
:+1:

**Comment by gallardo** [comment]
Feedback from the OpenCms Days 2015: this has currently low priority. Without external 'promotion', it could eventually happen in the future, along with a new repository implementation... or not.

**Comment by veggie** [comment]
Yes, I was there too. Understandable and frustrating at the same time. I hope they don't remove the history feature completely in version 10 or 11.

**Comment by tHerrmann** [comment]
Our development is currently not focused on this kind of feature. But if is really important to you, you can always sponsor it. Just drop us an email, and we can work out the requirements and costs.

**Comment by aKandzior** [comment]
A new GUI for the history feature will certainly be implement in OpenCms 10. As said already, enhancing the DB export with support for versions is not going to happen anytime soon.
