### ISSUE TITLE
Advanced Detail Page System

### ISSUE THREAD

**Issue by rubenglzlpz** [alkacon/opencms-core#345]
Hi,

I would like to suggest you an evolutive that might be interesting for the OpenCms community. Currently, OpenCms allows you to establish a "Detail Page" for a particular content type. It would be interesting that, it could also display a selected page depending on some values on the content itself.

Greetings,

**Comment by imorales** [comment]
Cool functionality.

**Comment by aKandzior** [comment]
Please describe in more detail how the improvement / feature should work. Your description is very broad and leaves much room for interpretation. In order to meet real world requirements, we need a detailed description with examples.

**Comment by rubenglzlpz** [comment]
I will try to explain it with an example:
We have a third party content type called "Report"
with a field called "Type" whose possible values ​​are "Internal" and "External"
Currently OpenCms allows us to open the content type "Report" with a detailpage called "report.html"
It would be interesting, depending on the value of "Type" field, the content was open with "internal_report.html" or "external_report.html" detail pages.
If this is not possible with the value of a field (because the tool ignore the structure of the content, for example) could be done based on a property value? Because OpenCms allows you to map properties and schema fields in the content type schema.

**Comment by aKandzior** [comment]
Detail pages are a bag of surprises. Many people have ideas what should be changed or improved, mostly for their rather specific uses cases. For the time being, we will not be able to work on this because of limited resources. 

Of course, you can implement this yourself and send a pull request.
