### ISSUE TITLE
Upload to wrong directory outside /sites/.... i.E. /system/modules

### ISSUE THREAD

**Issue by mtvweb** [alkacon/opencms-core#348]
Uploading i.E. images to the resources folder of a module fails. The upload is done to the last working directory of the "/sites/default".

Current workaround:
After uploading, it is necessary to move the files to the correct directory i.E. /system/modules/com.example.module/resources/img

OpenCMS 9.5.2

**Comment by tHerrmann** [comment]
Could you please provide a step by step descripition, how to reproduce this issue.

**Comment by aKandzior** [comment]
Closing this issue since we are not able to reproduce it and no further feedback was provided after request.
