### ISSUE TITLE
Store session information in the db

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#349]
One of the hiccups during module development is the need to restore the session state after container restart.
If the session were stored in the database, the restart could be made transparent for a developer (or any user).

**Comment by tHerrmann** [comment]
With the current workplace used up to version 9.5.2 this is not feasible. But with the new workplace planned for version 10 it's likeley we will find a solution for this.

**Comment by gallardo** [comment]
Thanks. That'd be great! I'm looking forward for that release.

**Comment by benocms** [comment]
+1 - very good idea
