### ISSUE TITLE
Editing content in collected Lists leads to Exception in Firefox 41

### ISSUE THREAD

**Issue by mwxwidmann** [alkacon/opencms-core#350]
When editing content by clicking on the pencil icon in collected lists, a GWT exception is thrown in Firefox 41 (tested on Windows and Mac). This also happens on the OpenCms demo site. There's no problem when using Chrome or Safari (IE not tested).

Steps to recreate the problem: 
* Log in to the OpenCms workplace 
* Navigate to grid-demo/blog, click on index.html
* Activate the OpenCms toolbar to toggle edit points
* Hover over the edit point of the first blog entry, click on the pencil
* Strangely the language select box is visible for a short moment an then disappears, the save button becomes active even if no changes are made to the content
* Click on the save button or the close button (and confirm with "OK")
* An error is displayed "Invalid id ..."
* The XML editor can't be closed, only a reload resolves the problem
* The content is in fact saved, so after a reload the changes are visible

The stack trace that's displayed in the Details section is:

    org.opencms.main.CmsIllegalArgumentException: Invalid id "9e772aad-52dc-11e4-9866-005056b61161%23-296264929"
    org.opencms.ade.containerpage.CmsContainerpageService.convertToServerId(CmsContainerpageService.java:401)
    org.opencms.ade.containerpage.CmsContainerpageService.getCachedElement(CmsContainerpageService.java:1187)
    org.opencms.ade.containerpage.CmsContainerpageService.getElements(CmsContainerpageService.java:1389)
    org.opencms.ade.containerpage.CmsContainerpageService.getElementsData(CmsContainerpageService.java:510)
    sun.reflect.GeneratedMethodAccessor175.invoke(Unknown Source)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:483)
    com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
    com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:265)
    com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:305)
    com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    org.opencms.gwt.CmsGwtService.service(CmsGwtService.java:195)
    org.opencms.main.OpenCmsCore.invokeGwtService(OpenCmsCore.java:1640)
    org.opencms.main.OpenCmsServlet.doGet(OpenCmsServlet.java:150)
    org.opencms.main.OpenCmsServlet.doPost(OpenCmsServlet.java:166)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:203)
    org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
    org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
    org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
    org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
    org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    java.lang.Thread.run(Thread.java:745)

**Comment by tHerrmann** [comment]
I think I have resolved this issue. Could please check out attached [containerpage editor](http://www.opencms.org/downloads/opencms/org.opencms.ade.containerpage-9.5.2.1.zip) to see if it works for you as well?

**Comment by mwxwidmann** [comment]
Yes, it works. Thank you for the prompt fix! I'll have it rolled out immediately.

**Comment by tHerrmann** [comment]
I have build another [containerpage editor](http://www.opencms.org/downloads/opencms/org.opencms.ade.containerpage-9.0.1.1.zip) for people still using OpenCms version 9.0.1.
Let me now, if it resolves the issue.
