### ISSUE TITLE
Presence of a "@" in the login vs PersistingLogin

### ISSUE THREAD

**Issue by SandrineProusteau** [alkacon/opencms-core#353]
On OpenCms 9.5.2, when we use an account which have his email as login, ex: firstname.lastname@company.com, the "reading" of the cookie seems to return an invalid token.
I suggest to replace "@" in the cookies contents by something like "_at_".
I get around this issue by registering new users with "@-replaced" email as login.

**Comment by gWestenberger** [comment]
Fixed for release 9.5.3.
