### ISSUE TITLE
Thread local not removed on stop

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#355]
Doesn't look harmful.

Tomcat logs the following message if it is shutdown shortly (very few seconds) after having started it up:

```
SEVERE [http-nio-18080-exec-11] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [opencms] created a ThreadLocal with key of type [com.sun.xml.bind.v2.ClassFactory$1] (value [com.sun.xml.bind.v2.ClassFactory$1@e555e1d]) and a value of type [java.util.WeakHashMap] (value [{class javax.xml.bind.annotation.W3CDomHandler=java.lang.ref.WeakReference@556060db}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
```

**Comment by gallardo** [comment]
Closing: I have thoroughly tested the reloading of the opencms app in tomcat, and in spite of that `SEVERE` message, there is no measurable leak after reloads.

**Comment by gallardo** [comment]
Correction: there is indeed a leak. The WebappClassLoader cannot be released, and will probably result in a PermGen exception if using Java < 8. (For Java 8+, it leaks, but it won't be so noticeable).

I could track the Tomcat logged error up to a JAXB bug. Older versions of JAXB (<2.2.5) can cause memory leaks. See https://java.net/jira/browse/JAXB-831 and https://java.net/jira/browse/JAXB-563.

**Comment by gallardo** [comment]
More on this: According to https://java.net/jira/browse/JAXB-1000, this could be
> caused by JAXB creating but never clearing a ThreadLocal of type ClassFactory.

Unfortunatelly, JAXB-1000 is marked in 2.2.6 and 2.2.7 as "Won't Fix" with a last comment "_Until JAXB API change we are not able to deal with this._"

**Comment by tHerrmann** [comment]
I think this really is a non issue. It occurs only when starting and stopping the web appliaciotn in short order. Which is only a development use case, and is very unlikely to happen in production. It only is a potential leak, not a real one. So "Won't fix" is just fine with me.

**Comment by gallardo** [comment]
I'm completely fine with this being marked as "won't fix". I just wanted to extend a bit more this issue documentation to serve my memory, in case I come across this in the future and I forget. (As I first found it, I though it would be an easy one to fix.)

Notice that there is a real leak, independently of the tomcat logged message. I can reproduce it always using heap dumps. But as you point out, it is relevant only during development, when reloading the webapp, and not in production.
