### ISSUE TITLE
UX: Add content icon [enhancement]

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#358]
I once and again struggle with finding the "Add content" icon in the ADE. I understand that under certain  circumstances and for certain people (I'd dare to say mostly software engineers), the current icon 
![image](https://cloud.githubusercontent.com/assets/790448/10479410/7ea3b114-7264-11e5-8cdb-5780704e751b.png) could be intuitive; but what about a much more accepted '+' sign? (E.g. 
![image](https://cloud.githubusercontent.com/assets/790448/10479498/101b3504-7265-11e5-8562-588573ff32fd.png))

*Disclaimer: Please, take this suggestion with a grain of salt, as I'm far from a UX designer.*

**Comment by veggie** [comment]
+1

**Comment by patric-dosch-vi** [comment]
+1

**Comment by tHerrmann** [comment]
Sorry, but we will most likely keep the wand.

**Comment by veggie** [comment]
:-(
If you don't mind, I would be interested in the reason. I heard from more than one customer of ours, that the wand is not very intuitive for this use case.

**Comment by tHerrmann** [comment]
Call it tradition. We like our magic resource creation.
We also think, the plus icon is very generic and no more intuitive than our wand.
