### ISSUE TITLE
Some ADE menu entries are grayed out if the user doesn't have write permission on the container page

### ISSUE THREAD

**Issue by LR17** [alkacon/opencms-core#359]
Some ADE menu entries are grayed out if the user doesn't have write permission on the container page. In particular: logout, about, preferences. Tested with a user having role "Editor".  Moreover the ADE "Add" button is disabled at page load (as expected) but if the user changes some content and goes back, then the draggable types are shown. Obviously if he/she tries to drag a type an error occurs due to missing permissions on the container page.

**Comment by LR17** [comment]
I believe the issue is triggered if the user does not have write permissions on the folder which contains the containerpage, not the container page itself

**Comment by LR17** [comment]
To make a summary: if the folder which contains the containerpage does not have permission or the write is denied at the type level (accessentry -w) the issue is triggered.
If the folder does have permission and the container page file do not, wverything works as expected

**Comment by tHerrmann** [comment]
Fixed in branch_9_5_x will be released in version 9.5.3.
