### ISSUE TITLE
Error on search function on CategoryWidget

### ISSUE THREAD

**Issue by AntoinePineau** [alkacon/opencms-core#360]
On OpenCms 9.5.2, when using a CategoryWidget and when trying to search, the following error happens: (TypeError) __gwt$exception: : Cannot read property 'Bc' of undefined
![alkacon-bug](https://cloud.githubusercontent.com/assets/1810578/10639639/a70075e0-7811-11e5-8f9d-2faa4c9a5d3e.png)

Are you aware of this issue ?

**Comment by tHerrmann** [comment]
Fixed in branch_9_5_x will be released in version 9.5.3.
