### ISSUE TITLE
"Show in device" DOM is different from classic ADE preview one

### ISSUE THREAD

**Issue by SandrineProusteau** [alkacon/opencms-core#362]
It should have been great if absolutly no DOM differences where added between classic ADE preview and "show in device" ADE preview...
We use to set css positionnement on elements directly under containers, to avoid multiple containers management in responsive design, and with these new div "cms_ade_element_start" and "cms_ade_element_end", the rendering is broken.

**Comment by tHerrmann** [comment]
These added elements can cause layout issues, we are aware of that. We have just not managed to improve the mechanism yet.

**Comment by SandrineProusteau** [comment]
We could add some css fix if there were a class attribute dedicated for "show in device" on the top of the DOM or on the container :) ...

**Comment by aKandzior** [comment]
Can you provide more detail on what class attribute you require for the fix? Sounds like it may be easy to add.

A more elaborate example would be nice.
