### ISSUE TITLE
Alkakon OpenCms 7.5.2 non persistent XSS.

### ISSUE THREAD

**Issue by chzacharopoulou** [alkacon/opencms-core#363]
Hello
I have create a
Search Form:
But
http://www.example.com/opencms/search.html?action=search&searchPage=1&query=>"><script>alert("EgoPL says: Hi, I'm in a XSS")</script>&submit=GO are
Exercuted.

Any idea how to fixed with a javascript?

**Comment by chzacharopoulou** [comment]
Any idea my code in search.jsp

<%@ page buffer="none" import="org.opencms.main.*, org.opencms.search.*, org.opencms.file.*, org.opencms.jsp.*, java.util.*" %><%   
    
    // Create a JSP action element
    org.opencms.jsp.CmsJspActionElement cms = new CmsJspActionElement(pageContext, request, response);
    
    // Get the search manager
    CmsSearchManager searchManager = OpenCms.getSearchManager(); 

  // get the template 
   

%>

<jsp:useBean id="search" scope="request" class="org.opencms.search.CmsSearch">
    <jsp:setProperty name = "search" property="*"/>
    <% search.init(cms.getCmsObject()); %>
</jsp:useBean>


<table>
    <tr>
    <td width="160">
       <form action="/gsis/info/gsis_site/Results.html" method="post">
        
           
            <div> <input name="query" type="text" value=""  
                    onfocus="this.value=''" title="Αναζήτηση" />
            <input class="searchsubmit" type="submit" 
                    title="Αναζήτηση" value="" style="border-style: none; background: url('/gsis/export/sites/default/gsis_site/images/search.gif') no-repeat; width: 22px; height: 26px; valign:top; cursor:pointer;"/>
             <input type="hidden" name="index" value="Gsis-Offline" /></div>
         
       </form>
    </td>
   <td width="80px;"><a href="/gsis/info/gsis_site/rss_feed.html" target="_blank"><img src="/gsis/export/sites/default/gsis_site/images/Feed.png" alt="rss" style="width: 22px; height: 22px;"/></a>
   <a href="https://twitter.com/gsis_gov_gr" target="_blank"><img src="/gsis/export/sites/default/gsis_site/images/Twitter.png" alt="Ακολουθήστε μας στο twitter" style="width: 22px; height: 22px;"/></a>
<a href="https://www.youtube.com/channel/UCMuaKgDs9qzkcT1cRwgmUPA" target="_blank"><img src="/gsis/export/sites/default/gsis_site/images/Youtube.png" alt="Ακολουθήστε μας στο youtube" style="width: 23px; height: 22px;"/></a></td>
       </tr>
</table>


and we have xss cross?

**Comment by tHerrmann** [comment]
Hi,
this is an issue tracker and should be used for bug reporting only. If you need help using OpenCms you are welcome to join the OpenCms mailinglist http://www.opencms.org/en/development/mailinglist.html and ask your quetsions there.

Regards, Tobias
