### ISSUE TITLE
Articles writing, auditing and publishing

### ISSUE THREAD

**Issue by BiWu** [alkacon/opencms-core#366]
I want to know how to satisfy the following scenario:
      1) User A writes a article.
      2) User B audits the article, if the article is right, then publish it. 
      3) Maybe sometimes, User C need to audit the article after User B audited
   Thank you.

**Comment by veggie** [comment]
Hi,
you can add the following code to your opencms-system.xml
        <workflow class="org.opencms.workflow.CmsExtendedWorkflowManager">
            <parameters>
                <param
name="workflowProjectManagerGroup">Administrators</param>
                <param name="workflowProjectUserGroup">Users</param>
                <param
name="notificationContent">/.content/workflow-notification.html</param>
            </parameters>
        </workflow>
This is only a 4-eyes workflow, so 3) is not possible.
There is an example file in /system/workplace/admin/notification/ which you
can copy. There you can define the subject, header and footer of the email
notification sent to the auditor.
HTH

Best regards
Kai

**Comment by tHerrmann** [comment]
Hi,
this is an issue tracker and should be used for bug reporting only. If you need help using OpenCms you are welcome to join the OpenCms mailinglist http://www.opencms.org/en/development/mailinglist.html and ask your quetsions there.

Regards, Tobias
