### ISSUE TITLE
Unable to unlock resources, because root folder is locked

### ISSUE THREAD

**Issue by veggie** [alkacon/opencms-core#367]
I changed properties of the vfs root folder "/" with the source search feature. Now all resources are locked and I am not able to unlock them - even as Admin user.
I get the following error message:
    The following resources were not unlocked:
    Error unlocking resource "/shared/" by current user "Admin" - Unable to unlock "/shared/", the lock is inherited from a parent folder.
    Error unlocking resource "/sites/" by current user "Admin" - Unable to unlock "/sites/", the lock is inherited from a parent folder.
    Error unlocking resource "/system/" by current user "Admin" - Unable to unlock "/system/", the lock is inherited from a parent folder. 
How can I force an unlock on the parent folder? Publish the "Offline" project doesn't work.

**Comment by veggie** [comment]
If someone ever has that problem, create a JSP in the VFS put in the following code, save it and call (click) it:
`<%@page session="false" buffer="none" import="org.opencms.jsp.CmsJspActionElement" %>`
`<%`
`CmsJspActionElement jsp=new CmsJspActionElement(pageContext,request,response);`
`jsp.getCmsObject().unlockResource("/");`
`%>`

**Comment by aKandzior** [comment]
Could you please transfer this fix to the WIKI? 

Right now this seems to be a rather "far out" issue only happening in rare cases, so your fix is perfectly valid.

**Comment by veggie** [comment]
Done.
See: http://www.opencms-wiki.org/wiki/Workaround_for:_Unable_to_unlock_resources,_because_root_folder_is_locked
