### ISSUE TITLE
"Title Ascending" order does'nt seem to work on Galleries on OpenCms 9.5.2

### ISSUE THREAD

**Issue by AntoinePineau** [alkacon/opencms-core#369]
Hello,

In OpenCms version 9.5.2, it seems that sorting elements in a gallery by Ascending Title does not work.
cf attached file.

![bug-23037](https://cloud.githubusercontent.com/assets/1810578/11659583/5690859a-9dc9-11e5-8eff-6903ba973fbd.PNG)

**Comment by tHerrmann** [comment]
Fixed in branch_9_5_x will be released in version 9.5.3.

**Comment by AntoinePineau** [comment]
Hello Tobias,
Would it be possible to obtain a patch for OpenCms 9.5.2 ?

**Comment by AntoinePineau** [comment]
Hi Tobias,

Could you please update me on that ?
