### ISSUE TITLE
Suggestion : Order types in gallery dialog by Label

### ISSUE THREAD

**Issue by SandrineProusteau** [alkacon/opencms-core#370]
It should be great if the list of types available in "Add new" gallery dialog where ordered automaticaly by Title, instead of by type machine name. :)
I know there is an "order" attribute in explorertypes definition, but it doesn't depend on workpalce locale, and it is not very convenient to use if we have near or more 20 custom xmlcontent types...

**Comment by aKandzior** [comment]
To me it appears better to order the items identical in all languages, so that the position in the list is always identical. What do you think?

**Comment by SandrineProusteau** [comment]
It would be great if we had a sorting select just like in the results tab, in order to switch sorting on several ways... 
Our customers are accustomed to search a list item by alphanumeric order of displayed labels. They do not switch between workplace languages, so they don't care it's always the same position. In our case, we have near 40 xmlcontent types, and some technical names don't match the displayed label. Most of items are alphanum ordered, but some are not. Very confusing for them to find these special items.

**Comment by aKandzior** [comment]
I suggest you use the sort order attribute to get the items in order for now. I can't promise that we will consider this feature request in the future as apparently there is a way to sort using the sort order attribute. It's just not locale depended, sorry.
