### ISSUE TITLE
Feature Request: Opening of internal / external weblink in new Window

### ISSUE THREAD

**Issue by all7722** [alkacon/opencms-core#377]
Hallo Opencms Team,
es wäre gut bei Neuanlage eines internen oder externen Weblinks (nicht aber im WYSIWYG Editors! - im Editor ist es möglich!) über eine neue / zusätzliche Einstellung (z.B. mittels einer combobox oder checkbox) zu definieren "ob der Link im neuen Browserfenster oder im selben Fenster" geöffnet wird. Dies ist ganz wichtig! Wenn es bereits funktioniert, bitte um einen Hinweis!
Ansonsten wäre es gut in einer der nächsten Version 10.0.x diese relativ kleine Erweiterung zu realisieren. Vorab vielen Dank!
Gruß
Alexander

**Comment by aKandzior** [comment]
Looks more like a support issue to me. Can you please identify what exactly do you mean by "Neuanlage eines internen oder externen Weblinks"? I understand the German but it does not make sense to me. 

If it is an issue in the XML contents (form based editor) and the formatter producing the output then this is not an OpenCms core issue. Actually it would be quite easy to add the function in this case by modifying the XSD and the formatter for the resource type in question. 

I will close this issue in 3 months if no further activity happens on this ticket.

**Comment by all7722** [comment]
Hello Alexander,
thans for your feedback! Please see attachment - I've created an screenshot (with a new additional checkbox and lable) - to show which functionality wil be nice to have (if you klick in Display area, not in editor, on the external link - started with http://....  [and with activated new chackbox/combobox], than a new window will be opened and not the same).
Thanks!
Alexander
![link_new_window](https://cloud.githubusercontent.com/assets/18071003/14608736/37576fce-0587-11e6-96ee-a70b4f65e244.jpg)

**Comment by aKandzior** [comment]
We will consider this enhancement for the next release of the Apollo Template in OpenCms 10. 

You are apparently using the demo template from OpenCms 9.5. 

It's easy to add this yourself. 

Open /system/modules/com.alkacon.bootstrap.schemas/schemas/imagex.xsd in the source code editor and enter the line 

`<xsd:element name="NewWindow" type="OpenCmsBoolean" minOccurs="1" maxOccurs="1" />`

below the similar line with the "Link". Locate the formatter you use in 

`/system/modules/com.alkacon.bootstrap.formatters/formatters/`

e.g. `image-simple.jsp`.

Here locate the code for the `<a href... >` tag(s) and insert the following at the right position:

`${value.NewWindow == 'true' ? ' target="external"' : ''}`

I will leave the details as an exercise for you. 

In case you can't get this working yourself consider getting support from the OpenCms mailing list or paid support from Alkacon. The issue tracker is not a support forum.
