### ISSUE TITLE
OpenCMS Publish Permission

### ISSUE THREAD

**Issue by junaidbinsarfraz** [alkacon/opencms-core#381]
This question is posted in **[here](http://stackoverflow.com/questions/36498763/opencms-publish-permission)** too 

I am using OpenCMS 10.

1) I have created a new user lets say mkumar.

2) I assigned Users group to the user.

3) I assigned Element author role ([having least permissions](http://documentation.opencms.org/opencms-documentation/background/permissions-in-opencms/users-groups-roles-and-ous/roles-in-opencms/))

Element Author

An element author can only access the page editor (and content editors). This role can create, add and edit content elements.
4) Now I created new resource/page say myPage.html and I add a sample content in it.

5) I set permission of mkumar on myPage.html [Check image here](http://i.stack.imgur.com/GLca3.png)

6) (From another browser) mkumar logged in and open myPage.html. He edited the content (say he add more content).

7) After editing mkumar is able to publish (but in permission box is denied Direct Publish).

Problem:

I want to remove publish permission. What should I do now?

**Comment by aKandzior** [comment]
Remove the user from the "users" group. If required, create a new group for users yourself. Make sure to apply the permission changes to the folder, not the file in the folder. You should not remove "write" permission and also uncheck "responsible. Also make sure that permissions are not only applied to the container page, but also to the element resource folders. 

I assume that this is a configuration / support issue and NOT a core problem. Closing this issue.
