### ISSUE TITLE
New workplace ignores custom groups in "New" dialog

### ISSUE THREAD

**Issue by jobisoft** [alkacon/opencms-core#382]
We upgraded to OpenCms 10.

Our module includes custom resourcetypes and explorertypes which are placed within their own group.  If I use the old workplace, these groups are still shown (thus not a config problem), but the new workplace ignores the groups and puts the custom resources in "other".

Is there a new config needed, to get groups in the new "New" dialog?

**Comment by aKandzior** [comment]
In OpenCms 10 the resources are ordered by content views, using a different configuration. The plus point is that the configuration can be individual per site.  

On a default installation, please see /system/modules/org.opencms.ade.config/elementviews/ to see how element views are defined and /system/modules/org.opencms.ade.config/.config to see how to connect the default view of a resource type to a specific element view. 

Let me know if this solves your issue.

**Comment by jobisoft** [comment]
Thanks, I try that. I will post further questions regarding this on the mailing list.
