### ISSUE TITLE
"Bilder kommentieren" fehlt im Kontextmenu des neuen Explorers

### ISSUE THREAD

**Issue by jobisoft** [alkacon/opencms-core#386]
Der alte Workplace hatte die tolle Funktion, allen Bildern einer Bildergalerie in einem Rutsch eine Beschreibung zu verpassen.

Wir lieben diese Funktion und es wäre schade, wenn sie im neuen Explorer dauerhaft fehlen würde.

**Comment by aKandzior** [comment]
This function is not part of the new explorer. There are no plans yet to add this again.

However, the new explorer has a "step through properties" feature that allows stepping through all files in a folder without leaving the dialog. Its the arrows in the lower left of the properties dialog. You can use this to edit all properties of an image gallery.

**Comment by jobisoft** [comment]
That is a big loss. The step through is not the same, because 

1) you do not see the picture you want to comment
2) you do not see all pictures at once to be able to make a "photo story", where the comments of the pictures add up to a story

Please reconsider.

**Comment by aKandzior** [comment]
You are right regarding your points 1) and 2). However, there are no plans to add this feature again in the near future. 

For the time being you can still use the old workplace if you want.
