### ISSUE TITLE
Can't install opencms10 on mysql cluster,create table error

### ISSUE THREAD

**Issue by lztang1964** [alkacon/opencms-core#390]
to install opencms 10 on mysql cluster need to change store engine to ndbcluster,error when create 
tables.

Error executing SQL statement: CREATE TABLE CMS_PROJECTRESOURCES ( PROJECT_ID VARCHAR(36) NOT NULL, RESOURCE_PATH TEXT BINARY NOT NULL, PRIMARY KEY (PROJECT_ID, RESOURCE_PATH(255)), INDEX RESOURCE_PATH_IDX (RESOURCE_PATH(255)) ) ENGINE = ndbcluster CHARACTER SET UTF8
-------------------------------------------
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: BLOB column 'RESOURCE_PATH' can't be used in key specification with the used table type at sun.reflect.GeneratedConstructorAccessor276.newInstance(Unknown Source) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:526) at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) at com.mysql.jdbc.Util.getInstance(Util.java:386) at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054) at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4190) at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4122) at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2570) at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2731) at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2812) at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2761) at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:894) at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:732) at org.opencms.setup.CmsSetupDb.executeStatement(CmsSetupDb.java:757) at org.opencms.setup.CmsSetupDb.executeSql(CmsSetupDb.java:672) at org.opencms.setup.CmsSetupDb.executeSql(CmsSetupDb.java:735) at org.opencms.setup.CmsSetupDb.createTables(CmsSetupDb.java:228) at org.apache.jsp.setup.step_005f5_005fdatabase_005fcreation_jsp._jspService(step_005f5_005fdatabase_005fcreation_jsp.java:415) at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438) at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396) at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:745)

**Comment by cernio** [comment]
Hi,
I had similar issues with percona cluster and ocms9.
In your case, you encountered a limitation of the ndbcluster engine:
*FULLTEXT indexes. * The NDB
<https://dev.mysql.com/doc/mysql-cluster-excerpt/5.5/en/mysql-cluster.html>
storage
engine does not support FULLTEXT indexes, which are possible for MyISAM tables
only.
(Ref:
https://dev.mysql.com/doc/mysql-cluster-excerpt/5.5/en/mysql-cluster-limitations-syntax.html
)


You may
- change the engine or clustering architecture (i.e. percona, mariadb with
galeralib, etc.)
- change the data table for RESOURCE_PATH to varchar (urgh!)


2016-04-28 5:38 GMT+02:00 lztang1964 <notifications@github.com>:

> to install opencms 10 on mysql cluster need to change store engine to
> ndbcluster,error when create
> tables.
> Error executing SQL statement: CREATE TABLE CMS_PROJECTRESOURCES (
> PROJECT_ID VARCHAR(36) NOT NULL, RESOURCE_PATH TEXT BINARY NOT NULL,
> PRIMARY KEY (PROJECT_ID, RESOURCE_PATH(255)), INDEX RESOURCE_PATH_IDX
> (RESOURCE_PATH(255)) ) ENGINE = ndbcluster CHARACTER SET UTF8
>
> com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: BLOB column
> 'RESOURCE_PATH' can't be used in key specification with the used table type
> at sun.reflect.GeneratedConstructorAccessor276.newInstance(Unknown Source)
> at
> sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:526) at
> com.mysql.jdbc.Util.handleNewInstance(Util.java:411) at
> com.mysql.jdbc.Util.getInstance(Util.java:386) at
> com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054) at
> com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4190) at
> com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4122) at
> com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2570) at
> com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2731) at
> com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2812) at
> com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2761) at
> com.mysql.jdbc.StatementImpl.execute(Stateme ntImpl.j ava:894) at
> com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:732) at
> org.opencms.setup.CmsSetupDb.executeStatement(CmsSetupDb.java:757) at
> org.opencms.setup.CmsSetupDb.executeSql(CmsSetupDb.java:672) at
> org.opencms.setup.CmsSetupDb.executeSql(CmsSetupDb.java:735) at
> org.opencms.setup.CmsSetupDb.createTables(CmsSetupDb.java:228) at
> org.apache.jsp.setup.step_005f5_005fdatabase_005fcreation_jsp._jspService(step_005f5_005fdatabase_005fcreation_jsp.java:415)
> at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) at
> javax.servlet.http.HttpServlet.service(HttpServlet.java:729) at
> org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
> at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
> at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340) at
> javax.servlet.http.HttpServlet.service(HttpServlet.java:729) at
> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:29
> 2) at or
> g.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
> at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> at
> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
> at
> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
> at
> org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
> at
> org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
> at
> org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
> at
> org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
> at
> org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
> at
> org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
> at
> org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
> at org.apache.catalina.connecto r.Coyote
> Adapter.service(CoyoteAdapter.java:522) at
> org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
> at
> org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
> at
> org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
> at
> org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
> at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> at
> org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> at java.lang.Thread.run(Thread.java:745)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/alkacon/opencms-core/issues/390>
>



-- 


[image: Enrico Marongiu on about.me]

Enrico Marongiu
about.me/cernio
skype: cerionmorgauin
  <http://about.me/cernio>
