### ISSUE TITLE
On demand static export handler with purge related resources

### ISSUE THREAD

**Issue by juandafg** [alkacon/opencms-core#391]
CmsOnDemandStaticExportHandler.java (return empty list) only purge elements in publish queue, but this behavior causes that if you rename an image, change is not refresh to content type that contains it and also container page. 

Instead of this, a change in content type is forced to refresh in:
       A_CmsStaticExportHandler.scrubResource -> getContainerPagesToPurge

If on demand static export handler returns recursive relations in 
      A_CmsStaticExportHandler.scrubResource -> getRelatedFilesToPurge

(i.e. demo):
(image slider) p6.jpg --> /grid-demo/.content/sliders/sl_00001.xml --> /grid-demo/home/index.html

You obtain automatic refresh for your content in all relation pages. This behavior is suitaible for Apache serving static export contents

**Comment by tHerrmann** [comment]
Hi,
you can configure your own implementaition of the static export handler in /WEB-INF/config/opencms-importexport.xml.
Just extend the default implementation and overwrite the method.
