### ISSUE TITLE
Reusing 1 content type, storing new content file in different pathes, displaying content list item in different detail pages

### ISSUE THREAD

**Issue by MabenQiu** [alkacon/opencms-core#392]
Hi every one, I’m trying to build a small site based on opencms v10, I defined a content type named ‘Article’ and want to reuse it in several different pages under different navigation menus, for instance, I created two menus: M1->M1A and M2->M2A, in pages under M1A and M2A, I putted separated list to display lists of ‘Article’, but here I’m facing 2 problems, (1) How can new contents of ‘Article’ created with different pages be stored in different folders? (2) How can ‘Article’ items of list in different pages be displayed with different detail pages? For problem-1, I tried to change resource type configuration in model-configuration(.config), to set ‘Folder’ to ‘With page’, new contents can be stored with pages which contain lists, but contents in the list cannot be displayed in detail page correctly. For problem-2, I know there can be a unique detail page under a sitemap, and it can be working fine, but whenever a user click an item in a list, the detail page shows(the user is navigated to detail page), but the navigation position before the user clicked the item lose, the user has to look up the navigation position (actual a menu) again, which makes a bad experience. So for shot, I want to reuse only one content type, but require new content files can be stored in different folders, list item can be redirected to different detail pages. Please share you advice if any, thanks in advance.

**Comment by tHerrmann** [comment]
Please refer to the OpenCms mailing list if you need support in using OpenCms: http://www.opencms.org/en/development/mailinglist.html

The is not a support forum but is used for bug tracking only.
