### ISSUE TITLE
How to set repositoryfolder_imagegallery of Image gallery widget with opencms v10?

### ISSUE THREAD

**Issue by MabenQiu** [alkacon/opencms-core#393]
How to set repositoryfolder_imagegallery of VFS image widget with opencms v10?
In the documentation of opencms we can see below desctiption but i don't how to set the repositoryfolder_imagegallery:
the gallery (folder) chosen via the property repositoryfolder_imagegallery. This property is read from the currently edited resource. It can be inherited and thus it is preferable to set it on a folder.
If neither repositoryfolder_imagegallery is set, nor an image gets replaced, the upload button is deactivated.

**Comment by cernio** [comment]
Just edit the properties of your site/subsite folder. Add the new property
and specify the full path of the imagegallery.

2016-05-03 14:45 GMT+02:00 MabenQiu <notifications@github.com>:

> How to set repositoryfolder_imagegallery of VFS image widget with opencms
> v10?
> In the documentation of opencms we can see below desctiption but i don't
> how to set the repositoryfolder_imagegallery:
> the gallery (folder) chosen via the property
> repositoryfolder_imagegallery. This property is read from the currently
> edited resource. It can be inherited and thus it is preferable to set it on
> a folder.
> If neither repositoryfolder_imagegallery is set, nor an image gets
> replaced, the upload button is deactivated.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/alkacon/opencms-core/issues/393>
>



-- 


[image: Enrico Marongiu on about.me]

Enrico Marongiu
about.me/cernio
skype: cerionmorgauin
  <http://about.me/cernio>

**Comment by tHerrmann** [comment]
Hi,
this is a bug tracker only. If you have questions regarding the useage of OpenCms it's best to contact the mailing list: http://www.opencms.org/en/development/mailinglist.html
