### ISSUE TITLE
OpenCms 10.0 can't translate ade galleries clientmessage

### ISSUE THREAD

**Issue by twofisher** [alkacon/opencms-core#394]
Hi,

when I translate the  messge file 
/system/workplace/locales/zh/messages/org/opencms/ade/galleries/clientmessages_zh.properties to chinese,It can't display correct as other locale  files in the chinese bundle.

![chinese](https://cloud.githubusercontent.com/assets/12093283/15004132/cedac908-11e5-11e6-82df-7c8c4c75de01.jpg)

the following chinese (unicode ) in file clientmessages_zh.properties was displayed incorrect in ADE.
GUI_TAB_TITLE_VFS_0=\u6587\u4ef6\u5939
GUI_TAB_TITLE_CATEGORIES_0=\u5206\u7c7b
GUI_TAB_TITLE_SEARCH_0=\u9ad8\u7ea7
GUI_TAB_TITLE_GALLERIES_0=\u56fe\u5e93

I wonder if someone  give me some advice on how to translate it.

thanks!

**Comment by tHerrmann** [comment]
Hi,
have you tried HTML entities instead of the unicode? That might work.

**Comment by tHerrmann** [comment]
Closing the issue.
In case using the HTML entities did not work, don't hesitate to re-open.
