### ISSUE TITLE
Defining a parent group doesn't work anymore in group administration (9.5.2).

### ISSUE THREAD

**Issue by robertdiawara** [alkacon/opencms-core#397]
When creating a new user group, It's not possible to define the parent group in the group administration. The fieds suddenly disappeared after the upgrade from version 8.5.2 to version 9.5.3.

**Comment by tHerrmann** [comment]
Defining parent groups is deprecated and is no longer supported by the UI. Even though existing parent group settings will still work. We are not planing to reintroduce the feature and it may be removed completely in future versions.
