### ISSUE TITLE
Solr: "res_locales" and "con_locales" of containerpages always contain all configured locales

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#403]
In solr "res_locales" and "con_locales" of containerpages contain all configured locales even though there's no content for all these languages.
So filtering a search query by e.g. "fq=con_locales=fr" is not possible.

To reproduce it:
- Fresh installation of OpenCms 10
- Change opencms-system.xml to
```
...
      <localesconfigured>
        <locale>en</locale>
        <locale>de</locale>
        <locale>es</locale>
        <locale>fr</locale>
      </localesconfigured>
...
```
- http://localhost:8080/opencms/opencms/handleSolrSelect?core=Solr%20Offline&fq=type:containerpage
returns
```
...
	<arr name="res_locales">
		<str>de</str>
		<str>es</str>
		<str>fr</str>
		<str>en</str>
	</arr>
	<arr name="con_locales">
		<str>de</str>
		<str>es</str>
		<str>fr</str>
		<str>en</str>
	</arr>
...
```
for all containerpages.

**Comment by dSeidel** [comment]
It is intended that container pages are indexed for multiple locales. You can use one container page for multiple language versions of a web page. You can restrict the locales that it is indexed for by setting "locale-available".

**Comment by kartobi** [comment]
I change property "locale-available" to specific locale on each "language folder" but containerpages in solr still contain all configured locales

**Comment by dSeidel** [comment]
Did you rebuild the indexes?

**Comment by kartobi** [comment]
Not explicitly. Though it would be updated by publishing, but it won't if property was set on folder.
Thanks
