### ISSUE TITLE
offline JSPs not updated after reverting changes

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#404]
### Steps to reproduce

1. Edit a formatter jsp that hasn't been changed after its publication
2. Request an offline resource that uses it
3. Check that the element gets rendered using the edited formatter
4. Revert formatter changes

### Expected

The formatter gets compiled again, and the resource gets rendered using the original formatter

### Current

The formatter doesn't get compiled, the resource gets rendered using the modified formatter.

### Workaround

Delete JSPs: Administration > Cache Administration > Clear JSPs repositories

**Comment by aKandzior** [comment]
If you revert the formatter using "undo changes" you are also restoring the Jsp last modified date. Jsp compilation is triggered on this date. You must touch Jsp after undo changes. Otherwise version on rfs is newer and so no recompilation.
