### ISSUE TITLE
online JSPs not updated after publish

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#405]
### Steps to reproduce

1. Edit a formatter that hasn't been modified since its publication
2. Request an online resource that uses it
3. Check that it is rendered using the published formatter
4. Publish the formatter
5. Request the online resource from 2.

### Expected

OpenCms notices the modification, recompiles the online JSP and renders the resource with the formatter in its new version

### Current

The resource is rendered using the old formatter

### Workaround

Clear JSPs repository

**Comment by tHerrmann** [comment]
I can not reproduce the issue following the described steps.
But something like this may happen, if the date last modified attribute of the formatter JSP is older than the JSP file version in the real file system. The only way to achieve this is to my knowledge by reimporting a module containing changed JSP with a date last modified attribute matching the one of the current JSP version. That is something we considere as wrong usage.

**Comment by aKandzior** [comment]
I assume mixed up Jsp modification dates. Modification date of newly published Jsp must always be newer than the one last published.
