### ISSUE TITLE
Page Source search results is empty

### ISSUE THREAD

**Issue by veggie** [alkacon/opencms-core#407]
When searching in `Search Management` --> `Source search` (searching in field `Search pattern`), the list shows matches:
`Files matched: 16`

When clicking on `Ok`, the following screen is empty.

This was tested in a clean install of OpenCms 10.0.1 with the Demo modules installed.
Tested Browsers: Firefox 47, Chrome 51.

**Comment by gallardo** [comment]
Seems to me like a dup of https://github.com/alkacon/opencms-core/issues/244

**Comment by aKandzior** [comment]
We will delay a fix until we have a new interface for the search function in the workplace.
