### ISSUE TITLE
Method expected to redirect permanently, but redirects temporarily

### ISSUE THREAD

**Issue by paulflakstad** [alkacon/opencms-core#408]
The `org.opencms.util.CmsRequestUtil#redirectPermanently` method erroneously invokes the `javax.servlet.http.HttpServletResponse#sendRedirect`.

`sendRedirect` will issue a _temporary_ redirect (302), instead of the expected permanent redirect (301).

(From the `sendRedirect` method description: "Sends a temporary redirect response to the client using the specified redirect location URL.")

**Comment by aKandzior** [comment]
Should check this for 10.5.

**Comment by dSeidel** [comment]
This will be fixed in the OpenCms 10.5.1 release.

**Comment by tHerrmann** [comment]
This was fixed with release 10.5.1.
