### ISSUE TITLE
Impossible to install opencms to pre-configured database tables.

### ISSUE THREAD

**Issue by pStrudthoff** [alkacon/opencms-core#41]
- The setup dialog has two checkboxes that allow bypassing table-creation and
user creation. 
- If both are de-selected in the next step one is asked if the existing databse
should be dropped. 
- When deciding not to drop the pre-configured database tables setup goes back
to the database screen. 

This is a "nuisance" for DB-Admins who think that they  know a bit more on how
opencms tables should be stored on their DB. Sometimes there might be real
reasons why one would separate the Database / Table creation and the setup of
OpenCms (highly customized DB settings). 

cheers!
Achim

**Comment by aKandzior** [comment]
Old issue, won't fix.
