### ISSUE TITLE
 gwt ade client  chinese，japanese and russian language bound  dosn't  work 

### ISSUE THREAD

**Issue by twofisher** [alkacon/opencms-core#410]
hi,
It seems "messages\org\opencms\ade\galleries\clientmessages" not work when switch language to Chinsese、Japanise and Russian.
 
![chinese](https://cloud.githubusercontent.com/assets/12093283/17424850/5e29090a-5afa-11e6-97bd-dfbfb1ce42e8.jpg)

when  switch to chinese,  if "\ade\galleries\clientmessages_zh.properties" is encode in Unicode,the search tab  titles and other lables  all displayed as ???????.If the  "\ade\galleries\clientmessages_zh.properties"  is translate to HTML entities,as you see the title "类型、类别、虚拟文件夹、高级、结果"  and the checkbox is  correct, but the others will direct output the HTML entities as “& # 3 5 8 2 1 ;& # 3 5 3 2 8 ; & # 6 5 3 0 6 ;”. the above picture include UTF-8、HTML entities、Unicode encode .No one will work fine.If encode in Unicode,all displayed as ?????,if tranlate unicode to HTML entities,same lable will direct output HTML entities code.

As a comparison,here is the Japanise display picture  
![default](https://cloud.githubusercontent.com/assets/12093283/17424861/72314912-5afa-11e6-836d-bdf9da2cf08f.PNG)
![g1](https://cloud.githubusercontent.com/assets/12093283/17424880/96126262-5afa-11e6-9448-860ec70bc5ca.PNG)

And here is the Russian result
![russa](https://cloud.githubusercontent.com/assets/12093283/17424866/7d8ecf50-5afa-11e6-8ee6-3b1a34ed6aeb.PNG)

Apart from this,same ADE menu also has problem.the good news is that workplace and module managed is fine!

Is this a program error or properties file encoding errors?

Thanks!

**Comment by chirkovmail** [comment]
The solution is here #406.

**Comment by twofisher** [comment]
thanks chirkovmail ,it work fine.

**Comment by gallardo** [comment]
I can confirm that this also solves #415 .

**Comment by twofisher** [comment]
After add utf-8 to OpenCmsServlet as  solution #406, Opencms's Menu and Label is work,but a new problem occurred, Text disappear in Blog and Section editor ,and the edit tool bar is not found also,
