### ISSUE TITLE
Missing jar in Maven repository: opencms-widgetset.jar

### ISSUE THREAD

**Issue by veggie** [alkacon/opencms-core#412]
The file `opencms-widgetset.jar`, which is located in the `WEB-INF/lib` folder, seems not to be in a public  Maven repository. Could you please provide it,

**Comment by tHerrmann** [comment]
This jar contains non Java resources only and is not required when building any OpenCms dependend classes.
Why would you use it as a maven dependency?

**Comment by aKandzior** [comment]
Apparently we dont need this in maven repo.

**Comment by veggie** [comment]
Sorry, I had no time to answer. I am not sure how I should get this jar, when I do a Maven based build, when I do not have this as dependency. I am no Maven pro, so a hint how to get the file during a Maven build process would be very nice.

**Comment by tHerrmann** [comment]
What are you trying to build? This JAR contains no Java classes. So I don't know why you would need it as a dependency.

**Comment by veggie** [comment]
Hi @tHerrmann,
sorry for being not precise. It would be sufficient to have the JAR in a public Maven repository. Is that possible?

**Comment by tHerrmann** [comment]
I still don't get, for what porpose you would need this specific JAR as a dependency in any of your builds. Please give an example.

**Comment by veggie** [comment]
We are not using the gradle build. And we are not using one of the installers from opencms.org. We are building the project using opencms-basic (https://github.com/comundus/opencms-basic) and vfs-maven-plugin (https://github.com/comundus/vfs-maven-plugin) to build OpenCms. Therefore we have a dependency to opencms-core:
`
<dependency>
    <groupId>org.opencms</groupId>
    <artifactId>opencms-core</artifactId>
    <version>10.0.1</version>
</dependency>
`
opencms-core handles all its dependencies and copies them to WEB-INF/lib. As opencms-widgetset.jar is not a dependency, the jar is not in WEB-INF/lib. 
I am looking for a way to get this jar into my webapps lib folder, without copying this jar to the opencms-basic project and reference it from there. In my opinion it should be retrieved from the "most original" place.
I just need a way to retrieve this file from some public available location. I could use maven-download-plugin or whatever to get it. 
So I just need something where Maven can fetch that file from automatically.

**Comment by tHerrmann** [comment]
Thank you for the explanation. 
We will make this JAR available on maven central for future releases starting with 10.5.

**Comment by veggie** [comment]
Great. Thanks.
