### ISSUE TITLE
CmsMessagesService: charset not set resulting in mangled hints

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#415]
In `CmsMessagesService.service`, opencms tries to set the character encoding in the response:

```
response.setCharacterEncoding(request.getCharacterEncoding());
```

(See https://github.com/alkacon/opencms-core/commit/c97367cc4540c50f0538aa450fa524cb9258b27e#diff-d4a236366763576588203f1eee567aa4R67).

But `request.getCharacterEncoding()` returns `null`, so the response is not explicitly set (though I could verify that it is still ISO-8859-1 by default).

Apparently containers do not behave consistently in these circumstances, so e.g. Tomcat 6, or Tomcat 8 + javamelody do not append the `charset` to the header `Content-Type:`, while Tomcat 8 without filters does.
This results in the container building a 'text/javascript' response encoded in ISO-8859-1 that Firefox interprets as UTF-8.

Setting the encoding explicitly solves the problem. A different solution could be encoding every GWT property file in UTF-8 and sending it as such. This seems to me a better solution, as [GWT expects property files in UTF-8](http://www.gwtproject.org/doc/latest/DevGuideI18n.html#DevGuidePropertiesFiles). 

<sup>N.B.: I'm not filing a PR because I'm not sure about side effects, nor about your preferred solution.</sup>

**Comment by gallardo** [comment]
This is a dup of https://github.com/alkacon/opencms-core/issues/410

**Comment by gallardo** [comment]
After further investigations, I have the impression that it is in the site editor where the request has no encoding set. Other GUIs are displayed properly. Although https://github.com/alkacon/opencms-core/pull/406 fixes this by setting encoding to UTF-8 if not previously set, I'm not completely sure that this is the right thing to do:

> The default encoding of a request is “ISO-8859-1” if none has been specified by the client
[section 4.9 of the [servlet spec](https://jcp.org/aboutJava/communityprocess/first/jsr053/servlet23_PFD.pdf) ]

I'd still prefer re-encoding all gwt property files to UTF-8 (if I recall correctly, this also solved the problem in one of my experiments).

**Comment by gallardo** [comment]
I found the evidence in Tomcat's code. Tomcat 8 in the default configuration (`ENFORCE_ENCODING_IN_GET_WRITER=true`) sets the character encoding in `org.apache.catalina.connector.Response.getWriter()` if not set previously to satisfy the servlet Spec. Tomcat 6 does the same **only** if `STRICT_SERVLET_COMPLIANCE` is `true` [(the default is `false`)](http://tomcat.apache.org/tomcat-6.0-doc/config/systemprops.html#Specification) 

It's even nice documented!

### Excerpts from the sources

#### Tomcat 8.0.14
```java
    /**
     * Return the writer associated with this Response.
     *
     * @exception IllegalStateException if <code>getOutputStream</code> has
     *  already been called for this response
     * @exception IOException if an input/output error occurs
     */
    @Override
    public PrintWriter getWriter()
        throws IOException {

        if (usingOutputStream) {
            throw new IllegalStateException
                (sm.getString("coyoteResponse.getWriter.ise"));
        }

        if (ENFORCE_ENCODING_IN_GET_WRITER) {
            /*
             * If the response's character encoding has not been specified as
             * described in <code>getCharacterEncoding</code> (i.e., the method
             * just returns the default value <code>ISO-8859-1</code>),
             * <code>getWriter</code> updates it to <code>ISO-8859-1</code>
             * (with the effect that a subsequent call to getContentType() will
             * include a charset=ISO-8859-1 component which will also be
             * reflected in the Content-Type response header, thereby satisfying
             * the Servlet spec requirement that containers must communicate the
             * character encoding used for the servlet response's writer to the
             * client).
             */
            setCharacterEncoding(getCharacterEncoding());
        }

        usingWriter = true;
        outputBuffer.checkConverter();
        if (writer == null) {
            writer = new CoyoteWriter(outputBuffer);
        }
        return writer;
    }
```

#### Tomcat 6.0.45

```java
    /**
     * Return the writer associated with this Response.
     *
     * @exception IllegalStateException if <code>getOutputStream</code> has
     *  already been called for this response
     * @exception IOException if an input/output error occurs
     */
    public PrintWriter getWriter() 
        throws IOException {

        if (usingOutputStream)
            throw new IllegalStateException
                (sm.getString("coyoteResponse.getWriter.ise"));

        if (Globals.STRICT_SERVLET_COMPLIANCE) {
            /*
             * If the response's character encoding has not been specified as
             * described in <code>getCharacterEncoding</code> (i.e., the method
             * just returns the default value <code>ISO-8859-1</code>),
             * <code>getWriter</code> updates it to <code>ISO-8859-1</code>
             * (with the effect that a subsequent call to getContentType() will
             * include a charset=ISO-8859-1 component which will also be
             * reflected in the Content-Type response header, thereby satisfying
             * the Servlet spec requirement that containers must communicate the
             * character encoding used for the servlet response's writer to the
             * client).
             */
            setCharacterEncoding(getCharacterEncoding());
        }

        usingWriter = true;
        outputBuffer.checkConverter();
        if (writer == null) {
            writer = new CoyoteWriter(outputBuffer);
        }
        return writer;

    }
```

**Comment by aKandzior** [comment]
This needs to be solved for 10.5.

**Comment by aKandzior** [comment]
@gallardo Looked up your pulk request. Setting the encoding to null obviously is wrong. I dont even belive setting the encoding of the response to match the encoding of the request is a good idea. 

I suggest we just set this to UTF-8.

Explaination: The comments in your code / the Tomcat source suggest that the encoding has to be set by the servlet. Apparently the place where the encoding is set in your PR _is_ the servlet. So to me it looks like we can set any encoding here we find suitable. UTF-8 is the obvious choice, since iso-8859-1 seems to be rather outdated. Most Html responses these days appear to be UTF-8 anyway.

**Comment by gallardo** [comment]
@aKandzior I agree with UTF-8 being much more appropriate. My PR was based upon the principle of less impact on existing code: backing up to ISO-8859-1 seemed to me the most conservative approach and the least risky with regard to backwards compatibility. I'll try to do some testing tomorrow, though.

**Comment by gallardo** [comment]
For the records, the idiom `response.setCharacterEncoding(request.getCharacterEncoding())` seems to stem from [`CmsGwtService`](https://github.com/alkacon/opencms-core/blob/branch_10_5_x/src/org/opencms/gwt/CmsGwtService.java#L193) (parent of `CmsMessageService`). This method is invoked in [`OpenCmsCore.invokeGwtService(...)`](https://github.com/alkacon/opencms-core/blob/branch_10_5_x/src/org/opencms/main/OpenCmsCore.java#L1721) on a `CmsGwtService rpcService` object that I assume though to always be `instanceOf` CmsMessageService, and thus doesn't pose a problem.

But to me, it seems sensible to apply the same corrections to both incarnations of the idiom to avoid future problems. Alternatively, `CmsGwtService` and the `service()` method could be marked as abstract if the class is never used directly.

**Comment by gallardo** [comment]
Thinking aloud, more on the charset selection: it'd also look appropriate to set the character encoding to `OpenCms.getSystemInfo().getDefaultEncoding()`

**Comment by aKandzior** [comment]
Agreed, this seems to be the best choice. Also because the default is usually is UTF-8.

We will include this in 10.5.0 for sure.

**Comment by gallardo** [comment]
I could finally test the PR and it looks O.K. But I have some remarks:

- I have published https://github.com/alkacon/opencms-core/pull/425 to cope with the _detected_ issue. I added logs during my tests so I could verify that the PR fixes the bug.
- I couldn't reproduce the scenario where the `CmsMessagesService.service` is invoked with a request _with_ encoding set, that is, `request.getCharacterEncoding()` was always `null` during my tests. This makes me feel uncomfortable: in the worst case, I could have overseen cases where the request had an encoding and  the response now overrides it with a different one. This could break backwards compatibility (as in "it wasn't a bug, it was a feature, and now it doesn't work any more").
- I couldn't get the `CmsGwtService.service` method invoked either, but I have published https://github.com/alkacon/opencms-core/pull/428 to "fix" it anyway. As I don't have a clue if the method will be ever invoked, I've been more conservative (I don't override the encoding if it is set in the request), and have added logs too, so it could be understood under what circumstances it is invoked.

**Comment by gallardo** [comment]
@aKandzior after further investigations, I came again across the gwt docs, and their [FAQ_Troubleshooting.html#Internationalization](http://www.gwtproject.org/doc/latest/FAQ_Troubleshooting.html#Internationalization):

> - Check any associated Java properties files (or other files where you’ve stored translations) to see if they are saved in UTF-8 format.
> - Check the HTML host page. If your web page content contains localized data, encode it as UTF-8 by adding the following tag to the <head> element.

:confused: If this `service` is only invoked from GWT, we should set the encoding to UTF-8, with no further considerations.

**Comment by gallardo** [comment]
Update: after further testing, I couldn't get the [mojibake](https://en.wikipedia.org/wiki/Mojibake) back regardless of the  encoding set in the response or the version of Tomcat used.

**Comment by aKandzior** [comment]
Great! Looks like you got the issues solved. Thank you for your thorough research in this issue!

**Comment by dSeidel** [comment]
Merging PR #425 in OpenCms 10.5 should have solved the issue. Please reopen the ticket if this is not the case.
