### ISSUE TITLE
Where to DOWNLOAD really ?

### ISSUE THREAD

**Issue by magixsource** [alkacon/opencms-core#416]
On page http://www.opencms.org/en/development/installation/server.html tell me go to download page to download`Download the latest major release of OpenCms.`. so i visit http://www.opencms.org/en/download/ and distribution page http://www.opencms.org/en/download/opencms.html, and distribution page tell me "Just download the binary distribution ZIP file and follow the instructions on the installation page. "

and finally i found a link to donwload,`http://www.opencms.org/en/modules/downloads/begindownload.html?id=e1086355-3204-11e6-9420-7fde8b0295e1`, upgrade to 10 distribution ? I download it and install to tomcat, not work. Does its need pre version of opencms ? are you kidding me. 
Why not distribution link to LTS full version ?

**Comment by gallardo** [comment]
Seems to me like a dup of https://github.com/alkacon/opencms-core/issues/244

**Comment by aKandzior** [comment]
Sorry to hear you are unable to find the download link. 

The most recent stable release is available right from the home page http://www.opencms.org.

On the page 
http://www.opencms.org/en/download/opencms.html
you find links to all download binaries.
