### ISSUE TITLE
show info in which project one is in for page editor and launchpad

### ISSUE THREAD

**Issue by veggie** [alkacon/opencms-core#417]
One cannot see in which project (online or offline) one is. (Of course you can guess, that you are in Online project, when you do not have the edit icons). But if one has multiple "Offline" projects, one cannot. 
Add info in the toolbar which project one is in for page editor and launchpad.

**Comment by aKandzior** [comment]
Since 10.0.1 you see the project and site when you place the mouse over the text ("Page", "Explorer") in the upper left of the toolbar.
