### ISSUE TITLE
add project switch in page editor

### ISSUE THREAD

**Issue by veggie** [alkacon/opencms-core#418]
One cannot switch projects in page editor. Would be nice to have this as additional feature.

**Comment by aKandzior** [comment]
10.5 has a site switch in the page editor. A project switch was tried but removed. Reason was that users used this to switch to the online project. Since 10 uses only one browser window, that leads to the user actally getting "lost" online because there are no more controls onscreen. 

So switching to online in page editor is a really bad idea. Other offline projects may work, but are seldom used these days. What is your use case?

**Comment by veggie** [comment]
The idea is to minimize clicks for the user and thus optimize the usability. To prevent getting lost, we could keep the controls and just deactivate the buttons and greying them out (as in explorer view). In order to show were the user is, we could enhance the box in the top left corner and show "Project online: Page". And in Offline project correspondingly "Project offline: Page". (actually the prefix "Project on-/offline" could be used in all dialogs.

**Comment by aKandzior** [comment]
"Optimize the usability" is not a valid use case description.

The task  would require a significant change of the online / offline behavior and mean quite an amount of work. I don't see us going there anytime soon. 

In 10.5 the user can us the "Toggle edit button" switch and see the project as if it was published, so very close to "online".

**Comment by veggie** [comment]
Agreed, it is no use case. But a good usability is one of the most important things for a user to decide if he likes to use the software or not (of course you know that already, because OpenCms in general has a good usability). One needs at least 8 clicks to get from the page explorer in offline project back to the page explorer in online project. In my opinion way to much.
Coming to the use case:
A very common use case is, that an editor wants to see the differences between online and offline without using another browser (in some companies, is quite often just one browser allowed). The "Toogle edit button" does not help in this use case.
I thought it is not that much work, because the page explorer already has this "greyed out feature", when in online project.

**Comment by aKandzior** [comment]
In a real world setup the workplace URL and the online project URL is usually different. 

In this case we could simply open a new window to the online project. Would be covering your case?

**Comment by veggie** [comment]
Yes, that sounds good. Maybe showing "project online" in the browser title?
Thanks for the good discussion about this issue.
