### ISSUE TITLE
add breadcrumb for new workplace tools / add administration start page (launchpad) to breadcrumb in traditional wp tools

### ISSUE THREAD

**Issue by veggie** [alkacon/opencms-core#419]
I would like to suggest two things:
- add breadcrumb for new workplace tools. So it is easier to get to the parent of new wp page.
- add administration start page (launchpad) to breadcrumb in traditional wp tools. Currently one has to use the quick launch menu to get back to the launchpad, which is ok, but having the additional possibility via the breadcrumb would add a bit more usability. And, it would be one click less.

**Comment by aKandzior** [comment]
For traditional tools this should work. 

Not sure about new Wp tools though - will depend on tool / usability.

**Comment by tHerrmann** [comment]
We added a breadcrumb to the new workplace tools. This will always have the 'Launchpad' as it's first entry.
We will not do anything to the old legacy tools. They will either be rewritten or removed in future versions.

**Comment by tHerrmann** [comment]
This has been implemented since 10.5.1.
