### ISSUE TITLE
 After switch Destktop to chinese  or  janpanese, ADE can't edit Text 

### ISSUE THREAD

**Issue by twofisher** [alkacon/opencms-core#423]
When the desktop is switched to **Chinese** or **Japanese**, the editor of the text does not appear, edit toolbar will not be displayed.This problem is exsists in 10.0 and 10.5 beta.

OpenCms is 10.0.1,after Add a new module of org.opencms.locale.zh,Can't edit Text in SectionContent and Blog ariticles,the new Text plus button dosn't displayed. If I edit an Blog article already existe in VFS,the Text was disapeared also.
This is resource of zh,now it is empty(Text is always don't display what ever  it is emplty or not).
<img width="596" alt="formedit5" src="https://cloud.githubusercontent.com/assets/12093283/18666653/946a90d6-7f5f-11e6-9f3b-483f67f623f2.PNG">

Module export point set as other languges.

<img width="597" alt="formedit4" src="https://cloud.githubusercontent.com/assets/12093283/18666732/f65ea2a0-7f5f-11e6-897c-ff0f5ef1f4e8.PNG">

Resource path of module
<img width="596" alt="formedit3" src="https://cloud.githubusercontent.com/assets/12093283/18666741/fc3b6302-7f5f-11e6-9ad7-0778b697e2c7.PNG">

Blog article Form editor,no **Text edit box** and edit toolbar.
<img width="597" alt="formedit2" src="https://cloud.githubusercontent.com/assets/12093283/18666746/0314e626-7f60-11e6-957c-f458cf5fc368.PNG">

Section Content also can't edit Text,no Text input area.
<img width="668" alt="formedit1" src="https://cloud.githubusercontent.com/assets/12093283/18666751/093e4bd2-7f60-11e6-8c52-2d465c2b8206.PNG">

**Comment by aKandzior** [comment]
Needs to be checked for 10.5. 

@twofisher Can you help solving this issue? We have no access to native Chinese / Japanese speakers.

**Comment by gallardo** [comment]
@twofisher regarding your last screenshots, I could verify that the OpenCms editor requests the `CmsMessagesServices.service`. I would expect that https://github.com/alkacon/opencms-core/pull/425 and https://github.com/alkacon/opencms-core/pull/428 solve (at least part of) your problem...

**Comment by twofisher** [comment]
@aKandzior I'm happy to share the  chinese localization with opencms 10.5 users.

**Comment by aKandzior** [comment]
@twofisher this would be great. Apparently the encoding issue is solved thanks to @gallardo. 

10.5 final will be released next month. It would be great if you could contribute an updated chinese localization!

**Comment by gallardo** [comment]
Uhmm... Could you attach the server logs? This looks to me like a different problem, doesn't it?

**Comment by gallardo** [comment]
After looking into the code I cannot really see when could anything in that line be evaluated to `null`. Apparently, everything should be correctly set during startup. A test for `null` shouldn't be necessary. Are you getting that 500 also without the patch?

**Comment by twofisher** [comment]
@gallardo ,if dot path #406 #425 #428,opencms 10.5 beta work except language encode and ADE text editor problem 。
I use java 1.8 and tomcat 8.0.37

java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

The zip file contains two log files,the abstract is error message copy from opencms.log.
[opencms.log.zip](https://github.com/alkacon/opencms-core/files/526137/opencms.log.zip)

**Comment by gallardo** [comment]
Just to rule out easy-to-forget details: you have surely installed the `org.opencms.apollo.*` modules (22 modules in the 10.5.0 version), right? Your logs are quite explicit: your OpenCms cannot find `/WEB-INF/jsp/online/system/modules/org.opencms.apollo/templates/apollo-page.jsp`. This is packaged in `org.opencms.apollo.template.core`.
Notice that opencms-core doesn't include ("yet") the apollo templates, that is, if you are deploying opencms only from these sources, you'll end up with an empty OpenCms (that only has workplace).

**Comment by twofisher** [comment]
@gallardo I have include the new all apollo modules , but some file not import to opencms system modules.
I install it to tomcat-7. 0.72,It work!
@aKandzior **But the Ade edit can't use yet when the workplace switch to Chiense or Russan**.
![2016-10-14 11-40-52](https://cloud.githubusercontent.com/assets/12093283/19375211/71b8f452-9197-11e6-9d4d-cb1d399f4dd7.png)

**Comment by gallardo** [comment]
@twofisher Just out of curiosity, have you tested applying only #425? I personally feel that #406 is bogus: if the browser were to send a request with parameters encoded in ISO-8859-1, this PR will break the functionality.

**Comment by dSeidel** [comment]
Regarding the ADE-Editor: We can confirm the issue. Html fields are not editable. It seems to be a TinyMCE problem. We are working on it.

**Comment by dSeidel** [comment]
Hi @twofisher, I identified the problem. We use a codemirror plugin for the tinymce. If this misses the translation, the tinymce does not show up at all. Could you provide suitable translations in the attached files? Then Japanese and Chinese should work.

[ja.txt](https://github.com/alkacon/opencms-core/files/597550/ja.txt)
[zh.txt](https://github.com/alkacon/opencms-core/files/597551/zh.txt)

**Comment by twofisher** [comment]
Hi @dSeidel , great,it is now work. I add the two file to  opencms-core #449 .
Thanks！
