### ISSUE TITLE
Properties of CmsResource get lost using CmsRepository

### ISSUE THREAD

**Issue by pStrudthoff** [alkacon/opencms-core#43]
When extending org.opencms.repository.CmsRepositorySession, it is not possible
to change and save timestamps (like DateLastModified). They seem to get lost in
one of the wrappers. My test-class looks like this:

public class CmsRepositorySession extends
org.opencms.repository.CmsRepositorySession {
    private final CmsObjectWrapper cms;

public CmsRepositorySession(CmsObjectWrapper cms, CmsRepositoryFilterfilter) {
        super(cms, filter);
        this.cms = cms;
    }

public void setDateLastModified(String path, long time) throws CmsException{
        CmsFile file = cms.readFile(path, CmsResourceFilter.DEFAULT);
        file.setDateLastModified(time);
        cms.writeFile(file);
    }
}

I didn't test, but I guess this applies to most the properties you usually are
able to set on a CmsResource/CmsFile.

Background: I'm working on an almost working SMB-Interface for the VFS, which
sits on top of a repository. Unfortunately the interface I_CmsRepositorySession
seems to be optimized for WebDAV and lacks some usefull operations like
modifing dates.

**Comment by aKandzior** [comment]
SMB has been implemented since 9.5, so this issue can be considered solved.
