### ISSUE TITLE
UX: implement filter/quick-search path in "Add content > Folders"

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#432]
Navigating through the VFS tree is pretty inefficient and cumbersome:

![screenshot_2016-10-11_10-18-01](https://cloud.githubusercontent.com/assets/790448/19263605/6956be12-8f9d-11e6-9588-2c4a2953ce61.png)

The `Add content > Folders` options row should also render a path input box featuring a quick (recursive) search through the file tree, allowing filtering paths that doesn't match the filter:

![screenshot_2016-10-12_16-34-49](https://cloud.githubusercontent.com/assets/790448/19314424/5e45d21c-909a-11e6-9275-ab7e3566aea0.png)

**Comment by aKandzior** [comment]
This will be included in the upcoming 10.5.1 release.

**Comment by gallardo** [comment]
Beautiful! Verified :+1:
