### ISSUE TITLE
UX: show path in "Add content" menu if filtering/sorting by path [Enhacement]

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#434]
To improve usability, the path should be also presented in the results dialog:

![screenshot_2016-10-11_13-04-11](https://cloud.githubusercontent.com/assets/790448/19268414/b2327646-8fb4-11e6-8bfa-0d317c8f6b5f.png)

I'd suggest to use an additional column for the path in the results list, as there is plenty of unused space. Alternatively, an additional row with the path would suffice:

![screenshot_2016-10-11_13-04-11](https://cloud.githubusercontent.com/assets/790448/19268525/359844fc-8fb5-11e6-8eed-dcef1648162c.png)

or:

![screenshot_2016-10-11_13-04-11](https://cloud.githubusercontent.com/assets/790448/19268556/669f1814-8fb5-11e6-982e-3e12b3201437.png)

**Comment by aKandzior** [comment]
Included (in Part) in OpenCms 10.5. We show the path information now when the results tab is sorted by path.
