### ISSUE TITLE
UX-i18n: Switch language in ADE toolbar [Enhancement]

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#436]
The demo features a language switch in the template. It'd be very convenient to have it in the ADE toolbar:

![screenshot_2016-10-11_13-44-59](https://cloud.githubusercontent.com/assets/790448/19269993/ee2210fe-8fbd-11e6-8f74-64cb6ea552e2.png)

**Comment by aKandzior** [comment]
This will be available in 10.5 (in the main toolbar menu).
