### ISSUE TITLE
 UX-i18n: Add language switch in Explorer context menu [Enhancement] 

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#439]
See example:

![screenshot_2016-10-11_15-42-55](https://cloud.githubusercontent.com/assets/790448/19272962/f4e510c8-8fca-11e6-97ae-1d84186dffdd.png)

**Comment by tHerrmann** [comment]
I am not sure, what you want to achieve here. What should happen when clicking on 'de' or 'es'?

**Comment by gallardo** [comment]
Fair question. I must say that I have forgotten what I meant. Now I can only guess that I'd like OpenCMS to:

-  jump to the folder of the corresponding locale variant and select it

or

- open the resource in the selected locale

being this last one to me the most appealing functionality. This last one would save one navigation step.

**Comment by gallardo** [comment]
I'm closing this to not clutter the issues list with lower priority / non-optimal enhancements proposals.
