### ISSUE TITLE
UX: Make configurable the default selection in "Add content > Advanced > Search scope" [Enhancement][prio:low]

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#440]
If the current site is a subsite, the default search scope in `Add content > Advanced` menu should be `Subsite and shared folder`. (Nice-to-have: if not, the _Subsite *_ entries should be hidden.) Alternatively, the detection process could be skipped and this default selection could be made configurable.

![screenshot_2016-10-11_15-57-53](https://cloud.githubusercontent.com/assets/790448/19273676/a3c17a94-8fcd-11e6-9eb3-e44b9f72e020.png)

Additionally, the current text is ambiguous: it's not clear if the Subsite search is recursive (apparently it is, what to me is surprising given the non-plural form of _Subsite_).

**Comment by gallardo** [comment]
I noticed that the selection persist across requests, so it's questionable how important it is to implement this feature.

**Comment by tHerrmann** [comment]
The default setting is already configurable since version 9.0.0. 
Add the element 'gallery-default-scope' as last to the opencms-workplace.xml. Available settings are: everything, shared, site, siteShared, subSite and subSiteShared.

**Comment by gallardo** [comment]
Thanks!

**Comment by gallardo** [comment]
For the records, example config:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.opencms.org/dtd/6.0/opencms-workplace.dtd">

<opencms>
        <workplace>
                <!-- ... -->
                <gallery-default-scope>subSite</gallery-default-scope>
        </workplace>
</opencms>

```
