### ISSUE TITLE
UX: Remember status in "Add content" dialogue [Enhancement] 

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#442]
The "Add content" dialogue should remember:
- the **last selected path** and expand it by default when opening the dialogue later
  - If multiple paths were selected, expanding the first or last selected path suffices
- the results **sorting criteria** and the **view** (Details / Small images / Big images) and set it by default when opening the tab later

**Comment by aKandzior** [comment]
Included in OpenCms 10.5.
