### ISSUE TITLE
Localized resource name support

### ISSUE THREAD

**Issue by babinslava** [alkacon/opencms-core#445]
Could you add localized resource name support?
For example at first we changed resource name in database tables to get human readable and SEO friendly URL like this:
https://tirhleb.com/%D0%9F%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%86%D0%B8%D1%8F/%D0%9A%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3/%D0%9F%D0%B8%D1%80%D0%BE%D0%B6%D0%BD%D0%BE%D0%B5_%D0%9F%D0%BE%D1%81%D1%82%D0%BD%D0%BE%D0%B5_%D1%81_%D0%B2%D0%B8%D1%88%D0%BD%D0%B5%D0%B9/

But then we added such changes https://github.com/babinslava/opencms-core/commit/a74c0ebe082a9a2a0ef264df4403f240947f64c2

And now everything works fine. We also changed translation in opencms-vfs.xml .

It would be very convenient to have such functionality by default.

**Comment by aKandzior** [comment]
This is a good idea. Please provide a PR against our code base. Keep in mind that this should work for all other non latin alphabet-languages as well.

**Comment by kartobi** [comment]
@babinslava: would you mind to post the translations in opencms-vfs.xml as well?

**Comment by babinslava** [comment]
What we changed:
s#[\s]+#-#g  to  s#[\s]+#_#g (to use "_" as i remember)
and
s#[^0-9a-zA-Z_$~\.\-\/]#!#g  to  s#[^0-9a-zA-Zа-яА-Я_$~\.\-\/]#!#g (to use Russian letters)
