### ISSUE TITLE
Integration of OpenCMS with AngularJS

### ISSUE THREAD

**Issue by sowmyanayak14** [alkacon/opencms-core#446]
Is it possible to integrate OpenCMS with AngularJS

**Comment by tHerrmann** [comment]
Yes, there shouldn't be any problem using AngularJS with OpenCms generated pages. You can use any JavaScript framework with OpenCms.

By the way, this is an issue tracker, not a support forum. Please contact  the [mailinlist](http://www.opencms.org/en/development/mailinglist.html) if you have any further questions.
