### ISSUE TITLE
Editor doen't show tabs in the second row

### ISSUE THREAD

**Issue by jgregorio0** [alkacon/opencms-core#451]
Hello everyone! we are working with OpenCms version 10.0.1 and we found what it seems a bug:
1. While editing a resource with many tabs editor shows first row only:
![one-row-tabs](https://cloud.githubusercontent.com/assets/5246991/20303964/24e8df24-ab2e-11e6-9460-51d0d516f12b.png)

2. The second row is hidden because of the inline style:
![element-style-heigh](https://cloud.githubusercontent.com/assets/5246991/20304003/5d4b725a-ab2e-11e6-9b4d-233f705ef756.png)

3. We add this css rules for solving this problem temporarly:
```
.org-opencms-ade-contenteditor-client-css-I_CmsLayoutBundle-I_CmsXmlEditorCss-basePanel div.gwt-TabLayoutPanelTabBar.org-opencms-gwt-client-ui-css-I_CmsLayoutBundle-I_CmsGeneralCss-cornerTop,
.org-opencms-ade-contenteditor-client-css-I_CmsLayoutBundle-I_CmsXmlEditorCss-basePanel div.gwt-TabLayoutPanelTabBar.org-opencms-gwt-client-ui-css-I_CmsLayoutBundle-I_CmsGeneralCss-cornerTop .gwt-TabLayoutPanelTabs {
  height: auto !important;
}
```

**Comment by dSeidel** [comment]
Thanks for the hint. The issue will be fixed in the OpenCms 10.5 release.
