### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by RobinYang123** [alkacon/opencms-core#452]
I have deployed opencms(version 10.0.1), but I got a exception when accessing the url 'http://localhost:8080/opencms/opencms/tutorial/step-1-modify-a-page/index.html', and it reads like this:
java.lang.ClassNotFoundException: org.apache.jsp.WEB_002dINF.jsp.offline.system.modules.org_opencms_apollo_template_formatters.formatters.layoutrow_jsp
	at java.net.URLClassLoader.findClass(URLClassLoader.java:599)
	at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:134)
	at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:66)
	at org.apache.jasper.JspCompilationContext.load(JspCompilationContext.java:628)
	at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:149)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:340)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)

So did I download the wrong version or some configurations that I didn't complete? thanks

**Comment by RobinYang123** [comment]
seems I got the reason, when I remove the codes below, the system works quite well:

<apollo:container-box
            label="${content.value.Title}${column.value.Name.isSet ? ' - '.concat(column.value.Name) : ''}"
            boxType="detail-placeholder"
            type="${typeName}" />

**Comment by dSeidel** [comment]
Which Tomcat (or alike) and Java version are you using? I checked with the docker image for alkacon/opencms-docker:10.0.1 and everything works fine. This should also be the case for Tomcat 7 (or later) and Java 7 (or later).

**Comment by RobinYang123** [comment]
Thanks for your reply, I'll have a try with tomcat7. By the way, Do we have any documentation for creating a new website? If we do, then where is the download link, thanks again

**Comment by dSeidel** [comment]
Hi @RobinYang123, does the problem still occur with Tomcat 7? Which servlet container did you use before?
Concerning your question on documentation: The official documentation has some hints about how to create your own website. Have a look at the topics here: [http://documentation.opencms.org/opencms-documentation/creating-a-website/](http://documentation.opencms.org/opencms-documentation/creating-a-website/).
Moreover, the Apollo Template on which the demo is based will be released tomorrow. You may also want to use this template. From TOMORROW (afternoon), [http://documentation.opencms.org/opencms-documentation/creating-a-website/opencms-documentation/additional-documentation/the-apollo-template/](http://documentation.opencms.org/opencms-documentation/creating-a-website/opencms-documentation/additional-documentation/the-apollo-template/) will provide some introductory notes.

**Comment by RobinYang123** [comment]
Hi dSeidel,
Thanks a lot, the system works well with tomcat7 and I used apache-tomcat-6.0.41 before. And  the official documentation link you sent me is really helpful, thank you very much
