### ISSUE TITLE
Faile to load : /opencms/handleStatic/editors/tinymce/jscripts/tinymce/plugins/codemirror/langs/pt.js

### ISSUE THREAD

**Issue by leandrorp** [alkacon/opencms-core#455]
Hello,
When i set the language to portuguese, the inline edit stops to working, because the tinymce doesn´t find the file  below: 
Opencms Version : 10.0.5

 /opencms/handleStatic/editors/tinymce/jscripts/tinymce/plugins/codemirror/langs/pt.js

Thanks

**Comment by tHerrmann** [comment]
Hi,
you are right, the codemirror plugin for TinyMCE is missing a Portuguese localization file. May be you can help us out translating following keys, so we can add it to the next release scheduled for tomorrow?

tinymce.addI18n('pt',{
	'HTML source code': 'Add translation here',
	'Start search': 'Add translation here',
	'Find next': 'Add translation here',
	'Find previous': 'Add translation here',
	'Replace': 'Add translation here',
	'Replace all': 'Add translation here'
});

**Comment by leandrorp** [comment]
Sure! it will be a pleasure to help.

tinymce.addI18n('pt',{
'HTML source code': 'Código Fonte HTML',
'Start search': 'Iniciar pesquisa',
'Find next': 'Próximo',
'Find previous': 'Anterior',
'Replace': 'Substituir',
'Replace all': 'Substituir todos'
});

**Comment by tHerrmann** [comment]
Thanks a lot. This will be part of the next release.
