### ISSUE TITLE
“Post a new article” demo page can't save in OpenCms 10.5

### ISSUE THREAD

**Issue by superc** [alkacon/opencms-core#457]
“Post a new article” demo page can't save in OpenCms 10.5
URL path:
http://localhost:8080/apollo-demo/blog/new-article/

**Comment by bFeldberg** [comment]
This is a missing dependency in the blog module. It depends on the _org.opencms.ugc_ module. You can fix this in your installation by removing all blog demo contents (either by removing and reinstalling the democontent module or by manually deleting them) so you can remove the blog module. Then you just reimport the blog module (and the democontents after that if removed previously) and it should now use the UGC javascript library correctly.

The dependency will of course be corrected, thank you.

**Comment by tHerrmann** [comment]
This was fixed with release 10.5.1.
