### ISSUE TITLE
could not run a build on branch_9_0_x, get following errors:

### ISSUE THREAD

**Issue by Jerrrrrrry** [alkacon/opencms-core#458]
builddeps:
get-dependency-paths:
compile-classes:
compile-gwt:
     [echo] Deleting GWT output folder: C:\workspace\opencms-core\modules\org.opencms.ade.containerpage\resources\system\modules\org.opencms.ade.containerpage\resources\containerpage
     [java] Compiling module org.opencms.ade.containerpage.ContainerpageEditor
     [java]    Validating units:
     [java]       [ERROR] Errors in 'file:/C:/workspace/opencms-core/src-gwt/org/opencms/ade/containerpage/client/ui/CmsContainerPageContainer.java'
     [java]          [ERROR] Line 249: The method add(Widget, Element) in the type ComplexPanel is not applicable for the arguments (Widget, Element)
     [java]          [ERROR] Line 424: The method insert(Widget, Element, int, boolean) in the type ComplexPanel is not applicable for the arguments (Widget, Element, int, boolean)
     [java]       [ERROR] Errors in 'file:/C:/workspace/opencms-core/src-gwt/org/opencms/ade/containerpage/client/ui/CmsContainerPageElementPanel.java'
     [java]          [ERROR] Line 173: The constructor AbsolutePanel(Element) is undefined
     [java]          [ERROR] Line 426: The method markForInlineFocus(Element) in the type EditorBase is not applicable for the arguments (Element)
     [java]          [ERROR] Line 656: The method add(Widget, Element) in the type ComplexPanel is not applicable for the arguments (CmsListCollectorEditor, Element)
     [java]          [ERROR] Line 686: The method add(Widget, Element) in the type ComplexPanel is not applicable for the arguments (CmsListCollectorEditor, Element)
     [java]       [ERROR] Errors in 'file:/C:/workspace/opencms-core/src-gwt/org/opencms/ade/contenteditor/client/widgets/CmsAdeDownloadGalleryWidgetFactory.java'
     [java]          [ERROR] Line 44: The type CmsAdeDownloadGalleryWidgetFactory must implement the inherited abstract method I_WidgetFactory.createInlineWidget(String, Element)
     [java]       [ERROR] Errors in 'file:/C:/workspace/opencms-core/src-gwt/org/opencms/ade/contenteditor/client/widgets/CmsAdeImageGalleryWidgetFactory.java'
     [java]          [ERROR] Line 44: The type CmsAdeImageGalleryWidgetFactory must implement the inherited abstract method I_WidgetFactory.createInlineWidget(String, Element)
     [java]       [ERROR] Errors in 'file:/C:/workspace/opencms-core/src-gwt/org/opencms/ade/contenteditor/client/widgets/CmsCalendarWidgetFactory.java'
     [java]          [ERROR] Line 43: The type CmsCalendarWidgetFactory must implement the inherited abstract method I_WidgetFactory.createInlineWidget(String, Element)
     [java]       [ERROR] Errors in 'file:/C:/workspace/opencms-core/src-gwt/org/opencms/ade/contenteditor/client/widgets/CmsCategoryWidgetFactory.java'
     [java]          [ERROR] Line 43: The type CmsCategoryWidgetFactory must implement the inherited abstract method I_WidgetFactory.createInlineWidget(String, Element)
     [java]       [ERROR] Errors in 'file:/C:/workspace/opencms-core/src-gwt/org/opencms/ade/contenteditor/client/widgets/CmsCheckBoxWidgetFactory.java'
     [java]          [ERROR] Line 45: The type CmsCheckBoxWidgetFactory must implement the inherited abstract method I_WidgetFactory.createInlineWidget(String, Element)
     [java]       [ERROR] Errors in 'file:/C:/workspace/opencms-core/src-gwt/org/opencms/ade/contenteditor/client/widgets/CmsColorpickerWidgetFactory.java'
     [java]          [ERROR] Line 43: The type CmsColorpickerWidgetFactory must implement the inherited abstract method I_WidgetFactory.createInlineWidget(String, Element)
     [java]       [ERROR] Errors in 'file:/C:/workspace/opencms-core/src-gwt/org/opencms/ade/contenteditor/client/widgets/CmsComboWidgetFactory.java'
     [java]          [ERROR] Line 43: The type CmsComboWidgetFactory must implement the inherited abstract method I_WidgetFactory.createInlineWidget(String, Element)
     [java]       [ERROR] Errors in 'file:/C:/workspace/opencms-core/src-gwt/org/opencms/ade/contenteditor/client/widgets/CmsDisplayWidgetFactory.java'
     [java]          [ERROR] Line 43: The type CmsDisplayWidgetFactory must implement the inherited abstract method I_WidgetFactory.createInlineWidget(String, Element)
     [java]       [ERROR] Errors in 'file:/C:/workspace/opencms-core/src-gwt/org/opencms/ade/contenteditor/client/widgets/CmsGroupWidgetFactory.java'
     [java]          [ERROR] Line 43: The type CmsGroupWidgetFactory must implement the inherited abstract method I_WidgetFactory.createInlineWidget(String, Element)
     [java]       [ERROR] Errors in 'file:/C:/workspace/opencms-core/src-gwt/org/opencms/ade/contenteditor/client/widgets/CmsHtmlGalleryWidgetFactory.java'
     [java]          [ERROR] Line 45: The type CmsHtmlGalleryWidgetFactory must implement the inherited abstract method I_WidgetFactory.createInlineWidget(String, Element)
     [java]       [ERROR] Errors in 'file:/C:/workspace/opencms-core/src-gwt/org/opencms/ade/contenteditor/client/widgets/CmsHtmlWidgetFactory.java'
     [java]          [ERROR] Line 53: The type CmsHtmlWidgetFactory must implement the inherited abstract method I_WidgetFactory.createInlineWidget(String, Element)
     [java]          [ERROR] Line 124: The constructor TinyMCEWidget(Element, JavaScriptObject) is undefined

[full logs.txt](https://github.com/alkacon/opencms-core/files/636935/full.logs.txt)

**Comment by tHerrmann** [comment]
Since version 9.0.0  Gradle is used to build OpenCms. Use the war task to build the OpenCms WAR file.
The ANT scripts are deprecated and may no longer work.
