### ISSUE TITLE
CmsSelectWidget accepts <optgroup>

### ISSUE THREAD

**Issue by pStrudthoff** [alkacon/opencms-core#46]
Hi.

I think it will be interesting that CmsSelectWidget accepts '<optgroup>' label.

It's just a little modification, we have it done already.

in CmsSelectWidgetClass:

public final static String OPTGROUP_START_VALUE = "optgroup_start";
public final static String OPTGROUP_END_VALUE   = "optgroup_end";
...

public String getDialogWidget(CmsObject cms, I_CmsWidgetDialog widgetDialog,
I_CmsWidgetParameter param){

...
CmsSelectWidgetOption option = (CmsSelectWidgetOption)i.next();

if(OPTGROUP_START_VALUE.equals(option.getValue())){
   result.append("<optgroup label=\"")
            .append(option.getOption())
            .append("\">");
}
else if(OPTGROUP_END_VALUE.equals(option.getValue())){
   result.append("</optgroup>");
}
else{
   // create the option
   ...
}
...
}

**Comment by aKandzior** [comment]
Closing this old issue.
