### ISSUE TITLE
UX: Remembered path in "Add content" dialogue not shown in "Folders" view

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#461]
<sup>(Related to https://github.com/alkacon/opencms-core/issues/442)</sup>
Although the selected path is being remembered, the "folders" filter view doesn't reflect it.

Multiple path filters set:
![screenshot_2016-12-13_14-47-16](https://cloud.githubusercontent.com/assets/790448/21142573/27260430-c143-11e6-9e32-f0e77e61bec5.png)

The folders view is empty when editing another container page:
![screenshot_2016-12-13_14-49-13](https://cloud.githubusercontent.com/assets/790448/21142613/5934063e-c143-11e6-8b8d-4a65d30bd1b5.png)

Expected:
![screenshot_2016-12-13_14-53-32](https://cloud.githubusercontent.com/assets/790448/21142757/f3f984f0-c143-11e6-92b4-140850528e0e.png)

Tested git revision: https://github.com/alkacon/opencms-core/commit/99ba95829b0c97407c5cf4a87219e3433c9f1779

**Comment by tHerrmann** [comment]
You are right, this is a bug.

**Comment by tHerrmann** [comment]
This was fixed with release 10.5.1.

**Comment by gallardo** [comment]
Thanks! Verified :+1:
