### ISSUE TITLE
About New User error tip in opencms 10.5

### ISSUE THREAD

**Issue by superc** [alkacon/opencms-core#463]
![20161217151509](https://cloud.githubusercontent.com/assets/3608960/21285163/2e6ba566-c46c-11e6-9542-57cb0a53a933.png)

**Comment by tHerrmann** [comment]
Hi,
I don't get the issue. Please describe in detail, what is going wrong.

**Comment by superc** [comment]
Friendly prompt is not perfect.
“org.opencms.workplace.tools.accounts.CmsEditUserDialog”
“org.opencms.file.CmsUser”
there are no localized

**Comment by tHerrmann** [comment]
The user management is due to be rewritten. We wont fix this kind of issue on the old management.
