### ISSUE TITLE
Lost workspace

### ISSUE THREAD

**Issue by texduc** [alkacon/opencms-core#466]
Hello; I tried to login to my workspace but it has disappeared; how do we restore it?

The requested resource "/crop/system/workplace/views/workplace.jsp" was not found on the server.

**Comment by dSeidel** [comment]
Did you configure a second site? If so, the workplace-server has to be configured correctly in the opencms-system.xml.
E.g., if you specify <workplace-server>http://localhost:8080</workplace-server>, you can access the workplace only via http://localhost:8080/....

**Comment by tHerrmann** [comment]
Since OpenCms 10 using "/system/workplace/views/workplace.jsp" is deprecated, it requires the module "org.opencms.workplace.traditional" to be installed.
Use "/system/login/" to log into the workplace.
