### ISSUE TITLE
Error reading resource

### ISSUE THREAD

**Issue by superc** [alkacon/opencms-core#468]
Editing resource exception in website foreground when using ```<cms:editable/>```  in template.

Version 10.5

![1](https://cloud.githubusercontent.com/assets/3608960/21382808/87ccc840-c79d-11e6-9d76-5e33f999bcf7.png)

HTTP Status 404 - org.opencms.file.CmsVfsResourceNotFoundException: Error reading resource from path "/system/workplace/views/top_foot.jsp".

![2](https://cloud.githubusercontent.com/assets/3608960/21382840/ae8c098c-c79d-11e6-9ba4-dad65e8747de.png)

**Comment by tHerrmann** [comment]
This was fixed with release 10.5.1.
