### ISSUE TITLE
Localize file type in explorer view

### ISSUE THREAD

**Issue by pStrudthoff** [alkacon/opencms-core#47]
When creating a new file, e.g. some structured content, the type is localized
in the wizard and the actual type name is not displayed.

However, in the explorer the actual type name is displayed and there's no
possibility to localize it.

This is inconsistent and might cause confusion with the users.

Example:

Real type name in the explorer: TermsPage
Localized name in the German wizard: AGB-Seite

There's no obvious correlation between these two so the user might not notice
that the "AGB-Seite" she created is actually of type TermsPage.

**Comment by aKandzior** [comment]
Closing this old issue.
