### ISSUE TITLE
Modifying the folders title invalid for Categories in OpenCms 10.5

### ISSUE THREAD

**Issue by superc** [alkacon/opencms-core#470]
Copy The /.categories/ folder to /apollo-demo/.categories/ and modifying the folders title invalid of "Assing categories" dialogs in content editor.

![u-1](https://cloud.githubusercontent.com/assets/3608960/21470010/181045fc-cab0-11e6-926f-26799fc07d98.png)

![u-2](https://cloud.githubusercontent.com/assets/3608960/21470011/2584bd9e-cab0-11e6-8614-cbb8f0c8ee00.png)

**Comment by dSeidel** [comment]
Hi @superc we do not support having the same category twice. You copied the categories, so you have, e.g., topic/ twice and in your second screenshot the instance you did not expect was chosen.
