### ISSUE TITLE
Compatibility request

### ISSUE THREAD

**Issue by Shaand** [alkacon/opencms-core#473]
URGENT Request:
We are in situation to upgrade our CentOS, therefore please confirm us the following.

1) Please confirm whether the OpenCMS v9.0.1 is compatible with CentOS 7?
2) We know OpenCMS v9.0.1 is compatible with Tomcat 7 - However please confirm?
3) Is it OpenCMS v9.0.2 is compatible with Postgres DB v9.2

Please let us know the above as soon as possible.

Thanks
Shaan

**Comment by tHerrmann** [comment]
This is not a support forum. For compatibility of OpenCms please see the release notes of the respective version.
