### ISSUE TITLE
Dynamic function not work in OpenCms 10.5

### ISSUE THREAD

**Issue by glonis** [alkacon/opencms-core#475]
When I drag an existing dynamic function in a container page and refresh (f5), the element disappears
![sc1](https://cloud.githubusercontent.com/assets/2591337/22072223/ecf542b4-dda1-11e6-9f15-9ca9402195d7.jpg)
![sc2](https://cloud.githubusercontent.com/assets/2591337/22072224/ecfb82f0-dda1-11e6-9f82-ca141d8d5f36.jpg)
![sc3](https://cloud.githubusercontent.com/assets/2591337/22072225/ecfd2c9a-dda1-11e6-970e-ff7614acd84c.jpg)

.

**Comment by tHerrmann** [comment]
We have fixed this issue with commit c1cfe53. This will be part of the upcoming release of OpenCms 10.5.1 in early February.
You can check out the current head of branch_10_5_x to test this.

**Comment by tHerrmann** [comment]
This was fixed with release 10.5.1.
