### ISSUE TITLE
CmsDefaultLinkSubstitutionHandler forces all links without secure flag to http

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#476]
We are running a site with both "http" as well as "https" 
The behaviour when browsing with https changed now, after updating from 9.0.1 to 10.5.

So far, all internal links wrapped with <cms:link> have been rendered without protocol and domain (except pages with property "secure=true")
Now they are forced to http, server prefix is appended (except pages with property "secure=true")

The cause is added ```cms.getRequestContext().isSecureRequest()``` for secureRequest flag in CmsDefaultLinkSubstitutionHandler:
```
boolean secureRequest = cms.getRequestContext().isSecureRequest() || exportManager.isSecureLink(cms, oriUri);
```

So else-if lateron prepends http-url of targetSite:
```
if (secureLink && (forceSecure || !secureRequest)) {
	serverPrefix = targetSite.getSecureUrl();
} else if (!secureLink && secureRequest) {
	serverPrefix = targetSite.getUrl();
}
```

As far as I can see, the if-condition alone would be right:
```
if (secureLink && (forceSecure || !secureRequest)) {
	serverPrefix = targetSite.getSecureUrl();
}
```

**Comment by gWestenberger** [comment]
The idea is that if you 'change context' (go from HTTP to HTTPS or vice versa), the server prefix with the correct protocol for the link target is prepended.

If you have resources which you use (link to) from both secure and non-secure pages (e.g. CSS files), you can set the 'secure' property to 'both' on these to prevent the server prefix from being prepended.

**Comment by kartobi** [comment]
So I need to set "secure=both" on /sites/default/ ?
