### ISSUE TITLE
Can't create a container page with content element together

### ISSUE THREAD

**Issue by maisasb** [alkacon/opencms-core#477]
I'm using opencms version 10.5
I created a new template model with a copied xml content, 
![img1](https://cloud.githubusercontent.com/assets/25438419/22436487/738c9652-e70b-11e6-9d44-5a59c1f049a9.png)
and in the sitemap configuration, I set this content element to create new content together with the page. 
![img3](https://cloud.githubusercontent.com/assets/25438419/22436510/80d001fa-e70b-11e6-9143-fe02ea85508c.png)
But this error occurs when I drop the template to create a new page in the sitemap editor:
"Error creating the resource "/sites/opencms/news/page-00012/.elements/".
Reason:Error creating the resource "/sites/opencms/news/page-00012/.elements/". The parent folder is locked by another user."
![img2](https://cloud.githubusercontent.com/assets/25438419/22436494/7a71624a-e70b-11e6-95b0-0a5cef4111c5.png)

Only the admin user can make this page creation work.
And I checked the permissions and they are the same for both users.

I think this is a bug in opencms 10.5    ._.
Thank's

**Comment by dSeidel** [comment]
Hi @maisasb,

the exception says that the parent folder is locked by another user. Have you checked for locks and removed or took over all possibly present locks before you added the new page?

**Comment by maisasb** [comment]
Hi @dSeidel,
Thanks for reply.
 Yes. I logged in with the admin user and unlocked all the resources and removed all the publish locks in the admin view. Nothing solved my problem.
With another user I can't create pages this way.
:(

**Comment by dSeidel** [comment]
Hi @maisasb,
I tried to reproduce the behavior - and you are right, it's a bug. We'll try to fix it in the next release.

**Comment by tHerrmann** [comment]
This has been fixed in release 10.5.1.
