### ISSUE TITLE
OpenCMS 10.5: can't map Title field to url

### ISSUE THREAD

**Issue by alessandro-violante** [alkacon/opencms-core#481]
Hi, 

I'm using OpenCMS v10.5 and I'm having some problems trying to map the urls of a resource type. 
The result is that the mapTo property doesn't work properly and my url isn't what I expect it to be. I don't know what's the configuration of the database, because I do not handle that, but I've followed the guide about detail page creation:

http://documentation.opencms.org/opencms-documentation/demos/lists-and-detail-pages/index.html 

The only difference I'm getting is the following that can be seen in this screenshot;

![sitemap](https://cloud.githubusercontent.com/assets/25792930/22973425/eb1b77c8-f37d-11e6-88e7-5f095a946386.jpg)

What should I do? What could be my problem? 

Do you need my code?

Thanks, 

Alex

**Comment by tHerrmann** [comment]
Hi Alex,
assuming you have placed the mapping definition in your resource type schema like this:
<mapping element="Title" mapto="urlName" />
You would not see the generated URL names within the sitemap editor, but only when linking to a specific event.

**Comment by alessandro-violante** [comment]
Hi,

Yeah, I've attached the image only because that was the only slight different thing I've seen on the screen (the "eventi" page is a "resource"). 

Is there something else I should do in order to see the correct mapping? Maybe some parameter in Modules management?

**Comment by aKandzior** [comment]
Can you please provide more information about what you want to achieve with the content mapping and what does not work?

**Comment by tHerrmann** [comment]
As no further info is provided, we are closing this issue.
