### ISSUE TITLE
opencms.ade.upload.CmsUploadException: No File Items Found in the request

### ISSUE THREAD

**Issue by aruncoder** [alkacon/opencms-core#482]
I've tried deploying opencms 8 and 9 series in glassfish 3.1.2 open source edition.
Deployment was successful. But when I try to upload anything file/zip format using GWT uploader / Applet or Basic Upload, I am getting the below error
**opencms.ade.upload.CmsUploadException: No File Items Found in the request**

Please see the attached file...
![uploaderror](https://cloud.githubusercontent.com/assets/26062226/23362053/e294d734-fd19-11e6-978e-49469f488634.png)

**Comment by aruncoder** [comment]
I am attaching opencms web.xml as well. As its mentioned, I had to remove the comments and description xml tags to make it working.

**Comment by aKandzior** [comment]
Does this also apply to OpenCms 10.0 or 10.5?

**Comment by tHerrmann** [comment]
We can not reproduce the issue and no further information supplied.
