### ISSUE TITLE
Wrong dropdown position in TinyMCE

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#485]
In case `<body>` has `position: relative;`,
```
body {
  position: relative;
}
```
the dropdown and tooltip position in editor isn't calculated correctly:
![dropdown_position](https://cloud.githubusercontent.com/assets/2276952/23704459/f9668f7c-03fc-11e7-9c31-18d3d9309f55.png)

**Comment by tHerrmann** [comment]
We fixed the issue by updating TinyMCE to version 4.6.2 in f8bd407bfd1c329a5d8233634b536ecc3bd59b3c.

**Comment by tHerrmann** [comment]
The fix to this issue has been released with version [10.5.2](https://github.com/alkacon/opencms-core/releases/tag/build_10_5_2).
