### ISSUE TITLE
LocationPickerWidget alters the coordinates of the selected point

### ISSUE THREAD

**Issue by amagnolo** [alkacon/opencms-core#486]
Selecting a point on the map in LocationPickerWidget, the widget performs an address lookup; the returned address coordinates override the selected point coordinates, often resulting far too distant from the correct location.

When the user selects a specific point on the map, its coordinates should be stored verbatim.
In the example attached, I want to select the bridge on the lake near the Mediapark, but after closing and reopening the widget, the point is moved to another location.

Selection of the correct point by marker drag and drop:
![before](https://cloud.githubusercontent.com/assets/1140372/23745283/f53e8952-04b7-11e7-9863-6ceb9371cdac.png)

After closing and reopening the widget:
![after](https://cloud.githubusercontent.com/assets/1140372/23745393/44f9e57c-04b8-11e7-9ea1-0ad42da19b2b.png)

**Comment by aKandzior** [comment]
Con confirm this. Needs to be fixed!

**Comment by tHerrmann** [comment]
This should be fixed by the commit above.

**Comment by tHerrmann** [comment]
The fix to this issue has been released with version [10.5.2](https://github.com/alkacon/opencms-core/releases/tag/build_10_5_2).
