### ISSUE TITLE
"Show in device": Edit bar in device preview visible

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#487]
If parameter "__disableDirectEdit=false" exists in url, edit bar is visible:

![show_in_device_nok](https://cloud.githubusercontent.com/assets/2276952/23801872/86f1fa40-05a9-11e7-88be-1ff03ee9ac21.png)

Should be hidden:

![show_in_device_ok](https://cloud.githubusercontent.com/assets/2276952/23801879/91f06fd0-05a9-11e7-8aab-d408a1966a06.png)

Tested with OpenCms 10.5.1

**Comment by tHerrmann** [comment]
The commit above fixes the issue.

**Comment by tHerrmann** [comment]
The fix to this issue has been released with version [10.5.2](https://github.com/alkacon/opencms-core/releases/tag/build_10_5_2).
