### ISSUE TITLE
"Show in device": wrong content size

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#488]
Defined size in templatecontexts.json is 375 x 667:
```
"iphone6": {
	"niceName": "iPhone 6 (portrait)",
	"width": 375,
	"height": 667
},
```

The resulting size is 315 x 607:

![show_in_device_content_size](https://cloud.githubusercontent.com/assets/2276952/23802173/5dd484b0-05aa-11e7-93a9-b02df7309ec7.png)

Maybe automatically add 17 or 18 pixel for vertical scrollbar to width would be helpful as well.

**Comment by aKandzior** [comment]
Out of curiosity: 

Now that every modern browser has development tools that are much better in emulating a mobile device, is this still a feature that the OpenCms core needs to support in a future version?

**Comment by kartobi** [comment]
Hmm, regarding this functionality I never thought about developers, but as a tool for content editors.
Usually employees in big companies are not able to install browser tools, so "Show in device" might be helpful regarding text lengths, image positions, etc.
But I don't know, if it is a frequently-used feature :-)

**Comment by patric-dosch-vi** [comment]
👍

**Comment by patric-dosch-vi** [comment]
I know our customers use it. Perhaps because the Internet Explorer tools are not very helpful here.

**Comment by tHerrmann** [comment]
The commit above should fix the issue by increasing the configured screen width in case the preview content height is greater than the screen height of the preview.

**Comment by Florencia007** [comment]
Hi, I don't see the "show in device" in the element properties. can you help me to fix this?
