### ISSUE TITLE
Exception should be written to opencms.log, not only to webserver log

### ISSUE THREAD

**Issue by jm009** [alkacon/opencms-core#490]
In org.opencms.search.solr.CmsSolrIndex.java, Version 10.5.1, line 302, e.printStackTrace();, an exception is written in the webserver (Tomcat) log. I was only looking for errors in opencms.log... Took me quite a lot of hours... ;-)

**Comment by gallardo** [comment]
Have you already written a PR?

**Comment by dSeidel** [comment]
The issue will be fixed in the next release.

**Comment by tHerrmann** [comment]
The fix to this issue has been released with version [10.5.2](https://github.com/alkacon/opencms-core/releases/tag/build_10_5_2).
