### ISSUE TITLE
Misleading google maps api key error when using LocationPicker-Widget

### ISSUE THREAD

**Issue by Belarophon** [alkacon/opencms-core#491]
We have problems using the LocationPicker-Widget in openCMS 10.5.1. Whenever we specify a new location, it is empty. So no preview is shown. When trying to edit it (folder-symbol) it shows the error message 'Missing Google Maps API Key...'. The problem is that we provided a valid key via the root folder properties. Debugging the method CmsLocationPickerWidget.getConfiguration() also confirmed that our provided key is used. The problems seems to be the missing map preview, since this is also one of the things that  is checked in method CmsLocationController.hasError().

<img width="951" alt="error message" src="https://cloud.githubusercontent.com/assets/19167309/25118632/68a96cb2-2417-11e7-8f17-51981f2c328f.png">

We tried a workaround (editing the control code manually and inserting the xml-formatted location-code from some 'old' component) and voila - the map preview is shown and also the folder-button to edit the location works.

<img width="1250" alt="manually providing location" src="https://cloud.githubusercontent.com/assets/19167309/25118646/76eea454-2417-11e7-8f1b-defdce7cff6b.png">

<img width="1075" alt="working location picker" src="https://cloud.githubusercontent.com/assets/19167309/25118647/76efccc6-2417-11e7-96aa-6175be0d4187.png">

Remarks/Questions:
1. How do I debug the code of packages org.opencms.gwt.client and beyond? Unfortunatly the 'normal' debugging doesn't work here. At least it doesn't stop at the specified breakpoints in class CmsLocationController. For org.opencms.widgets.CmsLocationPickerWidget debugging works...
2. The error message is a bit misleading since you can also provide the key via the location picker widget config in the XSD and even if it is provided correctly, the error is still shown...

**Comment by Belarophon** [comment]
Improved the workaround by specifying a default location in the top-level-XSD (the Location itself was located in a nested element):

<defaults>
<default element="Location/Location" value='{ "address": "Theresienhöhe 12, München", "lat": 48.133879, "lng": 11.545253, "height": 300, "width": 400, "mode": "", "type":"roadmap", "zoom": 18}' />
</defaults>

Somehow the London-default value was not used.

**Comment by tHerrmann** [comment]
The commit above fixes the issue. It is no longer necessary to set a default value for the widget to work.

**Comment by tHerrmann** [comment]
The fix to this issue has been released with version [10.5.2](https://github.com/alkacon/opencms-core/releases/tag/build_10_5_2).
