### ISSUE TITLE
list with <cms:search> and static export for new items

### ISSUE THREAD

**Issue by abarrigas** [alkacon/opencms-core#492]
Hi.

I'm experiencing an issue related with the <cms:search> list method when I export my site to static with OpenCMs 10.5.0.

These are the steps to reproduce the issue:

Using your example as a base (http://documentation.opencms.org/opencms-documentation/caching-in-opencms/static-export/) I configure my site for static export after publish (by the way, in your example I think you should change <regex>sites/mysite/modules/news/.*</regex> with <regex>/sites/mysite/.content/news/.*</regex>)

Then, I create, save and export a new item, but the static index.html is not updated, although it is exported (so it is exactly as it was before the new item creation).

After, if I edit the new item, index.html is updated correctly with the last changes.

I've been trying to figure out the reason, and after reading the publishing log, I've found that solr is updated AFTER the index.html export, so maybe, it doesn't work because solr should be updated before the export (to include the new item) and after (to update the solr wth the new idex.html content).

Does anyone have this same problem?

**Comment by tHerrmann** [comment]
You have to implement you own static export handler to resolve this issue. When using the cms:search tag to create a list of elements, there will be no relation stored in OpenCms indicating the connection between the list elements and the list page. Thus OpenCms is not able to determine the list page needs to be reexported when changing or adding an element to the list. 
When implementing your own static export handler, you know these hidden relations and can act accordingly.
