### ISSUE TITLE
JS-Exceptions when using VfsFileWidget

### ISSUE THREAD

**Issue by Belarophon** [alkacon/opencms-core#493]
When using the VfsFileWidget to select a folder I get 2 different types of exceptions. The first one is the following (when using it in opencms 10.0.0 with configuration="selectabletypes=folder|excludefiles"):

<img width="1339" alt="folder selection error" src="https://cloud.githubusercontent.com/assets/19167309/25372259/f6b5c6c2-2994-11e7-8ef5-9c077c1cb0f9.png">

Index: -1, Size: 1

Ticket Id: 1493103088799
java.lang.IndexOutOfBoundsException: Index: -1, Size: 1
Unknown.Ct(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.At(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.Ht(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.Kt(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.nBc(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.zD(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.zEh(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.yEh(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.qpf(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.aff(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.Oef(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.Qef(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.w_d(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.fjc(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.sQ(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.GQ(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.qC(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.tC(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)

The exception comes up when the folder/file-selection dialog opens. Afterwards a folder selection is possible.

In another case I use configuration="selectabletypes=folder". When initially no folder is selected the folder/file-selection dialog opens without an error and a folder selection is possible. But when reopening the dialog again directly afterwards (folder was selected before) the following exception occurs:

(TypeError) : Cannot read property 'k' of undefined

Ticket Id: 1493101938072
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'k' of undefined
Unknown.yvf(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.spf(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.aff(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.qef(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.sef(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.w_d(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.fjc(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.sQ(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.GQ(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)
Unknown.(http://localhost:8080/opencms/handleStatic/gwt/opencms/47422F2B5D61BC1779A4ADD64F9DA47E.cache.html)

I flushed all caches. I stopped the server, deleted directories /webapps/ROOT/export + webapps/ROOT/WEB-INF/jsp and restarted. I re-initialized the workplace. All didn't help. Not being a javascript-expert it was kind of difficult to find the error in 12'+ obfuscated LOC of the 47422F2B5D61BC1779A4ADD64F9DA47E.cache.html by myself :-) 

I have the problem in openCMS 10.0.0 (stacktraces are from that version) and 10.5.1 (there it was /handleStatic/v1448580201v/gwt/opencms/9434BADD0B5548B9A7A525340B9E69F2.cache.html) using chrome and safari (didn't test other browsers).. 

Any ideas/suggestions?

**Comment by patric-dosch-vi** [comment]
hey @Belarophon, I have a similar issue and I guess it is a bug.
And I use the new (9.5.1) galleryselect option to solve my issue. But for me it is perfect, because I wanna select only galleryies. I'm not sure if this fulfills your requirement.

http://documentation.opencms.org/opencms-documentation/content-in-opencms/defining-a-content-type/defining-the-contents-behavior/adjusting-the-contents-appearance-in-the-content-editor/widget-configuration/#2.17

Regards, Patric

**Comment by tHerrmann** [comment]
The fix to this issue has been released with version [10.5.2](https://github.com/alkacon/opencms-core/releases/tag/build_10_5_2).
