### ISSUE TITLE
Can't find class:elemental.events.KeyboardEvent.KeyCode

### ISSUE THREAD

**Issue by wtslh** [alkacon/opencms-core#502]
I've downloaded the newest source code from here,after I imported all the source code to an eclipse project,I got an error:
![image](https://user-images.githubusercontent.com/2245560/26861396-12250d2a-4b76-11e7-99f1-d3915094461a.png)

**Comment by gallardo** [comment]
Your IDE is missing the dependency `com.google.gwt:gwt-elemental:2.7.0 (gwt-elemental-2.7.0.jar)`. The dependency is already listed in the `dependencies.gradle`.

**Comment by tHerrmann** [comment]
This is true, the dependency is listed in dependencies.gradle.
