### ISSUE TITLE
${cms.enableReload} seems not to work in OpenCms 10.5.1

### ISSUE THREAD

**Issue by patric-dosch-vi** [alkacon/opencms-core#504]
hey, I try to use ${cms.enableReload} to force reloading of page after editing.

I place it somewhere in the formatter as described in the [docu](http://documentation.opencms.org/opencms-documentation/typical-tasks/writing-jsps/interesting-el-expressions/#sec_standardcontextbean_useful_properties_formatting), I clean our formatter with all of our stuff and i try it like
`<c:when test="${cms.edited}">
      ${cms.enableReload}
<div class="alert alert-info">[...]</div>
    </c:when>`

but nothing happend. 
In an OC10.0.1 project it works fine and reload the page. Bug?

Regards, Patric

**Comment by tHerrmann** [comment]
Hi Patric,
this works for me. 
Is the reload marker the only content generated by your formatter JSP? Than you need to surround it with any kind of HTML tag like <div>${cms.enableReload}</div>. Otherwise the content is not injected into the page HTML and the marker never evaluated.

Regards, Tobias

**Comment by patric-dosch-vi** [comment]
Hey Tobias, 

in the first version I add the marker inside a section-tag. 
If I understand it correctly, I can always insert the marker into the page, right? So without the <c:if test="${cms.edited}">.

But in the second attempt I missed the surrounding tag, thats right. I test this version again.

**Comment by tHerrmann** [comment]
I assume this works for you?!
