### ISSUE TITLE
opencmsDateTime

### ISSUE THREAD

**Issue by g4495792** [alkacon/opencms-core#505]
![image](https://user-images.githubusercontent.com/26370760/26956885-b1c75990-4cf3-11e7-9feb-a740ec91d44a.png)

can not click

**Comment by tHerrmann** [comment]
I can not reproduce this issue, please state which browser and OS version you are using. Can you confirm, if this issue is also present, when using the English locale?

**Comment by gWestenberger** [comment]
Fixed in branch_10_5_x.
