### ISSUE TITLE
Error inserting images from the editor in OpenCMS 9.5.3

### ISSUE THREAD

**Issue by josealbertopf** [alkacon/opencms-core#508]
Hi,

We have detected a bug in the Tinymce editor that is installed in the version of OpenCMS 9.5.3. This error occurs when we insert images into the OpenCMS editor using the image gallery.

The problem is reproduced as follows: we edit a xml page and inside the editor we open a gallery of images. When we select any image the error that follows is produced and does not load the image.

`
(IndexSizeError) stack: Error: Failed to execute 'setBaseAndExtent' on 'Selection': There is no child at offset 1. at c.setRng (http://patacas.usc.es/resources/editors/tinymce/jscripts/tinymce/tinymce.min.js:6:16402) at c.select (http://patacas.usc.es/resources/editors/tinymce/jscripts/tinymce/tinymce.min.js:6:14181) at _selectionSelectNode (http://patacas.usc.es/system/workplace/editors/tinymce/integrator.js?integratorArgs=mode:imagegallery:119:21) at setImage (http://patacas.usc.es/system/workplace/editors/tinymce/integrator.js?integratorArgs=mode:imagegallery:399:9) at mvc (http://patacas.usc.es/resources/ade/galleries/39311FC30FCA6527938EDDBD517846C9.cache.html:6185:133) at yuc.Fuc [as Yh] (http://patacas.usc.es/resources/ade/galleries/39311FC30FCA6527938EDDBD517846C9.cache.html:7244:27912) at Rnc (http://patacas.usc.es/resources/ade/galleries/39311FC30FCA6527938EDDBD517846C9.cache.html:6127:97) at mmc (http://patacas.usc.es/resources/ade/galleries/39311FC30FCA6527938EDDBD517846C9.cache.html:3143:25) at sHc.tHc [as Id] (http://patacas.usc.es/resources/ade/galleries/39311FC30FCA6527938EDDBD517846C9.cache.html:7247:14408) at HM.IM [as Cd] (http://patacas.usc.es/resources/ade/galleries/39311FC30FCA6527938EDDBD517846C9.cache.html:7235:20771) __gwt$exception: INDEX_SIZE_ERR: 1 DOMSTRING_SIZE_ERR: 2 HIERARCHY_REQUEST_ERR: 3 WRONG_DOCUMENT_ERR: 4 INVALID_CHARACTER_ERR: 5 NO_DATA_ALLOWED_ERR: 6 NO_MODIFICATION_ALLOWED_ERR: 7 NOT_FOUND_ERR: 8 NOT_SUPPORTED_ERR: 9 INUSE_ATTRIBUTE_ERR: 10 INVALID_STATE_ERR: 11 SYNTAX_ERR: 12 INVALID_MODIFICATION_ERR: 13 NAMESPACE_ERR: 14 INVALID_ACCESS_ERR: 15 VALIDATION_ERR: 16 TYPE_MISMATCH_ERR: 17 SECURITY_ERR: 18 NETWORK_ERR: 19 ABORT_ERR: 20 URL_MISMATCH_ERR: 21 QUOTA_EXCEEDED_ERR: 22 TIMEOUT_ERR: 23 INVALID_NODE_TYPE_ERR: 24 DATA_CLONE_ERR: 25 code: 1: Failed to execute 'setBaseAndExtent' on 'Selection': There is no child at offset 1.`

This error occurs with both Google Chrome (59.0.3071.104 (Official build) (32 bits)) and Mozilla Firefox (54.0 (32-bit)). This is a fairly important error, since web users can not insert images if they do not
know how to insert them directly with the source code.

This bug can be reproduced in a clean OpenCMS installation.

Regards!

**Comment by tHerrmann** [comment]
This has been fixed with the update of the tinyMCE component in the branches branch_10_0_x and branch_10_5_x. The fix will be part of the next version of OpenCms 10.5.2 to be released within a month.

**Comment by josealbertopf** [comment]
Is it possible to update the module for version 9.5.3? Making the change to version 10.5.2 is not something simple, nor a decision that can be taken fast.

We understand that when it comes to an essential bug (we are talking about inserting images) should be able to fix in the same version. Can it be done?

**Comment by rpet** [comment]
I agree with the previous comment. OpenCMS 10 (first stable version released on March 23, 2016) is barely one year old and for large sites it's not feasible to do a major upgrade in that timeframe only to fix a bug in the Tinymce editor.

**Comment by tHerrmann** [comment]
As the fix can not be cherry picked into branch_9_5_x due to changes in the module structure, we will not provide this for free. Alkacon Software offers professional support including patches. These support contracts enable use to keep up developing OpenCms.

**Comment by rpet** [comment]
@tHerrmann Thank you for your answer.

Maybe this is not the best place to discuss it, but let me say that our University has been supporting OpenCMS for several years by contracting the OCEE subscription and the premium support. Nowadays we still pay for the OCEE subscription but we decided to drop the premium support some years ago because we feel that it did not provide enough value taking into account the costs.

Being said that, I'll contact your sales department to explore the available options to solve other issues we have with OpenCMS, specially de lack of support for SQL Server in the update wizard.

Regarding this particular case we already have fixed it on our own, but I still think that the TinyMCE editor should be more supportable out of the box. OpenCMS 9.5 seems to have got stuck in the 4.3.2 version whereas the latest in the 4.3 branch is 4.3.13.

**Comment by tHerrmann** [comment]
This has been fixed in branch_9_5_x with commit 8bdb1174e525fd22ee5793af1e750ae86562dc27.
