### ISSUE TITLE
Relative URL converted to absolute URLs 10.5.X

### ISSUE THREAD

**Issue by jolivap** [alkacon/opencms-core#509]
Hi,
We are currently working on version 10.5.1 and with the editor we see that although we select images or internal links relatively, saving it is saved with an absolute url.
We have seen, browsing the internet, that in theory can be changed by reconfiguring some properties <userelativelinks>, relative_urls: false, convert_urls: false, remove_script_host: false, etc ...
We have tried everything and nothing works. Is there a base configuration that if it works?
Thanks in advance,

**Comment by tHerrmann** [comment]
This is not supported. OpenCms will always try resolve the link to the resource to set a relation and generate absolute links.
