### ISSUE TITLE
we extracted the opencms 10.5.1 but config folder is not there

### ISSUE THREAD

**Issue by Florencia007** [alkacon/opencms-core#511]
Hi, we are following the instructions to upgrade OpenCMS from 9 to 10.5.1. We have a jetlastic environment with Tomcat. 

In point 1. if we stop the envirnment we can not extract the zip. if we leave it running we extrat the zip but we see that the zip doesn't have the Config folder for example. 

Or we have the wrong zip that we downloaded from the opencms website or the istructions are for another zip file.

Its very confusing. Can anyone help me?

**Comment by tHerrmann** [comment]
Hi,
I am not familiar with the jetlastic environment. I think it would be a good idea, to set up a test server for your OpenCms running in a classic environment and do the update there first. So you can see, how everything works. And afterwards do the same in your jetlastic cloud.
By the way, this is not a support forum. Please contact the [mailing ](http://www.opencms.org/en/development/mailinglist.html) for further support.
