### ISSUE TITLE
CmsSolrIndex'er magical numbers

### ISSUE THREAD

**Issue by asgerjensen** [alkacon/opencms-core#514]
Hi,

The CmsSolrIndex class currently does some magic to ensure a search result gets enough hits, by basically ignoring the input start and rows, and getting all entries from 0 to input.rows*5, and then filter the result using the security handler, to ensure there are enough results.

This makes the total count unreliable, and whats worse, in large installations, if you have users that can see only 1/10th of the documents, they will get no / varying results, plus each request takes way longer to process, if the user is navigating a deep page, since it has to process all documents from 0 => start+rows.

Wouldnt it be possible to serialize the ACL for each document into something that can be matched in a query instead? Like 
  acl_org_role: ou=foo_role=WORKPLACE_MANAGER 

Then the CmsSolrIndex searcher could serialize the users current roles, and match against those.

Failing that, could the magic number at least be a setting that could be configured?

**Comment by dSeidel** [comment]
Hi @asgerjensen,

currently, there's no change planned here. We thought about putting permission information in the index, but when you update the permissions on a folder, the permissions on each document below might change. I.e., in the worst case, the index would have to be rebuild completely. This might take very long and not be expectable for customers.
