### ISSUE TITLE
User permission bug with multi sites

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#515]
When syncing an LDAP user for site "exhibition", its start site is "/sites/group/" (that's the default-uri configured in opencms-system.xml):
![user_1_settings](https://user-images.githubusercontent.com/2276952/28165433-ab62aa44-67cb-11e7-8660-eea5cc8f09d4.png)

He has edit permissions for his site only:
![user_2_groups_roles](https://user-images.githubusercontent.com/2276952/28165454-be1a0358-67cb-11e7-8e4c-a22397547c38.png)

After logging-in her starts with /sites/group/:
![site_group_1_logged_in_user](https://user-images.githubusercontent.com/2276952/28165551-21ffcf88-67cc-11e7-9def-87f1a65bc3ea.png)

Now he is able to upload files to /sites/group/ although he only has +r+v permissions:
![site_group_2_uploaded_dummy](https://user-images.githubusercontent.com/2276952/28165563-315a5b38-67cc-11e7-838c-04bf91c77ebe.png)

That's quite critical, as her can overwrite existing files as well.

Further actions are not possible. So he can't delete, edit or publish the just uploaded file

**Comment by tHerrmann** [comment]
Without write permissions on the folder, it is not possible to upload to it. Check if the user really has the permissions you stated. Take also inherited group permissions into account.
Still the upload action should not be available to your user, as this site is not part of his OU. OU related permissions are checked on a different level than principal related permissions. This needs improvement.

**Comment by kartobi** [comment]
> Without write permissions on the folder, it is not possible to upload to it.
But if there are inherited write permissions, why is the user not able to edit or delete the upload lateron?

**Comment by tHerrmann** [comment]
This is where the OU related permissions prevent the UI to offer these actions. Using the Java API it would still be possible.
