### ISSUE TITLE
Opencms blocked importing module

### ISSUE THREAD

**Issue by javis2g** [alkacon/opencms-core#518]
When I import a module it gets stuck in the link stop step.
The page always stops refreshing at this point.
Import all files but in the process of parsing links OpenCMS stops responding.

Please, can you help me?

Here is an example of the last line written by opencms:
118/120) Parsing links to "/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.jsp" ..

Thank you
regards

**Comment by tHerrmann** [comment]
Please provide some more information. Which OpenCms version are you using? Does this happen with any kind of module or just a specific one? Are there any related errors in the OpenCms log file?

**Comment by tHerrmann** [comment]
We are closing this issue as no further information is provided.
