### ISSUE TITLE
Direct Edit: wrong redirect on Delete action

### ISSUE THREAD

**Issue by AngrySpace79** [alkacon/opencms-core#52]
Hello,

sometimes when I use delete content using Direct Edit I get an empty page.
I'm using opencms 7.5.3 but if I use the same installation on another pc it works right.

How can I fix it? Is there a way to know what file has been corrupted?

Thanks in advance.

**Comment by aKandzior** [comment]
Unable to reproduce this issue. This is probably a support case. Closing this ticket.
