### ISSUE TITLE
[build] AnnotationProcessor warning during compilation

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#522]
For the records. Please close after upgrade openjpa to `openjpa-3.0.0+`.

`org.apache.openjpa:openjpa-2.4.0` is using unfortunate annotations (See https://issues.apache.org/jira/browse/OPENJPA-2300). The issue applies also for openjpa-2.4.2. It has been solved already upstream in version 3.0.0-SNAPSHOT (tested 2017-06-19).

Compile logs:
```
gradle compileJava
Using internal version properties file
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
warning: Supported source version 'RELEASE_6' from annotation processor 'org.apache.openjpa.persistence.meta.AnnotationProcessor6' less than -source '1.7'
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning

BUILD SUCCESSFUL

```

**Comment by tHerrmann** [comment]
JPA has been removed in branch_11_0_x. We will not update the JPA dependency for any older branches.
