### ISSUE TITLE
<cms:link> to folder and static-export

### ISSUE THREAD

**Issue by abarrigas** [alkacon/opencms-core#523]
Hi everyone.

I've experienced a strange behaviour using opencms 10.5.1 and static export, related with <cms:link>

If I use

`<cms:link>%(link.weak:/system/modules/mymodule/resources/js/app.js:3cda0b8b-5fed-11e7-b478-0050568f726b)</cms:link>`

it turns into  

> ../../system/modules/mymodule/resources/js/app.js

which is OK, but using

`<cms:link>%(link.weak:/system/modules/mymodule/resources/js/</cms:link>` 

it turns into

> ../../../opencms/system/modules/mymodule/resources/js/

which is not OK, because I don't use opencms folder on static export.

I've solved it using JavaScript this way:

```
Resources = "<cms:link>%(link.weak:/system/modules/mymodule/resources/js/app.js:3cda0b8b-5fed-11e7-b478-0050568f726b)</cms:link>";
Resources = Resources.slice(0, -6);
```

I hope you can figure out why this is happening

Thank you.

**Comment by dSeidel** [comment]
Hi, the behavior is correct. If you link from an exported file to a non-exported resource that is in the same site, resources are linked to relatively.
