### ISSUE TITLE
Apollo modules a-blog can not create chinese-simplified,only  punctuation.

### ISSUE THREAD

**Issue by g4495792** [alkacon/opencms-core#525]
a-blog can not create chinese-simplified,only  punctuation.
![11111111111111](https://user-images.githubusercontent.com/26370760/30010348-a2955564-9161-11e7-9eeb-fea687b34195.jpg)
![0000000](https://user-images.githubusercontent.com/26370760/30010349-a33d505c-9161-11e7-8cf0-ce727c738788.jpg)

**Comment by g4495792** [comment]
Apollo modules a-blog can not create chinese-simplified pdf file，only punctuations,number and english word.

**Comment by gWestenberger** [comment]
If you need to generate PDFs with Chinese characters, you will have to embed (and use) an appropriate font in the PDF formatter JSP. We use flying-saucer for PDF generation, so you need something like the following in that JSP:

<style type="text/css">
@font-face {
    font-family: myfont;
    src: url(/system/mymodule/droidsansfallback.ttf);
    -fs-pdf-font-embed: embed;
    -fs-pdf-font-encoding: Identity-H;
}

body, body * { 
	font-family: myfont !important;

}
</style>
