### ISSUE TITLE
Users are not deactivated/activated through user synchronisation

### ISSUE THREAD

**Issue by jeromediaz** [alkacon/opencms-core#532]
OpenCMS 9.5.2
When we have a non activated user created on a front server, he is correctly pulled back by user synchronisation through OCEE.
But afterwards the user is activated on the front server but remains deactivated on the back server.

**Comment by tHerrmann** [comment]
Hi,
this seems to be an issue with the OCEE LDAP connector and not the OpenCms core. Please contact Alkacon support regarding the this problem.

Regards, Tobias
