### ISSUE TITLE
Users can still published when direct publish right is not enabled

### ISSUE THREAD

**Issue by jeromediaz** [alkacon/opencms-core#533]
We have two users only belonging to a group with direct publish right not enabled on a folder (and sub elements) but they are still able to publish content inside this folder.

Any idea?

**Comment by tHerrmann** [comment]
Hi,
this may be working as intended. 
Check your offline project to see, which group is set as project manager group. In case these users are member of this group, this will allow them to publish, even though direct publishing is not granted.
To change that, assign a different group as project managers.
Regards, Tobias

**Comment by AntoinePineau** [comment]
Thank you for your answer Tobias, but how can we proceed to authorize some users and not all the users of a group to be able to publish ?

**Comment by tHerrmann** [comment]
You can either create a group for that purpose and set this group as project managers of the involved project. Or you make sure, none of the users are member of the project managers group and assign direct publish rights individually.
