### ISSUE TITLE
Custom gallery title macro is not resolved and %(...) is attached literally

### ISSUE THREAD

**Issue by jgregorio0** [alkacon/opencms-core#534]
Good morning! I'm facing what seems to be a bug when I try to enter gallery title using macro for text resource type. It happens for OpenCms 9.5.3

1. When gallery title field is empty, default macro is resolved correctly:

Editing:
![1 editing gallery title default](https://user-images.githubusercontent.com/5246991/30852371-da5d18e6-a2ab-11e7-9a61-66a6ee26ecfc.PNG)

Explorer:
![2 explorer gallery title default](https://user-images.githubusercontent.com/5246991/30852383-e51d9e2c-a2ab-11e7-9349-5c59d168405d.PNG)

2. However, if I set gallery title field using any macro it is resolved for title property only:

Editing:
![3 editing custom gallery title](https://user-images.githubusercontent.com/5246991/30852411-fa9c424e-a2ab-11e7-8e97-c073a15eed4b.PNG)

Explorer:
![4 explorer custom gallery title](https://user-images.githubusercontent.com/5246991/30852417-fc7f642e-a2ab-11e7-946f-02e42032f86b.PNG)

ADE:
![5 ade custom gallery title](https://user-images.githubusercontent.com/5246991/30852419-fdbda3b4-a2ab-11e7-975e-3976568524a8.PNG)

Any clue about what's going on?

**Comment by dSeidel** [comment]
Works at least in current OpenCms versions correct, so I close the issue.
