### ISSUE TITLE
Toolbar is hidden when page is scrolled down in Chrome

### ISSUE THREAD

**Issue by herbae** [alkacon/opencms-core#535]
Using Chrome 61.0.3163.100 64 bits, the dialog window doesn't show up when the page is scrolled down, as you can see in the pictures below.

![image](https://user-images.githubusercontent.com/6299880/31030311-429ed5c6-a52b-11e7-9eb2-d9d8cf9d3d95.png)
When page is scrolled to the top, dialog shows up ok.

![not ok 1](https://user-images.githubusercontent.com/6299880/31030346-5e02dde4-a52b-11e7-9f8c-4cf78e874758.PNG)
As you scroll down, dialog shows up partially.

![not ok 2](https://user-images.githubusercontent.com/6299880/31030360-6e09bea6-a52b-11e7-861d-64d4b083a961.PNG)
And, finally, no dialog at all.

I could not replicate this on IE or Firefox.

The workaround for this is to scroll the page to the up, open up the dialog and then scroll down back again.

**Comment by tHerrmann** [comment]
This has been fixed by commit 5647e6f9740967b3d130638d874dba02d856d042. We are planning a release early this month containing the fix.

**Comment by patric-dosch-vi** [comment]
hello @tHerrmann, many thanks to provide that fix. Can we build OpenCms 10.5.1 (based on tag https://github.com/alkacon/opencms-core/tree/build_10_5_2) with the added classes? What do we have to update (jars? modules?) to rollout the fix?

Regards, Patric

**Comment by tHerrmann** [comment]
Hi @patric-dosch-vi,
you can patch any OpenCms version 10.x by adding those classes and rebuilding the Jars opencms-widgetset.jar and org.opencms.gwt.jar. Use the gradle tasks 'widgetSetJar' and 'jar_org.opencms.gwt'.
Regards, Tobias

**Comment by aKandzior** [comment]
Our analysis of the problem has shown that the positioning issue is actually a bug in the GWT library.

The GWT bug is documented here: https://github.com/gwtproject/gwt/issues/9542

**Comment by aKandzior** [comment]
This is fixed with 10.5.3. 

We also will provide patches for 10.0.1 and 9.5.3, but not issue a new version.

**Comment by tHerrmann** [comment]
For anybody who is not able to update to the latest OpenCms version we provide patches for the following versions:
[9.5.1](http://www.opencms.org/downloads/opencms/OpenCms_9.5.1_chrome_ui_patch.zip)
[9.5.3](http://www.opencms.org/downloads/opencms/OpenCms_9.5.3_chrome_ui_patch.zip)
[10.0.1](http://www.opencms.org/downloads/opencms/OpenCms_10.0.1_chrome_ui_patch.zip)
[10.5.2](http://www.opencms.org/downloads/opencms/OpenCms_10.5.2_chrome_ui_patch.zip)
