### ISSUE TITLE
Formatter's CSS Link not included when element dropped for the first time

### ISSUE THREAD

**Issue by abed-nego999** [alkacon/opencms-core#537]
When dropping an element for the first time in my page, it doesn't import the CSS Link into my "head includes", so I have to refresh the page. But before refreshing, I have to edit it (without the styles) because of the #536 Issue

**Comment by tHerrmann** [comment]
Which OpenCms version are you using?

**Comment by abed-nego999** [comment]
OpenCms 10.5.3. 
The class CmsContainerpageService doesn't bring any information about the CSS Link of the formatter, so I can't do any JS workaround to fix the problem
