### ISSUE TITLE
Can not edit links

### ISSUE THREAD

**Issue by abed-nego999** [alkacon/opencms-core#538]
Even in the Demo Site, when trying to "Direct Edit" a link's caption it redirects you to the link's href

**Comment by tHerrmann** [comment]
Please state which browser version you are using and where in the demo you are not able to edit link captions.
It works for me on the demo overview page.

**Comment by abed-nego999** [comment]
I tried with Firefox and IE11. In the "apollo-demo/home" page, for example. When you hover the mouse over the first link that says "More information", it appears the editing pointer but, when clicking, it redirects you to the OpenCms tutorial.

**Comment by tHerrmann** [comment]
To enable editing of link captions, you need to insert an additional element like this:
<a href=""><span rdfa>link caption</span></a>
in case of 
<a href="" rdfa>link caption</a> the link will be followed.
This is intended behavior. It should make sure, you can actually follow links within direct edit enabled elements.
