### ISSUE TITLE
tomcat server shutdown while running setup wizard

### ISSUE THREAD

**Issue by rekhaJain** [alkacon/opencms-core#542]

**Comment by tHerrmann** [comment]
Please provide the catalina logs and the opencms log files to see what went wrong.

**Comment by rekhaJain** [comment]
Hi, Problem is resolved know. I believed issue was coming because of not able to passing xml file while running setup. it is resolved with used jdk 8 + tomcat 8 + my sql 5.0 + open cms 10.x version. Thanks for looking into this.
