### ISSUE TITLE
Looking for beginner guide for open cms 10.x .

### ISSUE THREAD

**Issue by rekhaJain** [alkacon/opencms-core#544]
i am new to start work on open cms 10.x. Please provide me example or pdf book which help me to start create web site with adding new pages and modified it.

**Comment by tHerrmann** [comment]
There is a small tutorial available as a part of the demo contents. Also available is our online documentation at [OpenCms Documentation](http://documentation.opencms.org/central/).

**Comment by pimonty** [comment]
![captura de pantalla de 2017-12-28 19-51-45](https://user-images.githubusercontent.com/29837564/34421708-c49931ce-ec08-11e7-8203-cc354bedf54d.png)

**Comment by ManfredSchenk** [comment]
documentation.opencms.org works here (Provider Deutsche Telekom, Dualstack IPv4/IPv6)

**Comment by pimonty** [comment]
Thank you so much
