### ISSUE TITLE
Validation rules not working

### ISSUE THREAD

**Issue by flaviaveloso** [alkacon/opencms-core#546]
Hello, everyone! 

I'm having a problem with the validation rules of my nested xsd.
I set the validation rules on the nested schema:

![schemanested](https://user-images.githubusercontent.com/11728956/32086758-190684a2-bab6-11e7-8df9-4a25bee5954e.PNG)

But when I access it from the content editor and put the wrong data, the error message don't appear:

![semerro](https://user-images.githubusercontent.com/11728956/32086767-32366334-bab6-11e7-826f-bd3b5e07ba25.PNG)

The rules has been respected. If I put some wrong information, the content editor don't let me save the content, but the error message don't show too. 

Can you help me? Am I loosing something? 

Thanks!

**Comment by patric-dosch-vi** [comment]
hey @flaviaveloso, have you tried to use the type="error" - normally I do not have this type-property in my XSDs.

Our rule for a similar case:
<rule element="Anchor" regex="[a-zA-Z0-9]+" message="${key.editor.errormessage.field.anchor.invalid}"/>

Regards, Patric

**Comment by flaviaveloso** [comment]
Hi @patric-dosch-vi! 

I changed the type, but the problem continues :'(

The rule for a similar case did not appear to me...

**Comment by dSeidel** [comment]
I checked in current OpenCms versions and it did work (latest 10.5.x and upcoming 12). If your version is older, it might have been the case, that the configuration did only work if done in the root content. This was the case for multiple settings in older versions. We made more things possible to be used in nested contents as well in more recent versions.
