### ISSUE TITLE
Calendar widget disable

### ISSUE THREAD

**Issue by flaviaveloso** [alkacon/opencms-core#551]
Hello!

Is there someway to disable this calendar widget?

![image](https://user-images.githubusercontent.com/11728956/33332513-9922fc3e-d44b-11e7-88af-3fbd6b416217.png)

I just want to type the date. 
And all dates will have the same hour, so I don't need to show the hour too...

Can you help me, please?

Thanks!

**Comment by davidrod** [comment]
Hi!

It’s easy. Edit the schema of the type and remove the layout of the field Data. Then you have only an String type. You can use a regular expression to validate the field.



David Rodríguez Merino
Área Web del Gabinete de Comunicación
Secretaría General
Universidad de Valladolid

Edificio Rector Tejerina
Plaza de Santa Cruz nº 6
47002 Valladolid

Email: david.rodriguez.merino@uva.es
Email grupo: soporte-web@uva.es
Tlfno: 983 18 4913
Tlfno grupo: 983 18 4771
Web: http://www.uva.es
Web grupo: http://webmaster.blogs.uva.es




Imprima este e-mail y sus archivos adjuntos si realmente es necesario. Gracias por ser respetuosos con el medio ambiente

AVISO SOBRE CONFIDENCIALIDAD. La legislación española ampara el secreto de las comunicaciones. Este correo electrónico y sus anexos son estrictamente confidenciales. Si Vd. no es el destinatario del mismo, por favor, notifíquenoslo inmediatamente y destruya el original. No deberá copiar este mensaje ni sus anexos o usarlo para propósito alguno, ni divulgar su contenido a ninguna persona.

WARNING ABOUT CONFIDENCIALITY. Spanish law guarantees privacy in electronic communications.This message and its attachments are confidential. If you are not the intended recipient please, notify us inmediately and destroy or the original to us. You should not copy this message or use it for any purpose, nor disclose its content to any other person.

**Comment by flaviaveloso** [comment]
Hi @davidrod ! Thanks for the answer!!

But I need to use the type OpenCmsDateTime, because I am mapping this field on solr (*_dt).
