### ISSUE TITLE
Tag <cms:ugc> does not generate an ugc-id

### ISSUE THREAD

**Issue by joseseixas** [alkacon/opencms-core#554]
Hi,
I created an ugc to my own resource-type and tried to follow the "apollo-blog-new-article" example as much as I could. However, the ugc-Id generated by the tag <cms:ugc> comes always blank. Therefore, the javascript "ujc-query.js" fails at loading and returns an error in the browser console. ("java.lang.IllegalArgumentException: Invalid UUID syntax!"). Any attempt of uploading my form results on another error, since the UGC properties : session ,content and contentClone are not initialized.

Does anybody have a clue why the ugc-id is not being generated?
By the way , I am on 10.5.3 version

**Comment by bzebedin** [comment]
Hi.
I have a lot of UGC in my projects running 10.5.3 without any problem. So I think this is not an issue of opencms. I think a good place to discuss this problem is the mailing list. (opencms-dev@opencms.org)

Kind regards
Bernhard

**Comment by arf3** [comment]
> Hi,
> I created an ugc to my own resource-type and tried to follow the "apollo-blog-new-article" example as much as I could. However, the ugc-Id generated by the tag cms:ugc comes always blank. Therefore, the javascript "ujc-query.js" fails at loading and returns an error in the browser console. ("java.lang.IllegalArgumentException: Invalid UUID syntax!"). Any attempt of uploading my form results on another error, since the UGC properties : session ,content and contentClone are not initialized.
> 
> Does anybody have a clue why the ugc-id is not being generated?
> By the way , I am on 10.5.3 version

I had the same problem and found the solution.
It lies in the "Name Pattern" field inside the ugc formatter configuration. It needs to have a Macro to create number. So in that, add
nameformat_%(number)
and then it will start generating UUID
it does not throw any opencms logs rather a java error message
