### ISSUE TITLE
Update dependency to flying-saucer-pdf-openpdf version 9.1.11

### ISSUE THREAD

**Issue by andreasrosdal** [alkacon/opencms-core#558]
I recommend that you replace the dependency from flying-saucer-pdf (iText 2.x) to flying-saucer-pdf-openpdf 9.1.11.

This would use the Flying Saucer library with OpenPDF:
https://github.com/librepdf/openpdf

iText 2.x has unfixed security bugs, so it is best to replace it with OpenPDF.
http://seclists.org/bugtraq/2017/Nov/20 
https://github.com/LibrePDF/OpenPDF/pull/56

See some more information here also:
https://github.com/flyingsaucerproject/flyingsaucer
https://mvnrepository.com/artifact/org.xhtmlrenderer/flying-saucer-pdf-openpdf

(This is configured in dependencies.gradle - https://github.com/alkacon/opencms-core/blob/branch_10_5_x/dependencies.gradle#L166)

**Comment by andreasrosdal** [comment]
See: https://github.com/alkacon/opencms-core/pull/566

**Comment by tHerrmann** [comment]
The flying saucer dependency has been updated in branch_10_5_x.

**Comment by tHerrmann** [comment]
This has been fixed with release 10.5.4.
