### ISSUE TITLE
Importing module: Insufficient diagnostics for dup entries in manifest

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#568]
During module import, opencms logs a failure message for duplicated manifest entries with no diagnostics / hints at all. E.g.:

    ( 44 / 214 ) Publishing file /system/modules/d.s.u/resources/formtemplates/default.st ... !!! failed

If server logs are activated, it also logs something like:

    24 Jan 2018 10:44:06,035 ERROR [ms.db.generic.CmsProjectDriver:1312] ( 44 / 214 ) Publishing file "[org.opencms.file.CmsResource, path: /system/modules/d.s.u/resources/formtemplates/default.st, structure id 6e7bbfef-00e3-11e8-9580-0242ac11002b, resource id: 03f5467d-0628-11e1-a876-6f6871313691, type id: 1, folder: false, flags: 0, project: 6ddd5d4b-00e3-11e8-9580-0242ac11002b, state: 99, date created: Mon Mar 07 16:08:31 CET 2011, user created: c300ba5c-01e8-3727-b305-5dcc9ccae1ee, date lastmodified: Thu Nov 03 15:43:27 CET 2011, user lastmodified: c300ba5c-01e8-3727-b305-5dcc9ccae1ee, date released: Thu Jan 01 01:00:00 CET 1970, date expired: Sun Aug 17 08:12:55 CET 292278994, date content: Wed Jan 24 09:49:04 CET 2018, size: 21227, sibling count: 2, version: 1]".

This is too cryptic and not helpful at all.

OpenCms should report something like

    Warning: Resource /system/modules/d.s.u/resources/formtemplates/default.st to publish is not new, nor has been modified or deleted. (Is it duplicated?)

**Comment by gallardo** [comment]
For the record, the most obvious place to report this is in https://github.com/alkacon/opencms-core/blob/build_10_5_3/src/org/opencms/db/generic/CmsProjectDriver.java#L1320. Unfortunately, `org.opencms.db.generic.CmsProjectDriver` and `org.opencms.db.jpa.CmsProjectDriver` (notice `generic` vs `jpa`) share a big chunk of code.

If fixed, both `publishFile` versions should be extended.

**Comment by aKandzior** [comment]
Thank you for taking the time to open a ticket. However, it's unlikely that we will implement this improvement in the foreseeable future, so I close this ticket now.
