### ISSUE TITLE
Initial OpenCms setup in non-tomcat fails

### ISSUE THREAD

**Issue by double-p** [alkacon/opencms-core#571]
Not much ado before this in OpenCmsServlet.java
```
                // if wizard is still enabled - allow retry of initialization (required for setup wizard)
                // this means the servlet init() call must be terminated by an exception
```
Are you serious? I am more or less shocked that tomcat (your "home ecosystem") allows this.
In almost any other container this is a fatal failure and OpenCms "setup" will never come to happen.
There is no "retry" by JEE spec or something else for Servlets.

"We just had a heart-attack, but that's ok, just carry on". 

Please rethink this.. e.g. write a flag into the database about "wizard was ran already" or thelike.

I am also inclined to open a bug with tomcat over this.

**Comment by ShalokShalom** [comment]
Subscribe

*Popcorn*

**Comment by double-p** [comment]
While the description is like to scare people away.. this one does the trick in opencms.properties:
servlet.exception.enabled=false
