### ISSUE TITLE
Don't allow creation of detail pages without associated page

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#575]
(Comes from #548)

In the same was that it is not possible to associate an invalid path to the "page" of a detail page, it shouldn't be possible to create a detail page with empty "page" field.

This is currently allowed (and it shouldn't):

![35680276-2e6d45ba-075a-11e8-97ea-62edf15b0fa9](https://user-images.githubusercontent.com/790448/35687340-c1126f6c-076e-11e8-8c9d-03b3a9bb0923.png)

**Comment by dSeidel** [comment]
I added validation rules for type and page in the current master - so your requested feature will be part of OpenCms 12.
