### ISSUE TITLE
Problem in tutorial during step 4: work-with-the-sitemap

### ISSUE THREAD

**Issue by YueHanNeiSi** [alkacon/opencms-core#581]
After having opened the Sitemap in step 4 of the tutorial via the 'Sitemap' icon in the right part of the toolbar the tutorial instructs to select 'Add pages'. Unfortunately the icon for 'Add pages' is not shown in the main toolbar. Only 'Publish' and 'Select view' icons are shown.

![image](https://user-images.githubusercontent.com/37030225/36940837-21f84734-1f4d-11e8-93a8-09bbaaf89b56.png)

The tutorial shows something different:

![image](https://user-images.githubusercontent.com/37030225/36940845-8cb735d0-1f4d-11e8-9ce3-cc78dacc9afc.png)

Windows 7 Professional 6.1.7601 Service Pack 1 Build 7601

Same behavior in:
- Google Chrome Version 64.0.3282.186 (64-Bit)
- Firefox Quantum 58.0.2 (64-bit)

**Comment by dSeidel** [comment]
Hi @YueHanNeiSi ,

it's actually not a problem of the tutorial, it's a problem of the OpenCms demo server. For a local installation of OpenCms (or the docker image) it should work.

**Comment by flaviaveloso** [comment]
Hello @dSeidel  and @YueHanNeiSi !!

I am having the same problem here and I am using a docker image with opencms 10.5.3
Someone can help me, please?

Thanks!

**Comment by flaviaveloso** [comment]
Hello @dSeidel and @YueHanNeiSi !!

I am having the same problem here and I am using a docker image with opencms 10.5.3
Could you help me, please?

Thanks!

**Comment by dSeidel** [comment]
Hi @flaviaveloso , is it an image you built yourself? The official images are available for 10.5.1 and then 10.5.4. We did not experience the behavior outside the demo server up to now.

**Comment by flaviaveloso** [comment]
@dSeidel 

I make a local installation of the OpenCms version 10.5.4 but the problem continues :(

The /sites/default/ doesn't had the .content folder, so I created one to access the sitemap and what I see is that:

![image](https://user-images.githubusercontent.com/11728956/41623307-b0ea661c-73e8-11e8-8b71-79872b0c87be.png)

I don't know if it's normal or I lost some configuration...

**Comment by dSeidel** [comment]
Hi @flaviaveloso,

did you install the demo modules? What does the structure in the Explorer look like in /sites/default/? The structure in the screenshot does not correspond to a default installation.
