### ISSUE TITLE
Preview of XmlContent inconsistent

### ISSUE THREAD

**Issue by asgerjensen** [alkacon/opencms-core#582]
Version: 10.5.2

There are three ways to preview an unpublished change from the Workspace app:
1. Click "Display" on the context menu
1. Click "History" and click the magnifying glass on previous version
1. Click "History" choose two versions, choose "Compare", click "Show version 'X'"

1) will find the  `template` or `template-elements` property, and spawn that with `request.uri` being the unpublished version (or published if there are no changes)
2) will call the `CmsVfsService#getHistoryPreviewInfo` and return a value that spawns the `template` with the URI, and a parameter called `__disableDirectEdit=true`, but no information about which version was clicked, so the `template` always shows the most recently published version
3) will call `/system/shared/showversion/<URL>` with a `version` parameter. This is then used to resolve a `CmsHistoryFile` by the `CmsHistoryResourceHandler`, but without loading its contents, meaning that when it later on tries to load the contents via `CmsXmlContentFactory`, it will hit these lines:
```
/* 288 */     CmsXmlContent content = (CmsXmlContent)req.getAttribute(rootPath);
/*     */     
/* 290 */     if (content == null)
/*     */     {
/* 292 */       CmsFile file = (resource instanceof CmsFile) ? (CmsFile)resource : cms.readFile(resource);
```
and since `CmsHistoryFile` is a subclass of `CmsFile`, it will not read the contents, meaning that
`unmarshall`, will get an empty byte array, leading it to simply try to return an empty object from this
```
/*     */     CmsXmlContent content;
/* 233 */     if (contentBytes.length > 0) {
/*     */       CmsXmlContent content;
/* 235 */       if (keepEncoding)
/*     */       {
/* 237 */         content = unmarshal(cms, contentBytes, encoding, new CmsXmlEntityResolver(cms));
/*     */       }
/*     */       else {
/*     */         try
/*     */         {
/* 242 */           String contentStr = new String(contentBytes, encoding);
/* 243 */           content = unmarshal(cms, contentStr, encoding, new CmsXmlEntityResolver(cms));
/*     */         }
/*     */         catch (UnsupportedEncodingException e) {
/* 246 */           throw new CmsXmlException(Messages.get().container("ERR_XMLCONTENT_INVALID_ENC_1", filename), e);
/*     */         }
/*     */       }
/*     */     }
/*     */     else
/*     */     {
/* 252 */       content = new CmsXmlContent(cms, DocumentHelper.createDocument(), encoding, new CmsXmlEntityResolver(cms));
/*     */     }
```
which, because  `DocumentHelper.createDocument()` does not create a root element, causes
```
/*      */   protected CmsXmlContentDefinition getContentDefinition(EntityResolver resolver)
/*      */     throws CmsRuntimeException
/*      */   {
/*  920 */     String schemaLocation = m_document.getRootElement().attributeValue(I_CmsXmlSchemaType.XSI_NAMESPACE_ATTRIBUTE_NO_SCHEMA_LOCATION);
/*      */     
/*      */ 
```
to give a NullPointerException on `m_document.getRootElement()`

I was able to work around 3) by adding a new PreloadHistoryHandler, that checked if the other HistoryHandler had set something up, then manually called `cms.readFile` on the stored `CmsHistoryFile`, unmarshalled it, and stored it in the request context under its `rootPath`.

However, I cannot seem to get scenario 2) to work in any way. It would be great if the default URL would include the version number or some such.

**Comment by gWestenberger** [comment]
This seems to be already fixed in the current master branch.
