### ISSUE TITLE
Full static export with single tree approach don't work

### ISSUE THREAD

**Issue by anabel40** [alkacon/opencms-core#584]
CmsAfterPublishMultilanguageStaticExportHandler don't work if you use single tree approach in OpenCms 10.5.3.

**Comment by AlfonsoBM** [comment]
Tried in 10.5.4 and doesn't work either, even following official documentation: https://documentation.opencms.org/opencms-documentation/tutorials/building-a-multilingual-website/#10

Same behaviour as described here: http://opencms.996256.n3.nabble.com/Full-static-export-multilanguage-site-td27122.html

**Comment by dSeidel** [comment]
Full static export is not the relevant feature as has been ages ago and this the focus is not on getting it fully compatible with new features. So we wont fix this at the moment.
