### ISSUE TITLE
Additional Request Parameter in search

### ISSUE THREAD

**Issue by joseseixas** [alkacon/opencms-core#590]
Hi,

I am working on 10.5.3 version and I think a found a bug in search, using a search configuration file.
I tried to use additional request parameters but it was not working. What happened follows: 

 1 - my querystring was ?lq=&reloaded=&q=open&teste=tralala&sort=score+desc (in my example I modified the apollo demo search )

 2 - the additional parameter, inside my xml (jsp-search-00001.xml), was configured as :
   &lt;AdditionalRequestParams&gt;
         &lt;Param&gt;&lt;![CDATA[teste]]&gt;&lt;/Param&gt;
         &lt; SolrQuery&gt;&lt;![CDATA[fq=type:(%value)]]&gt;&lt;/SolrQuery&gt;
       &lt; /AdditionalRequestParams&gt;

3 - during debugging, the content of field m_additionalparameter of the CmsSearchControllerCommon object was : 
                   key = "org.opencms.xml.types.CmsXmlStringValue: name=Param, type=OpenCmsString, path=AdditionalRequestParams[1]/Param[1], value='teste'"
		 value= "org.opencms.xml.types.CmsXmlStringValue: name=SolrQuery, type=OpenCmsString, path=AdditionalRequestParams[1]/SolrQuery[1], value='fq=type:(%value)'"
     
4 - I believe it should be instead
                  key = "teste"
                  value = "fq=type:(%value)"

5- During the CmsSearchControllerCommon.updateFromRequestParameters execution, no parameter is matched, since it compares "teste" with "org.opencms.xml.types.CmsXmlStringValue: name=Param, type=OpenCmsString, path=AdditionalRequestParams[1]/Param[1], value='teste'" 

6- The problem seems to be in CmsXMLSearchConfigurationParse.getAdditionalRequestParameters where it reads (wrongly I suppose) the xml content.

Please let me know if I misinterpreted the functionality.
Thanks

**Comment by dSeidel** [comment]
Hi @joseseixas you're right, there's a problem. I'll fix it in the next bug-fix release.

Best, Daniel.
