### ISSUE TITLE
'CmsSearchParameters.getIndex()' doesn't have a code to catch the 'NullPointException'.

### ISSUE THREAD

**Issue by ByungJun25** [alkacon/opencms-core#596]
Hello, 

https://github.com/alkacon/opencms-core/blob/c66bc3203f615f63e84692d90c3322e4a8308754/src/org/opencms/search/CmsSearchParameters.java#L470

Could you add the some logic to catch the NullpointException in "CmsSearchParameters.getIndex()" method? or add a default value?
I don't know exactly how it works but I got the NullpointException here.
When does it initialize 'm_index' variable? should I initialize manually?

Thank you.

**Comment by dSeidel** [comment]
Hi @ByungJun25,

use "setIndex(String indexName)" or "setSearchIndex(CmsSearchIndex index)" to set the index in the parameters. If using the name, it'll only set the index if it really exists.

**Comment by ByungJun25** [comment]
Hi @dSeidel,

Thank you for answer about my issue!

I checked the code again, and I found we already used the setIndex method of CmsSearch class. 

The problem is that we set different name value for index in 'opencms-search.xml' file. 
We fixed it, and it works. :)

Thank you.
