### ISSUE TITLE
org.opencms.search.solr.CmsSolrField cannot be cast to org.opencms.search.fields.CmsLuceneField

### ISSUE THREAD

**Issue by AlfonsoBM** [alkacon/opencms-core#597]
Steps to reproduce:

Previously installed or clean opencms 10.5.x or 9.5.x installation
Go to "Search Management" -> and bulb "Show field configuration".

`Exception throw: org.opencms.search.solr.CmsSolrField cannot be cast to org.opencms.search.fields.CmsLuceneField`

Workaround: Manually delete all search index and create them again.

Tested on Windows+Oracle and Suselinux+Mysql

Any solution? Thanks.

**Comment by gWestenberger** [comment]
Dialog no longer exists in master branch.
