### ISSUE TITLE
CMS_PUBLISH_HISTORY is never pruned

### ISSUE THREAD

**Issue by asgerjensen** [alkacon/opencms-core#598]
Version: OpenCMS 10.5.2

I notice that CMS_PUBLISH_HISTORY is never pruned when the parent table CMS_PUBLISH_JOB is pruned. Looking at the database drivers, i see there are calls defined to delete between two publish tags, or for a specific resource, but neither are ever invoked, and a code search here in github reveals no reference to these functions outside the driver layer..

As there are no foreign key relations defined between CMS_PUBLISH_JOB and CMS_PUBLISH_HISTORY the table will just keep growing indefinetly.

**Comment by gWestenberger** [comment]
Fixed in master branch.
