### ISSUE TITLE
Problems with labels in workplace_ru.properties

### ISSUE THREAD

**Issue by AngrySpace79** [alkacon/opencms-core#60]
Hi, I've a russian website, and I can view it correctly with UTF-8 encoding but I've problems with labels from workplace_ru.properties

I've found this code:
http://lists.opencms.org/pipermail/opencms-dev/2009q3/032999.html

but when I adapt it in my page, I get only "?????"

This is my code in jsp element page:

String jvmDefaultCharsetName = Charset.defaultCharset().displayName();
byte[] OldCharset = cms.label("label.contacts_subject").getBytes(jvmDefaultCharsetName);
byte[] NewCharset = CmsEncoder.changeEncoding(OldCharset, jvmDefaultCharsetName, "UTF-8");
String RussianLabel = CmsEncoder.createString(NewCharset, "UTF-8");

out.print(RussianLabel); // The output is "?????" 

I also tried to put this code at the top of the page:
String ReqUr = CmsRequestContext.setEncoding("UTF-8");

but labels are in italian (my default workplace.properties)

How can I solve this problem?

**Comment by aKandzior** [comment]
Properties files do not support international characters. This is a Java restriction. 

This is a support issue. Closing this ticket.
