### ISSUE TITLE
Account blocking broken

### ISSUE THREAD

**Issue by Marco-VI** [alkacon/opencms-core#604]
According to the default settings a user should be blocked after the third login attempt when providing a wrong password for 15 minutes. Unfortunately there was a change two years ago in org.opencms.ui.login.CmsLoginController line 452: https://github.com/alkacon/opencms-core/blob/731b3f5eb7375f9c236cfc00ff3edce2017218f4/src/org/opencms/ui/login/CmsLoginController.java#L452 which prevents this behaviour. Since this change readUser(realUser, password) will also check if the password is correct not only if the user exists. When the user provides an incorrect password an exception is thrown that the user wasn't found. Therefore the code responsible for the blocking feature is never processed and a brute force attack could be used to guess the credentials.

**Comment by gWestenberger** [comment]
Fixed in OpenCms 11 and later.
