### ISSUE TITLE
NullPointerException while loading handle500 from folder /.errorpages/

### ISSUE THREAD

**Issue by AnnJul** [alkacon/opencms-core#611]
## Affected Version
OpenCms 10.5

## Problem
NullPointerException while trying to load a site specific handle500.html.

## Steps to Reproduce
I have a site specific handle500.html in /sites/default/.errorpages/. In web.xml I changed the path of handle500 to /opencms-errorhandler/handle500. 
```
<error-page>
    <error-code>500</error-code>
    <location>/opencms-errorhandler/handle500</location>
 </error-page>
```
Then I click on an empty <cms:link> on my page to get an error 500. But the page is not shown up because of a NullPointerException in CmsJspTagEditable (https://github.com/alkacon/opencms-core/blob/branch_10_5_x/src/org/opencms/jsp/CmsJspTagEditable.java#L276).

## Reason
The CmsObject of the CmsFlexController is null because the error handling in OpenCmsCore.openErrorHandler(HttpServletRequest, HttpServletResponse, int) (https://github.com/alkacon/opencms-core/blob/branch_10_5_x/src/org/opencms/main/OpenCmsCore#L2167) removes all attributes from the CmsFlexController which is later called in CmsJspTagEditable.isEditableRequest(ServletRequest)

**Comment by gWestenberger** [comment]
Fixed in master branch.
