### ISSUE TITLE
I couldn't use 'passSettings' attribute in cms:display Tag.

### ISSUE THREAD

**Issue by ByungJun25** [alkacon/opencms-core#613]
Hello,

I would like to use 'passSettings' attribute in 'cms:display' Tag in order to pass the settings value to formatter.
But I couldn't use it, when I add the passSettings attribute like as below, I got the error message: 'Unable to find setter method for attribute: [passSettings]'

Here is the code what I write for using it.

`<cms:display value="${Element1.value.Contents}" displayFormatters="${Element1.value.TypesToCollect}" passSettings="true" editable="true" />`

'Element1.value.Contents' has a macro formatter and macro formatter has several sub xml files(as Formatter). Each sub xml file has a settings value. So I would like to use each settings of sub xml file when it will be rendered via 'cms:display' Tag.
![image](https://user-images.githubusercontent.com/10557621/47844107-d3677700-ddc1-11e8-9751-15cc59f2f333.png)
**<Element1.value.Contents's Element Settings>**

When I used the 'cms:param' tag instead of passSettings attribute inside 'cms:display' tag, it worked fine.

Please tell me what was wrong and what I should do.

Version and Build Information is like as below

Version: 10.5.3
Build Date: 2017-10-18 11:07
Git Branch: build_10_5_3
Git Commit ID: d5e099d
Build Number: #1377
Build System: Jenkins ci-release
Build Type: Release

Thank you.

**Comment by dSeidel** [comment]
Hi, sorry for the late answer. There was a bug in the tag class, not providing really not providing the (correctly typed) setter. I just fixed it and it will be part of the upcoming OpenCms 12 release.
