### ISSUE TITLE
static export of offline version is not possibe. 

### ISSUE THREAD

**Issue by ssklavos-ed** [alkacon/opencms-core#623]
The static export only works for online. Isnt that possible somehow to configure the site to get the offline version exported? I tried with a cron job in opencms 11 beta setting as a project  entry : "offline", however it still exports the online version and NOT the unpublished pages.

**Comment by dSeidel** [comment]
Hi @ssklavos-ed this would be a new feature, but it is not in our focus currently. So I'll close the issue.
