### ISSUE TITLE
Opencms 11 beta GIT application is missing. Should it be brought back?

### ISSUE THREAD

**Issue by ssklavos-ed** [alkacon/opencms-core#626]
The GIT integration application is missing from the new 11 version (https://documentation.opencms.org/opencms-documentation/extending-opencms/development-setups/developer-tools/). Does that mean that if we need to use it we will have to deploy a custom git app in the workplace launchpad, following similar logic, or there is something new cooked for the official 11 release? 
NOTE: This is a very important application for the development life-cycle, and I believe, it should be improved to also support Windows (Currently only for linux since it was executing a bash script underneath). In any case this feature should extinct in 11 version.

**Comment by dSeidel** [comment]
Hi @ssklavos-ed,

the tool is still present, you only need to add a config to make it visible: Under WEB-INF/git-scripts/ there's a file module-checkin.conf.demo - if you remove the ".demo" the tool will appear. Nevertheless, using the command-line version and check changes before committing is - in my opinion - the much better way to check in.
Support for Windows is not planned. Now all the work is done by a shell script, i.e., not running under Windows.
