### ISSUE TITLE
OpenCms 9.5.3 and new Chrome version incompatibility

### ISSUE THREAD

**Issue by rubenglzlpz** [alkacon/opencms-core#628]
When you navigate between folders in workplace the context menu (alternative button) stop working, the only solution is pressing F5.

This error has been detected since a recently version of Chrome, it's not happens with Firefox neither Internet Explorer.

**Comment by rubenglzlpz** [comment]
When you navigate between folders in workplace the context menu (alternative button) stop working, the only solution is pressing F5.

This error has been detected since a recently version of Chrome, it's not happens with Firefox neither Internet Explorer.

**Comment by helios-design** [comment]
I can confirm that this is also an issue on OpenCms 10.5.3

**Comment by tHerrmann** [comment]
The problem should be fixed by editing the file /system/workplace/resources/commons/explorer.js and replacing the line 650 
- "document.onmouseup = top.handleOnClick;\n"
with this one
+ "document.onmouseup = function(e){top.handleOnClick(e);};\n"

**Comment by helios-design** [comment]
Thank you. I can confirm that the suggested fix works!

**Comment by rubenglzlpz** [comment]
It works! Thanks
