### ISSUE TITLE
encrypted username and password for database connection

### ISSUE THREAD

**Issue by bartcarlo** [alkacon/opencms-core#629]
Hi everyone,
i have a OpenCms 10.5.2, I would to know if there is the possibility to have a username and password encrypted for the connection to the database configured in OpenCms configuration file opencms.properties
My configuration is like in the following example.
opencms.properties:

Configuration of the replication database pool
##############################################################
name of the JDBC driver
db.pool.replication.jdbcDriver=oracle.jdbc.driver.OracleDriver
URL of the JDBC driver
db.pool.replication.jdbcUrl=jdbc:oracle:thin:@HOST:PORT:SID
optional parameters for the URL of the JDBC driver
user name to connect to the database
db.pool.replication.user=MY_USER
password to connect to the database
db.pool.replication.password=MY_PASSWORD

Thanks!!!

**Comment by StephanSchrader** [comment]
You could configure a custom: `org.opencms.security.I_CmsCredentialsResolver` inside the _opencms-system.xml_ config.

**Comment by gWestenberger** [comment]
The credentials resolver is indeed the right way to go about this. Closing.
