### ISSUE TITLE
Modified data not set correctly when adding expire date

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#630]
Adding an expire date triggers a change entry in history, but "Modification date" and "Last modifed by" is not set (the old values are kept).

I set expire date to the past today, logged in as "Author":
![image](https://user-images.githubusercontent.com/2276952/51733807-80c4f080-207a-11e9-8de8-031d0f97e025.png)

Reproduced and tested that with 10.0.1, 10.5.2 and 11.0.0_beta

**Comment by tHerrmann** [comment]
This is intentional.
The use case for this behavior is a list of news items sorted by last modified date. In this case setting an expiration date should not change the sort order.
If you want to make sure, the last modified date is changed, use the resource context menu Advanced > Touch dialog.

**Comment by kartobi** [comment]
But in that case the history view is confusing. It shows a resource change, but unlike other changes does not state when the change was done.

**Comment by gWestenberger** [comment]
The column header "Date at which the last modification occurred that was not just setting release/expiration date" does not fit. "Modification date" is much shorter, and in most cases perfectly adequate. Same for the user. Closing.
