### ISSUE TITLE
urlname.replace property not documented

### ISSUE THREAD

**Issue by arrumm** [alkacon/opencms-core#631]
Hello guys, I think it's more related to documentation rather that to code.

Few days ago just find out that 'urlname.replace' property is very useful.
If you have resources which title (e.g.) mapped to urlname and its property 'urlname.replace' not set up so each time when you change title you get a new mapping. So finally you get several urls referred to the same OpenCms resource.

The issue is I spend some hours to find that in the code itself after find nothing in docs.

**Comment by gWestenberger** [comment]
It's in the current version of the documentation:
https://documentation.opencms.org/opencms-documentation/content-in-opencms/lists-and-detail-pages/detail-pages/index.html
