### ISSUE TITLE
OpenCMS 11.0.0-rc: internal link selector not showing 

### ISSUE THREAD

**Issue by ggiudetti** [alkacon/opencms-core#634]
There seems to be an issue with the internal link selector not showing up from the inline editor.
The popup opens, but is totally 'transparent' (seems to be an 'overflow:hidden' issue, tested on Chrome 73.0.3683.86 )

![internal link selector](https://user-images.githubusercontent.com/1433818/55227450-cd15e380-5217-11e9-9b04-bd56ecbd0f9f.png)

**Comment by tHerrmann** [comment]
Should be fixed with commit cbd63cd919afdafd5b848e3298212132b83eba41.
