### ISSUE TITLE
OpenCms 11 RC: some dialogs are not wide enough, scrollbar is missing

### ISSUE THREAD

**Issue by veggie4ever** [alkacon/opencms-core#640]
In some dialogs in the workplace (e.g. module export) the content of the log output is not fully visible. If so, it is not possible to see the status of a exported resource ("o.k." or "failed"):
![ocms11rc-no-horizontal-scrollbar](https://user-images.githubusercontent.com/3355835/56734051-219e7700-6762-11e9-824d-06345e2fdd76.png)

Some dialogs, like static export, do show a horizontal scrollbar, but even when scrolling to most right point, some content is still not visible:
![ocms11rc-horizontal-scrollbar-but-still-cut-off-content](https://user-images.githubusercontent.com/3355835/56734387-f5cfc100-6762-11e9-865d-2b3e82178214.png)

Tested with latest Firefox and Chrome on Windows 10.

**Comment by gWestenberger** [comment]
Fixed in branch_11_0_x.
