### ISSUE TITLE
OpenCms 11 RC: cut off text in some columns in explorer view. Use tooltip to show full text

### ISSUE THREAD

**Issue by veggie4ever** [alkacon/opencms-core#641]
In some dialogs (e.g. internal link check), which use the explorer like view with several columns, some content is too wide, to see its full content. It would be a nice enhancement, to see the full content of the column when hovering over it.
![ocms11rc-tooltip-for-hidden-text-in-explorer](https://user-images.githubusercontent.com/3355835/56734750-06cd0200-6764-11e9-89ca-d32163891eb3.png)

**Comment by aKandzior** [comment]
Thank you for your enhancement request. However, it's unlikely that we will implement this feature in the foreseeable future, so I close this ticket now.

**Comment by gWestenberger** [comment]
Implemented in master branch.
