### ISSUE TITLE
OpenCms 11 RC: debug output in browser console when requesting mercury demo pages?

### ISSUE THREAD

**Issue by veggie4ever** [alkacon/opencms-core#644]
There seems to be a lot of debug output in the browser console when requesting mercury demo template pages:

![ocms11rc-debug-output-in-browser-console](https://user-images.githubusercontent.com/3355835/56737229-3d0d8000-676a-11e9-9f84-bdcefa5a7a51.png)

I would feel better, if they where not shown there.

Tested in Edge and Chrome.

**Comment by aKandzior** [comment]
This was enabled for the release candidate only. The Mercury template included in the 11.0.0 release will not output debug information by default.
