### ISSUE TITLE
OpenCms 11 RC: Mecury demo - format selectbox in inline editor shows options in wrong color

### ISSUE THREAD

**Issue by veggie4ever** [alkacon/opencms-core#645]
depending on which content item is edited with the inline editing function, the format selectbox shows the selectbox entries in the wrong color. They are not visible, because the font color and background color of the selectbox seem to be the same:
![ocms11rc-format-selectbox-does-not-show-options-correctly](https://user-images.githubusercontent.com/3355835/56741788-cbd2ca80-6773-11e9-914b-82e1ea6e8385.png)

Tested in latest Firefox.

**Comment by gWestenberger** [comment]
Fixed in master branch.
