### ISSUE TITLE
OpenCMS 11 RC: Not complete after create new site

### ISSUE THREAD

**Issue by sinhsac** [alkacon/opencms-core#649]
After create new site, The button is [Cancel], I think it's should be [Close]
![image](https://user-images.githubusercontent.com/48815494/56846745-061ba380-68fd-11e9-8ecb-988725ed7774.png)

**Comment by dSeidel** [comment]
Hi @sinhsac ,
thanks for the hint. The button will be labelled "Close" in the OpenCms 11 release.
