### ISSUE TITLE
Location Widget unusable with full configuration

### ISSUE THREAD

**Issue by ggiudetti** [alkacon/opencms-core#655]
If the location widget is used with all the edit parameters in its configuration (i.e. adding 'size' and 'mode' to the example poi configuration in the mercury template) it becomes impossible to click on the icon to edit it.
![before](https://user-images.githubusercontent.com/1433818/58410043-a63a2900-8071-11e9-838f-1f9b565b7bb9.png)
![after](https://user-images.githubusercontent.com/1433818/58410053-aafedd00-8071-11e9-9a45-004e0650d665.png)

**Comment by gWestenberger** [comment]
Fixed in branch_11_0_x.
