### ISSUE TITLE
OpenCms 10.5 - resourceItem is null when the system calls updateCurrentFolder method.

### ISSUE THREAD

**Issue by ByungJun25** [alkacon/opencms-core#663]
Hi, 

After the user found the resource **via the filter function on Explorer**, the user opens any update-resource-dialog(ex. replace) via right click menu of resource **and then when the user closes the dialog via any button(OK, Cancel and 'X' button), the lots of ERROR logs as like below will be written on log file**.

**ERROR log:**
rendering 'null' item for resource {resource_path}

So I have checked the source code, the problem is that the 'resourceItem' is null for every CmsResource.
https://github.com/alkacon/opencms-core/blob/13fc0b8c9a1d36b6541dd5a2debe15fb81de1f0f/src/org/opencms/ui/components/CmsResourceTable.java#L328-L331

And I have followed call stack of method, I found the code as below.
In the 'fillItem' method, resourceItem was not founded.
https://github.com/alkacon/opencms-core/blob/13fc0b8c9a1d36b6541dd5a2debe15fb81de1f0f/src/org/opencms/ui/components/CmsResourceTable.java#L657-L664

And the 'updateCurrentFolder' method calls 'fillItem' method in loop statement.
https://github.com/alkacon/opencms-core/blob/13fc0b8c9a1d36b6541dd5a2debe15fb81de1f0f/src/org/opencms/ui/apps/CmsFileExplorer.java#L1247-L1249

That's why everytime the lots of error message was written on log file...

Why cannot resourceItem be found in this case? 

**Of course, this doesn't make any funtional issue but our team get the Error log message via email.. so everytime when the users use the filter and close the dialog, we get the lots of error mails... therefore we need to solve this problem.**

Could you help us?

We used the version 10.5.4.

Thank you

Best Regards,
Byungjun Woo

**Comment by gWestenberger** [comment]
Fixed in version 11.
