### ISSUE TITLE
OpenCms 11 - history preview

### ISSUE THREAD

**Issue by filipkratochvil** [alkacon/opencms-core#664]
Hi guys,

behavior of the history preview function in OpenCms 11 (but it's same in OpenCms 10.5) works quite strangely.

Let's say i would like to see "article" history preview in a folder (you have to make some changes to add history records):
/mercury-demo/.content/article/

When i click on the magnifying glass icon, i'll get following content in all cases (except one):

_New "Article" element
An article for news or blogs that consists of several paragraphs with optional images, author, date and categories.
You need to enter the initial values in the form editor._

But, one example works quite acceptably:

I'm able to see preview of a resource which has offline/unpublished changes.
1. Edit resource and save changes (don't publish it!)
2. Click on the History in the Context menu
3. Click on magnifying glass icon in the first row (offline/unpusblished change)

Content of a resource is displayed correctly. I expect same (or similar) behavior for all history records.

Thank you.

**Comment by gWestenberger** [comment]
It's a consequence of the way the formatters from the Mercury/Apollo template are written. The formatters check the inMemoryOnly EL attribute, and if it's true they just print the default values. This is meant for the case where you drag a new element on the container page. But the attribute is also true when rendering the preview for historical files, so these get lumped together with the new elements.

We will likely improve this for the next version.
