### ISSUE TITLE
OpenCms 11.0.1 new Color picker Widget of XmlContent position issue

### ISSUE THREAD

**Issue by SandrineProusteau** [alkacon/opencms-core#674]
In OpenCms 11.0.1, the new color picker widget freeze the page when it open half out of the window.
If the field is near the bottom of the window, the popup appears on bottom of the field, instead of on the top of the field, and so it's half hidden, and we cannot click anything, the editor is blocked on it. Must refresh window.

**Comment by tHerrmann** [comment]
This issue has been fixed by commit 768a0cee3eea4a1b65c05080dd1e11b139ebca99. The fix will be part of the next OpenCms release.

**Comment by gWestenberger** [comment]
Fixed in 11.0.2.
