### ISSUE TITLE
Undo changes not working properly

### ISSUE THREAD

**Issue by arrowwind** [alkacon/opencms-core#677]
I am using 11.0.1 with Mercury Templates.

I have dragged a m-section in a page. After adding some text in it, I publish it.

For Scene 1:
I change the text.  The "Undo changes" can not be activate.

For Scene 2:
I delete the m-section which is the first one I have created. The "Undo changes" can not undo the deleted element.

**Comment by tHerrmann** [comment]
The 'Undo changes' action will only undo the changes on the selected resource. So for Scene 1 you need to call it for the m-section element and not for the containerpage including the element. You can do this either  by opening the info dialog for the element and accessing the context menu from there or from the file explorer.
In Scene 2 you would need to undelete the m-section element first and apply 'Undo changes' on the containerpage afterwards.

**Comment by veggie4ever** [comment]
Hi Tobias,

I understand what you are saying.
Funnily one of our customer asked the same question last week. 
Do you think this behaviour is intuitive? As a user I would expect to be able to undo the changes I made on this page. The question would be, how to implement this. Especially, when more elements on a page are changed. I would like to see that as feature request for an upcoming version.
