### ISSUE TITLE
Where storeds Property Name's i18n data?

### ISSUE THREAD

**Issue by arrowwind** [alkacon/opencms-core#681]
For 11.0.1
In the Property Editor, there are a lot of properties, such as Title, NavText and so on. I don't find the way to i18n those property names. So It is possible to i18n those fields ?

**Comment by dSeidel** [comment]
Hi @arrowwind , you can configure properties in the module or sitemap configurations (the .config files). There you can provide a display name in the form %(key.my.special.key) and you put "my.special.key" in a workplace message bundle (https://documentation.opencms.org/opencms-documentation/localization/message-bundles/#workplace-bundles-the-always-there-bundles).
