### ISSUE TITLE
i18n for "Edit redirect" in Sitemap is missing.

### ISSUE THREAD

**Issue by arrowwind** [alkacon/opencms-core#682]
For the widget dialog, the i18n is missing.

**Comment by arrowwind** [comment]
to fix it
modify file \system\modules\org.opencms.base\classes\org\opencms\base\workplace.properties

add
`label.RedirectPage.Link=Link`
`label.RedirectPage.Type=Type`

**Comment by gWestenberger** [comment]
Fixed in 11.0.2.
