### ISSUE TITLE
11.0.1 - TinyMCE does not works in direct edit

### ISSUE THREAD

**Issue by atouza-opentrends** [alkacon/opencms-core#684]
TinyMCE does not loads for when editting a content from the page view using direct edit mode. No html widget is loaded. This works if the content is edited from the workplace view.

Reason is that TinyMCE needs the document to be in "standard" mode. For that `<!DOCTYPE html>` needs to be the first thing in the page while during direct edit this is not the case.

This worked in OpenCms 11.0.0 due to a previous TinyMCE version being used.

**Comment by gWestenberger** [comment]
Put <!DOCTYPE html> in your template JSP, then.

**Comment by atouza-opentrends** [comment]
Just to clarify, problem was that in my template `<cms:enable-ade />` tag was before the `<!DOCTYPE html>` which didn't give any problem on 11.0.0.
