### ISSUE TITLE
HTTP authentication BASIC-realm should with meaningful info.

### ISSUE THREAD

**Issue by Yuanuo** [alkacon/opencms-core#685]
You should return a meaningful name instead of the default getOpenCmsContext(), because this method always returns "/opencms". This is a really bad experience for users.

I submitted a code change, suggested,
https://github.com/Yuanuo/opencms-core/commit/c6bee343bc23b32516abbc98bb1e1ba90dcecf8c

**Comment by gWestenberger** [comment]
Changed in master branch.
