### ISSUE TITLE
（MySQL）CMS_HISTORY_PROPERTIES.PROPERTY-VALUE should specify character encoding

### ISSUE THREAD

**Issue by Yuanuo** [alkacon/opencms-core#688]
PROPERTY-VALUE should specify a character encoding like the other two tables(CMS_OFFLINE_PROPERTIES,CMS_ONLINE_PROPERTIES).

file: webapp/WEB-INF/setupdata/database/mysql/create_tables.sql
line(168): **PROPERTY_VALUE TEXT NOT NULL**, 
change to:  **PROPERTY_VALUE TEXT CHARACTER SET utf8mb4 NOT NULL,**

**Comment by gWestenberger** [comment]
Fixed in 11.0.2.
