### ISSUE TITLE
the Permission of Direct Publish is not working properly for v11.0.1

### ISSUE THREAD

**Issue by arrowwind** [alkacon/opencms-core#689]
For example, I have setting permissions of a html file that a user called userA( users group) cannot publish this file.
I used another user account modify the html file.  The userA should not publish the html file, but the truth is the html file is published.
Please fix it.

**Comment by gWestenberger** [comment]
The Users group is set as the project manager group for the Offline project by default, so this is probably what overrides the direct publish permission - users in a project manager group for a project can always publish stuff in that project.
