### ISSUE TITLE
the export property is not working while using CmsOnDemandStaticExportHandler for V11.0.1

### ISSUE THREAD

**Issue by arrowwind** [alkacon/opencms-core#690]
For the type of HTML redirect HTML file,  I set the export proerty false. But will export the file still exports and shows exception.  The other export handler will work fine.

**Comment by gWestenberger** [comment]
Maybe you forgot to publish the file? The system reads the property in the Online project for static export.

**Comment by gWestenberger** [comment]
Can't reproduce.
