### ISSUE TITLE
Sorting by name in the workplace capitalizes first names first (latin)

### ISSUE THREAD

**Issue by D612** [alkacon/opencms-core#692]
Sorting by name in the workplace capitalizes first names first (latin). In OpenCms 9.5 working, but 11 don't work.
![OpenCms - Explorer](https://user-images.githubusercontent.com/26367863/69722549-324b0d00-10f6-11ea-9773-1ffe2992b6df.png)
![problema__1](https://user-images.githubusercontent.com/26367863/69722550-32e3a380-10f6-11ea-8f79-379f06040d03.jpg)

**Comment by dSeidel** [comment]
I pushed the latest updates for branch_11_0_x. Sorting is improved by commit 503bbe3f45781bb0c49a23a135cc2e0287b720ee.
