### ISSUE TITLE
Wrong behavior during file upload into the expired folder

### ISSUE THREAD

**Issue by filipkratochvil** [alkacon/opencms-core#693]
Hello guys, one of my coleague found bug during file upload into the expired folder:

**Case 1 - User with "VFS manager" role**
User can select file, but after confirmation wrong log message is displayed (about missing "+w" permissions; but user has right permissions).

**Case 2 - User with "Root Administrator" role**
User can select file, upload file, change title but after final confirmation nothing happens. File is missing and there is no record in log file.

Behavior is present in OpenCms 10.5 same as in OpenCms 11.

**Comment by gWestenberger** [comment]
Fixed in 11.0.2.
