### ISSUE TITLE
Translation problems on tinymce

### ISSUE THREAD

**Issue by nucleodeportais** [alkacon/opencms-core#695]
When I was editing structured content that contains an HtmlWidget, I was able to translate everything to Brazilian Portuguese, except "Fonts" and "System Font". How can I translate this item? 
See the image below:

![Fonts](https://user-images.githubusercontent.com/62144960/76627791-67029900-651a-11ea-9379-8b3353e4ec9f.png)

**Comment by gWestenberger** [comment]
There's an official TinyMCE translation for Brazilian Portuguese now on https://www.tiny.cloud/get-tiny/language-packages/ .
