### ISSUE TITLE
Translation problems in the image editor

### ISSUE THREAD

**Issue by nucleodeportais** [alkacon/opencms-core#696]
When I was editing structured content that contains an image gallery, I was able to translate everything to Brazilian Portuguese, except "title". How can I translate this item?
See the image below:
![Alemao](https://user-images.githubusercontent.com/62144960/76628760-04120180-651c-11ea-9c6a-6395d6690264.JPG)

**Comment by gWestenberger** [comment]
These are just the literal names of the properties being edited, they are not translatable.
