### ISSUE TITLE
NPE for disable user in OpenCms 11.0.1

### ISSUE THREAD

**Issue by D612** [alkacon/opencms-core#700]
Attach
![img1](https://user-images.githubusercontent.com/26367863/87682497-452e5280-c756-11ea-97df-ddd1e53893bd.png)
![img2](https://user-images.githubusercontent.com/26367863/87682514-48c1d980-c756-11ea-9d16-74327b5b363f.png)

**Comment by gWestenberger** [comment]
Fixed in 11.0.2.
