### ISSUE TITLE
Performance issue creating contents

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#702]
We are facing the following performance issues when a folder of contents has a lot of resources in combination with permission checks.

### Steps to reproduce

Preconditions:
- Folder /.content/linklist/ contains 10000 resources li_00001.xml to li_10000.xml
- User as edit rights, but role "VFS resource mangager" is not assigned

1) Open container page and drag&drop a linklist to container (the new content will be create in memory only)
2) Edit the new content (resource name will be generated and resource be created in VFS)

To generate resource name, all 10000 content resouces will be read and checked for permissions.
Takes around 30s after click on edit:

![imagen](https://user-images.githubusercontent.com/2276952/90272170-e6432280-de54-11ea-98cc-942574cea536.png)

In case user clicks edit after a few seconds again (because nothing happens), OpenCms will send a second request which results in an error "resources already exists"

(Tested in OpenCms 10.5.3)

The cause is the readResources() in CmsDefaultFileNameGenerator with does the permission check, which runs over 10000 resources to find the succeeding number for resource name po_10001.xml:

```
    public String getNewFileName(CmsObject cms, String namePattern, int defaultDigits, boolean explorerMode)
    throws CmsException {

        String checkPattern = cms.getRequestContext().removeSiteRoot(namePattern);
        String folderName = CmsResource.getFolderPath(checkPattern);

        // must check ALL resources in folder because name doesn't care for type
        List<CmsResource> resources = cms.readResources(folderName, CmsResourceFilter.ALL, false);

        // now create a list of all the file names
        List<String> fileNames = new ArrayList<String>(resources.size());
        for (CmsResource res : resources) {
            fileNames.add(cms.getSitePath(res));
        }

        return getNewFileNameFromList(fileNames, checkPattern, defaultDigits, explorerMode);
    }
```
	
	
	
The problem seems to get worse when using OpenCms 11.0.1, as readResources() in addition is called for Online project:

```
    public String getNewFileName(CmsObject userCms, String namePattern, int defaultDigits, boolean explorerMode)
    throws CmsException {

        CmsObject cms = OpenCms.initCmsObject(m_adminCms);
        cms.getRequestContext().setSiteRoot(userCms.getRequestContext().getSiteRoot());
        cms.getRequestContext().setCurrentProject(userCms.getRequestContext().getCurrentProject());
        String checkPattern = cms.getRequestContext().removeSiteRoot(namePattern);
        String folderName = CmsResource.getFolderPath(checkPattern);

        // must check ALL resources in folder because name doesn't care for type
        List<CmsResource> resources = cms.readResources(folderName, CmsResourceFilter.ALL, false);
        CmsObject onlineCms = OpenCms.initCmsObject(cms);
        onlineCms.getRequestContext().setCurrentProject(cms.readProject(CmsProject.ONLINE_PROJECT_ID));

        // now create a list of all the file names
        Set<String> fileNames = new HashSet<>();
        for (CmsResource res : resources) {
            fileNames.add(cms.getSitePath(res));
        }

        try {
            CmsResource offlineFolder = cms.readResource(folderName);
            CmsResource onlineFolder = onlineCms.readResource(offlineFolder.getStructureId());
            String onlinePath = onlineCms.getSitePath(onlineFolder);
            List<CmsResource> onlineContents = onlineCms.readResources(onlinePath, CmsResourceFilter.ALL, false);
            for (CmsResource res : onlineContents) {
                fileNames.add(cms.getSitePath(res));
            }

        } catch (CmsException e) {
            LOG.warn(e.getLocalizedMessage(), e);
        }

        return getNewFileNameFromList(fileNames, checkPattern, defaultDigits, explorerMode);
    }
```

Possible solutions could be not to do permission check when "just" creating resource name.

Add least the edit button could be disabled until request to create resource in VFS was return.
So it would still be quite slow, but not resulting in an error.

**Comment by dSeidel** [comment]
Hi @kartobi ,
you already copied the code snippet from the head of branch_11_0_x. And this is the version as is in OpenCms 11.0.2. It uses an "admin"-CmsObject, which means that permission checks are skipped, since for root administrators have always all permissions granted.
In release 11.0.1 the code is different and does not use an "admin-CmsObject and hence might check permissions. Consequently, with OpenCms 11.0.2 performance should be better.

**Comment by tobias-karrer** [comment]
Hi @dSeidel,

you're didn't notice admin object was initialized. Maybe because I checked 12_0_x as well, were it wasn't changed yet.
I'll try to patch it in 10.5.2 we currently use.

**Comment by tobias-karrer** [comment]
Patching by the 11.0.2 version helped to speed up.

What about 
> Add least the edit button could be disabled until request to create resource in VFS was return.
> So it would still be quite slow, but not resulting in an error.
Would that be possible?

We often get user feedback about this error.
