### ISSUE TITLE
Non-Root Organisation Unit Issue

### ISSUE THREAD

**Issue by opencmsuser** [alkacon/opencms-core#703]
Hi,

I have several OU. I want to disable the OU during the login process. After I checked in "Edit Organizational Unit" > Hide from Login form, the user logs in but there is no Page Editor Toolbar. The User has the Role "Author".

How can I have on the one side the login process without typing the OU and the other side the user seeing the Toolbar. To me its strange behaviour.

Sincerly
Thanks.

**Comment by gWestenberger** [comment]
Can't reproduce in V12.
