### ISSUE TITLE
Illegal Operation Reflexive with GWT-Servlet 2.8.2

### ISSUE THREAD

**Issue by D612** [alkacon/opencms-core#712]
It was identified that the gwt-servlet library used in OpenCms tries to carry out a reflexive operation that is being considered illegal in the most current versions of Java, following several tests carried out. Tests were performed using Tomcat 9 with OpenJDK 11, OpenJDK 15, OpenJDK 16, Oracle JDK 16, Oracle JDK 18, and these reflective operations should be modified to suit the new Java security policies.

This problem happens when you log in to OpenCms 11 and also when you try to go to site management and gear, a test with a clean environment was performed. I tried to downgrade to the 2.5.1 library used in OpenCms 9.5.2 and without success either. I also tried to use 2.9.0, but without success.

The chief architect of the Java division, Mark Reinhold, made JEP (Java Enhacement Proposal) 260 to address illegal reflective access of the code through the class path from Java 9, for security reasons.

Source:
https://openjdk.java.net/jeps/260
https://jaxenter.com/jdk-9-replace-permit-illegal-access-134180.html
https://www.gitmemory.com/issue/gwtproject/gwt/9584/768559557

![tomcat_90_openjdk11_1_ao_logar_gwt282](https://user-images.githubusercontent.com/26367863/113610990-4117cd00-9624-11eb-842e-ed7f58290567.png)
![tomcat_90_openjdk11_2_engrenagem_gwt282](https://user-images.githubusercontent.com/26367863/113610991-41b06380-9624-11eb-8ae9-0906fac23ca5.png)
![tomcat_90_openjdk11_3_illegalaccess_permit_gwt282](https://user-images.githubusercontent.com/26367863/113610993-4248fa00-9624-11eb-9f45-c1c6ce5609fc.png)
![tomcat_90_openjdk11_4_illegalaccess_debug_gwt282](https://user-images.githubusercontent.com/26367863/113610995-4248fa00-9624-11eb-905d-b89a07bf4547.png)
![tomcat_90_openjdk11_5_engrenagem_illegalaccess_debug_gwt282](https://user-images.githubusercontent.com/26367863/113610996-42e19080-9624-11eb-8710-91195f0fc2b2.png)
![tomcat_90_openjdk11_6_engrenagem_illegalaccess_deny_gwt282](https://user-images.githubusercontent.com/26367863/113610999-42e19080-9624-11eb-9d0a-902507683b84.png)
![tomcat_90_openjdk15_7_gwt282](https://user-images.githubusercontent.com/26367863/113611001-437a2700-9624-11eb-9e84-755521598488.png)
![tomcat_90_openjdk15_7_gwt282_illegalaccess_permit](https://user-images.githubusercontent.com/26367863/113611002-437a2700-9624-11eb-8b78-e54e3e922272.png)
![tomcat_90_openjdk15_7_gwt282_illegalaccess_warn_naoentra](https://user-images.githubusercontent.com/26367863/113611003-4412bd80-9624-11eb-9893-d68a8d11dd01.png)
![tomcat_90_oraclejdk16_gwt282](https://user-images.githubusercontent.com/26367863/113611005-44ab5400-9624-11eb-8afd-a6ec4eb7256c.png)
![tomcat_90_oraclejdk16_illegalaccess_debug_aologar_gwt282](https://user-images.githubusercontent.com/26367863/113611006-44ab5400-9624-11eb-9263-94ef58f542bb.png)
![tomcat_90_oraclejdk16_illegalaccess_debug_engrenagem_gwt282](https://user-images.githubusercontent.com/26367863/113611007-4543ea80-9624-11eb-9ca6-55d337fa9b8f.png)
![tomcat_90_oraclejdk16_illegalaccess_debug_gwt282](https://user-images.githubusercontent.com/26367863/113611009-4543ea80-9624-11eb-8a1f-6326c4a1e7fb.png)
![tomcat_90_oraclejdk18_gwt251_downgrade_problema1](https://user-images.githubusercontent.com/26367863/113611010-45dc8100-9624-11eb-92dc-f55744f70c3a.png)
![tomcat_90_oraclejdk18_gwt251_downgrade_problema2](https://user-images.githubusercontent.com/26367863/113611011-46751780-9624-11eb-83c6-434ae4e94e58.png)
![tomcat_90_oraclejdk18_gwt282](https://user-images.githubusercontent.com/26367863/113611014-46751780-9624-11eb-9513-0fc826a7dc43.png)

**Comment by gWestenberger** [comment]
Fixed in master branch. 

The site management error is an unrelated error that occurs when a default-uri configured in opencms-sites.xml is not also used as a site root for a site, but that is also fixed in the master branch.
