### ISSUE TITLE
Sort by "Title Ascending" does not behave as intended

### ISSUE THREAD

**Issue by atouza-opentrends** [alkacon/opencms-core#714]
Using "Title ascending" (or descending) for ordering shows first Capital letters, then lower case, symbols, capital letters with accents and lower case letters with accents.

Desired behaviour should be ignore case and accents for sorting.

![imagen](https://user-images.githubusercontent.com/31236071/118606942-4c7c1d80-b7b8-11eb-8090-9299e06cfcf2.png)

**Comment by gWestenberger** [comment]
Fixed in master branch for next version.
