### ISSUE TITLE
Problem with displaying offline content with future released date

### ISSUE THREAD

**Issue by D612** [alkacon/opencms-core#716]
It was identified in version 11.0.2 that the content when it has a future release date, and when we click to be loaded in offline perspective, error 404 occurs. This problem does not occur in version 9.5, we were able to replicate the same problem in a clean version.

We consider it to be a problem with this new version. I need support.

**Comment by tobias-karrer** [comment]
Same problem here (with version 10.5.1)
A solution would be highly appreciated.

**Comment by dSeidel** [comment]
Hi @D612 and @tobias-karrer ,
I tried to reproduce the issue - as I understood it - in OpenCms 11.0.2. I set the release date for an event to the future and published. It displayed on the detail page and also for editing. Same worked with a new copy of the event, never published.
Could you provide instructions on how to produce the error. If possible with the default demo.

**Comment by D612** [comment]
Video demonstrating the problem:
https://www.youtube.com/watch?v=mrkoWlohQZA

**Comment by D612** [comment]
Do you have any estimate on how to solve this problem? Can it be resolved in version 11.0.3 or 12.0.0?

**Comment by gWestenberger** [comment]
Fixed in master branch for next version.
