### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by hagaiwech** [alkacon/opencms-core#717]
Hi OpenCMS team,

I tried to find your security email address but no success. Also, there isn't any mail to contact you with.
Please contact me back, it's about a security issue we found.

hagai.wechsler@whitesourcesoftware.com

**Comment by cornerpirate** [comment]
Hello,

I work with Pentest Limited and we also require contact details for the same reason. We may have a simultaneous discovery here.

Please email in to: contact@pentest.co.uk

Regards
