### ISSUE TITLE
TreeMap exportnameMapping does not work reliably in 11.0.2

### ISSUE THREAD

**Issue by MatthiasHoldorf** [alkacon/opencms-core#718]
**Our configuration:**
We override the CmsAfterPublishStaticExportHandler to only export files that were published. In addition, we have custom exportnames set. 

**Reproduction:**
Exporting a file results in an error in the CmsStaticExportManager and its TreeMap implementation with their two overridden comparators CmsExportNameComparator and CmsSlashComparator.

**Bug description:**
During the generation of the TreeMap the rootSite is set. Upon retrieval from the list in CmsStaticExportManager:1583 the rootSite is always null and thus the comparator and subsequently the TreeMap have different results.

**Result/Behavior:**
The result is that some paths can be exported and some don't, because the TreeMap is wrong. If we set the "currentSite" during debugging it works.

**Proposal:**
The TreeMap implementation might be optimized prematurely and could be reverted to a simple map. In 10.0.1 we have a simple map implementation and it does indeed work.

**Comment by gWestenberger** [comment]
The TreeMap is very much not a premature optimization, and is needed for a special feature where the same export name can be used in multiple sites indepently (if appropriate export rules are defined). Also, I can't reproduce your issue.
