### ISSUE TITLE
SearchUsers with anyGroups param

### ISSUE THREAD

**Issue by glonis** [alkacon/opencms-core#719]
Hi OpencmsTeam,
I would like to report a bug in the user search class with "anyGroups" parameter active. The query is missing two brackets that enclose the list of groups in the EXISTS block.
The tedote is org.opencms.db.generic.CmsUserQueryBuilder.addGroupCondition line 206, the instructions should be added:
```
groupClause.setPrefix ("(");
groupClause.setSuffix (")");
```

I hope I have been helpful.
Greetings Giuseppe

**Comment by gWestenberger** [comment]
Fixed in master branch for next version.
