### ISSUE TITLE
Warning in logs: "The Logger  was created with the message factory"

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#726]
When opening the configuration of the log channels (http://localhost/workplace#!logfile-app/log-channel), many log messages like the following one will be output to the catalina out:

```
2021-10-12 22:48:05,689 http-nio-8080-exec-5 WARN The Logger  was created with the message factory org.apache.logging.log4j.message.ParameterizedMessageFactory@4e5e908c and is now requested with the message factory org.apache.logging.log4j.message.ParameterizedMessageFactory@86e0cff, which may create log events with unexpected formatting.
```

The warning is triggered by

https://github.com/alkacon/opencms-core/blob/745bc78ca23a011aa95ceb7ee699ee36026eb9b8/src/org/opencms/ui/apps/logfile/CmsLogChannelTable.java#L382

and later by

https://github.com/alkacon/opencms-core/blob/745bc78ca23a011aa95ceb7ee699ee36026eb9b8/src/org/opencms/ui/apps/logfile/CmsLogFileApp.java#L461

where OpenCms requests for each Logger found a corresponding parent Logger using `org.apache.logging.log4j.core.Logger#getParent()`.

Unfortunately, this method uses `org.apache.logging.log4j.core.LoggerContext#getLogger()`, assuming that the current Logger and the parent Logger have the same `MessageFactory`, but this is not the case and it logs that warning.

**Comment by gWestenberger** [comment]
Fixed in master branch.
