### ISSUE TITLE
Exception message lost in CmsUpdateStep04SettingsDialog.java

### ISSUE THREAD

**Issue by jm009** [alkacon/opencms-core#732]
I am calling /update for OpenCms 12.

I get the error message "Unable to transform configs" from the wizard.
There is no further information neither in the GUI nor in any log file.

https://github.com/alkacon/opencms-core/blob/cb0d890a1a650e5805e508d4c8a56aa50221a964/src-setup/org/opencms/setup/updater/dialogs/CmsUpdateStep04SettingsDialog.java#L132
and following lines: Exception e is just not used, not output anywhere, just dropped.
That makes it hard to debug, what the problem is.

Best regards, and in any case thank you very much :heart: for OpenCMS!

Update: I just found out, the problem is, that some config files and WEB-INF/log directory were not writable by the Tomcat user. I leave this bug report open, because it is about throwing away an Exception, and throwing away root cause error messages in this case (as in most cases) is not a good idea.

**Comment by gWestenberger** [comment]
Fixed in master branch.
