### ISSUE TITLE
Allow login without providing password through the Java API

### ISSUE THREAD

**Issue by jtotht** [alkacon/opencms-core#733]
When accessing OpenCMS through the Java API, [`CmsObject.loginUser(String, String)`](https://documentation.opencms.org/javadoc/core/org/opencms/file/CmsObject.html#loginUser-java.lang.String-java.lang.String-) allows logging in with a given username–password pair. This is useful for most setups, but there are cases when the code calling this method has already confirmed the user’s identity (e.g. it maintains a session on its own, or the user used for the login is a technical system user). Such codes currently have to either constantly ask the user for their password, or store the password in an unencrypted or reversibly encrypted form, which latter is a very bad security practice, since if an attacker gains access to the store, they’ve got the passwords in clear text. Would a single-parameter `CmsObject.loginUser(String)` method be added that works the same as the two-parameter version except that it doesn’t validate the password, such codes could switch to a more convenient or secure authentication method.

**Comment by gWestenberger** [comment]
Closing this, because authorization without a password is already possible by writing a custom authorization handler class (which has to implement the interface org.opencms.security.I_CmsAuthorizationHandler) and configuring it in your opencms-system.xml.

**Comment by jtotht** [comment]
Could you please give some advice how to do that? As I wrote, I use the Java API and log the user in using `CmsObject.loginUser(String, String)`. When the user logs in through the login form (it’s my own login form, not the OpenCMS default), I do want to check their password, preferably without reinventing the wheel by writing my own password check. However, at other times, my code calling `CmsObject.loginUser` wants to log in without verifying the password. It decides whether to check the password based on conditions more complex than what can be inferred from an `HttpServletRequest`: some calling places use human users (for which I want to check the password at times), while others use technical ones (for which I never want to check the password), and it doesn’t depend only on the HTTP request which one is the case.

**Comment by gWestenberger** [comment]
For the technical users, you can just use [this method.](https://github.com/alkacon/opencms-core/blob/bf9076b1d8acf6159629bf1b6c44be9ec0323a02/src/org/opencms/main/OpenCms.java#L740) You need to feed it a CmsObject with root admin privileges, which you can obtain by writing and installing a module with a [custom module action class](https://github.com/alkacon/opencms-core/blob/bf9076b1d8acf6159629bf1b6c44be9ec0323a02/src/org/opencms/module/I_CmsModuleAction.java).

**Comment by jtotht** [comment]
First, my main concern are actually non-technical users—if a technical user’s password is breached, it’s unfortunate as (depending on the access level of the technical user) the attacker may gain full access to the system until the breach is noticed and the password is changed; but if a human user’s password is breached, we can’t even estimate the damage, as we all know that users tend to reuse passwords: the password breached from my hobby website may also be used on an e-government website. I could use [`OpenCms.initCmsObject(CmsObject, CmsContextInfo)`](https://documentation.opencms.org/javadoc/core/org/opencms/main/OpenCms.html#initCmsObject-org.opencms.file.CmsObject-org.opencms.main.CmsContextInfo-) for human users, but as I read the source code, [`CmsObject.loginUser(String, String)`](https://documentation.opencms.org/javadoc/core/org/opencms/file/CmsObject.html#loginUser-java.lang.String-java.lang.String-) does some additional setup that `initCmsObject` doesn’t do. I don’t understand the code at 100%, so I’m worried that maybe important things would not be done if I used `initCmsObject`.

Second, I could write a module (I didn’t try to actually do that, but let’s suppose I could), but how do I get the information out of the module, using code that lives next to OpenCMS, not inside it? Not to mention that if I want to programmatically install this module, using [`CmsModuleManager.addModule(CmsObject, CmsModule)`](https://documentation.opencms.org/javadoc/core/org/opencms/module/CmsModuleManager.html#addModule-org.opencms.file.CmsObject-org.opencms.module.CmsModule-), I’d need an admin user for installing a module that helps me get the admin user…
