### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [alkacon/opencms-core#737]
Hey there!

I belong to an open source security research community, and a member (@asifnmnl) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by gWestenberger** [comment]
We added a SECURITY.md file.

**Comment by JamieSlome** [comment]
@gWestenberger - thanks for the response! ⚡

I will submit a request via the platform, but just for reference, the report can be found directly here too:
https://huntr.dev/bounties/3ea79272-d29b-48a3-b5ab-b76da2a2750e/

It is private and only accessible to maintainers with repository write permissions 👍

**Comment by gWestenberger** [comment]
The reported issue was a Tomcat configuration issue.
