### ISSUE TITLE
[OpenCMS 11] Error internal link

### ISSUE THREAD

**Issue by acastmae** [alkacon/opencms-core#738]
In the text editor used in the "article" and "content section" elements, when an internal link to a portal page is selected, an error occurs. It is necessary to manually add "/opencms/" to make it work.
I would like to know how to avoid this step every time I have to insert a link.
Thank you very much for your help.

The first image shows how the link looks like when selecting it, giving error and the second one shows the link adding manually "/opencms/" to make it work.

![image](https://user-images.githubusercontent.com/98807052/161253411-8ee34830-c197-434b-9ab5-64177f0c11a3.png)
![image](https://user-images.githubusercontent.com/98807052/161253685-e75fe48e-461b-4c23-b759-c842bace0381.png)

**Comment by gWestenberger** [comment]
Please provide more information on what the error is, and how to reproduce it.

**Comment by acastmae** [comment]
I have checked it and it recognizes it as an external link, is there any way to configure it to select it to be an internal link?
I mean, is there any way to fix it, either by modifying the configuration files for example, or can it only be modified manually?
Thank you very much for your help

**Comment by gWestenberger** [comment]
Do you have a reverse proxy like Apache or haproxy running in front of Tomcat? Make sure it sends the host name from the request URL to Tomcat. Also, if said reverse proxy does SSL termination, make sure you have the attribute  sslmode="manual-ep-termination" on your <workplace-server> and <site> entries in your opencms-sites.xml.

**Comment by Warzag** [comment]
Hello. Hi gWestenberger, hi acastmae, I have the same problem, i tried to configure opencms-sites.xml like in you comment but dont work and the portal dont start.

My problem only occurs in a PRE or PRO environment when I change the local url (http://aleno1:10020/) to the production/preproduction url (diwebsa.es).

Thanks for help

**Comment by gWestenberger** [comment]
You have to make sure the host name you use to access OpenCms gets correctly forwarded to Tomcat in the host header.
