### ISSUE TITLE
[Opencms 10 to 13] Unlock bug for detail page container resources

### ISSUE THREAD

**Issue by tobias-karrer** [alkacon/opencms-core#740]
When two user working on pages with detailContainers, the block each other as the lock on containerpage in .detailCotnainers remains after a user adds or removes a module to the detailpage content

Steps to reproduce (two user with edit/publish rights needed)
1. Open detail page for on of the events in mercury-demo
2. Add and edit an new content element to the event with user1
3. After editing the lock on container page remains:
![image](https://user-images.githubusercontent.com/59998109/177546903-4f9e374f-254b-43f3-b4a4-53ea684ad16f.png)

4. User2 now can't edit or publish the event contents:
![image](https://user-images.githubusercontent.com/59998109/177547581-2a0b0aab-ae1d-43d3-9c8d-f95d0e5b2aa3.png)
![image](https://user-images.githubusercontent.com/59998109/177547638-0d1755c6-4ac3-452f-ba59-d70cfa8d2f6f.png)

**Comment by tobias-karrer** [comment]
Hi @aKandzior, @gWestenberger,
any updates/feedback here?
Will this be fixed soon in OpenCms 13?

BR, Tobias

**Comment by gWestenberger** [comment]
In OpenCms 12 and later versions, the lock is removed when user1 closes the browser tab or leaves the page.

**Comment by gWestenberger** [comment]
If you mean the demo server - I can't reproduce it there. The file is unlocked when I close the tab or go to a different page.

**Comment by tobias-karrer** [comment]
Ok, thanks!
I can't reproduce it on the demo server now any more neiter.
