### ISSUE TITLE
Test Smell: using random number in test methods

### ISSUE THREAD

**Issue by TestSmell** [alkacon/opencms-core#742]
Hi!
We notice that the random number generator is used in some test methods, such as the test method ''testUUIDEquals()'' in TestCmsUUID.java.
But using random number generators in test code is not a good practice.
Random number generation can create couplings between classes and timing artifacts because most random number generator classes are thread-safe and therefore introduce additional synchronization.  It's the memory synchronization that may change the timing of your program. If you look into Random, you can see that it uses an ''AtomicInteger'' under the covers so using it will cause read and write memory barriers as part of the generation of the test data which may change how the other threads see data and the timing of your application overall.
Especially, we find that in your test method, the running time is very important to you since you try to calculate it.
''System.out.println("Time for UUID equals() implementation for " + testSize + " UUIDs : " + time1);''

In terms of solutions, 
1. you could use another simple random algorithm (e.g., https://pastebin.com/BTCa6Jqh) that was not synchronized;
2. you could also generate a class that stored 10000 random numbers (or however many you need) beforehand and then handed them out without synchronization.

**Comment by gWestenberger** [comment]
Not really relevant.
