### ISSUE TITLE
Servlets in OpenCMS 11

### ISSUE THREAD

**Issue by skizub21** [alkacon/opencms-core#744]
I have my own servlet:
`<servlet>
  <servlet-name>StartupServlet</servlet-name>
  <servlet-class>com.myapp.StartupServlet</servlet-class>
  <load-on-startup>1</load-on-startup>
  <init-param>
      <param-name>configcontext</param-name>
      <param-value>http://localhost:8080/myapp/appconfig/</param-value>
  </init-param
</servlet>`

defined in **web.xml** , which works perfectly with OpenCMS v.10.5.4 (and all previous versions).

When I configure the same in web.xml of OpenCMS v11 - application stops working (not starting during tomcat startup).
I'm using tomcat9.

Am I missing something else in OpenCMS configuration?

Thanks in advance for your help.

**Comment by gWestenberger** [comment]
Maybe you should check your Tomcat logs.

**Comment by skizub21** [comment]
These are tomcat log screenshots taken from version 10.5.4 (where it starts and indicates startup in opencms.log) and 

![image](https://user-images.githubusercontent.com/78475687/193116244-12083264-fe83-4de5-a692-36e16aec968f.png)

11.0 (where it doesn't)

![image](https://user-images.githubusercontent.com/78475687/193117109-d2ba7892-174f-479e-9ff5-6ff2683219a5.png)

with OpenCMS 11.0 it produces two warnings additionally:
**log4j:WARN No appenders could be found for logger (com.myapp.StartupServlet).
log4j:WARN Please initialize the log4j system properly.**

Could it be the reason application is not starting?

**Comment by gWestenberger** [comment]
Check the log files in your Tomcat log folder (localhost*.log) too.

If OpenCms starts without your servlet and doesn't start with it, the problem is with your code. I can't help you with problems with your code.

**Comment by skizub21** [comment]
Localhost logs are showing just a retrieval of index.html page and no application activity usually related with this.

It is exactly what I'm trying to understand: why same code, same configuration, running on same tomcat server works with OpenCms versions up to v11 and stops to work from v11 onwards. There must be something new introduced in OpenCMS causing such behaviour.
