### ISSUE TITLE
Imageseries Autoloading

### ISSUE THREAD

**Issue by havank** [alkacon/opencms-core#745]
In opencms 13 the imageseries in mercury supports  an element setting "Automatic loading"
Choosing for "Automatic loading"  does not work. 
Why ? because the generated data-imageseries is generated as "autoload":true.
But "autoload":"true" is required. (not the Boolean true but the string "true").

Hein van der Kallen

**Comment by gWestenberger** [comment]
This issue belongs in the mercury-template project: https://github.com/alkacon/mercury-template
