### ISSUE TITLE
m_securityManager is Null, NullPointerException

### ISSUE THREAD

**Issue by yannsorr** [alkacon/opencms-core#747]
Hello everyone,
I'm using OpenCms-Core dependency (version 14) and trying to use `initCmsObject` method but it returns:
_java.lang.NullPointerException: null
	at org.opencms.main.OpenCmsCore.initCmsObject(OpenCmsCore.java:3093)_

I searched on issues page on GitHub and i found [https://github.com/alkacon/opencms-core/issues/741](url) #741 .
This issue is closed but same problem appears in my app, maybe there is an error in my code.

I have a private CmsObject, and in method i use OpenCms.initCmsObject:
`private CmsObject cmsObject;`
`@RequestMapping(value = "/x", method = RequestMethod.POST)`
`public void x(@Valid @RequestBody object object) {`
`	this.cmsObject = OpenCms.initCmsObject(OpenCms.getDefaultUsers().getUserGuest());`
`...`
`...`
`}`
			`
This is a screen of null variable: 
![image](https://user-images.githubusercontent.com/108749818/198311259-836d6c30-20b2-433e-a1cd-38622c27e2ff.png)

In my application.properties there is : `opencms.set.logfile=false`

Java: 1.8
Apache Maven 3.8.4
OpenCms-Core: 14.0

**Comment by gWestenberger** [comment]
Are you executing your code in an actual OpenCms installation in a servlet container? Because if not, then that is the problem.
