### ISSUE TITLE
Restore the possibility to remove link only from one word in html widget without lost words

### ISSUE THREAD

**Issue by acasini94** [alkacon/opencms-core#757]
If we have to edit a link in a html widget for reduce the text linked, we have to remove all the link (if i use 'remove link') or we lost some words (if I use 'edit link'). 
For instance: if I have a link like this [my link](http://www.google.com), and later I want to unlink only the word "my", if I select only the word and click on "remove link" on the widget, I remove all the link and not only a part. We didn't have this problem in version 10.5, but only from version 11. 
If iI use 'edit link' instead, if I change text in 'text to display' to 'link' (without 'my'), I lost the word and I have to reinsert it without the link. 
Thanks a lot

**Comment by gWestenberger** [comment]
This seems to be a change in how TinyMCE does things - see https://www.tiny.cloud/docs/demo/basic-example/ , it behaves the same way - and is not easily fixable in OpenCms.
