### ISSUE TITLE
Missing scrollbar in Multi-group selector widget

### ISSUE THREAD

**Issue by veggie4ever** [alkacon/opencms-core#760]
When using the multi group select widget `GroupMultiSelectorWidget` and having a long list of groups there is no scrollbar indicating  that there are more groups to choose from.
![image](https://user-images.githubusercontent.com/3355835/229478406-d7421d73-7ba0-4115-87a3-eef1b926968d.png)
Please add a scrollbar similar to the ones in other dialogs, e.g. like this:
![image](https://user-images.githubusercontent.com/3355835/229479317-bfa9cab7-7a8a-443a-84b5-caa81c66dd20.png)

Thanks a lot in advance.
Best regards
Kai

**Comment by gWestenberger** [comment]
I can not reproduce this in OpenCms 14, the widget has the same scrollbar (it only shows up when the mouse cursor is  over the widget).

**Comment by veggie4ever** [comment]
That is very strange. There is definitely no scrollbar (tested in Firefox and Chrome). Not even when hovering with the mouse over the field.
![image](https://user-images.githubusercontent.com/3355835/230128873-e0f4c8ec-1e35-45c6-99b4-e6f4b8ec66e1.png)
It seems (no matter why) that the scrollbar was moved out of the visible area on purpose:
![image](https://user-images.githubusercontent.com/3355835/230129351-c40bc5e7-707c-4d3a-9dc1-98c7234f989e.png)

Could you please recheck this or give a hint what might be the problem?
We are using the Widget as the only field in one tab:
![image](https://user-images.githubusercontent.com/3355835/230129782-8746c9bf-bb6f-4e03-a7e7-45cddc2e42dd.png)

This is how our schema looks like:

```
...
			<xsd:element name="PermissionGroups" type="OpenCmsString" minOccurs="0" />
...
				<Setting>
                    <PropertyName>PermissionGroups</PropertyName>
                    <DisplayName>%(key.label.PermissionGroups)</DisplayName>
                    <Description>%(key.label.PermissionGroups.help)</Description>
                    <Widget>GroupMultiSelectorWidget</Widget>
                    <WidgetConfig>groupfilter=.*L-RES-INTRANET.*</WidgetConfig>
					<Mapping>
						<MapTo>permission:GROUP:+r+v|GROUP.ALL_OTHERS:|GROUP.Projectmanagers:+r+v+w+c</MapTo>
					</Mapping>
                </Setting>`
```

**Comment by gWestenberger** [comment]
It's the tab that's causing the problem. I will look at this again.

**Comment by gWestenberger** [comment]
Fixed in master branch.
