### ISSUE TITLE
Language fallback with two locales in <localesdefault> does not work any more in OpenCms 14

### ISSUE THREAD

**Issue by tobias-karrer** [alkacon/opencms-core#762]
As shown on 
https://documentation.opencms.org/opencms-documentation/template-development/localization/multilingual-websites/
we configured two default locales:
```
<localesdefault>
        <locale>en</locale>
        <locale>de</locale>
</localesdefault>
```

After updating from Opencms 10 to 14 showing english contents in german subtree still is fine, but the opposite way doesn't work correctly - contents in english subtree don't show german contents (when language node for "EN" isn't available)

Only the first localesdefault definition is considered

Switching the order in opencms-system.xml to 
```
<localesdefault>
        <locale>de</locale>
        <locale>en</locale>
</localesdefault>
```
as well "switches" the behaviour.

**Comment by gWestenberger** [comment]
Your description is lacking in detail.

Possibly you have the locale property set to "en" in your English subtree? That would supercede the settings in opencms-system.xml - "en,de" would be the proper setting. 

If this isn't the problem, please provide a minimal example for producing this behavior in a fresh OpenCms installation.

**Comment by tobias-karrer** [comment]
Setup:
![image](https://user-images.githubusercontent.com/59998109/233338872-2d765b6d-ee99-4e1b-9121-da7665b86e91.png)
![image](https://user-images.githubusercontent.com/59998109/233338902-42854d17-701a-4e20-8a8e-e86e9401761d.png)

Config 1:
```
<localesdefault>
        <locale>en</locale>
        <locale>de</locale>
</localesdefault>
```

OpenCms 10:
- Shows EN content in /de/ subtree if language node DE is not available.
- Shows DE content in /en/ subtree if language node EN is not available.

OpenCms 14:
- Shows EN content in /de/ subtree if language node DE is not available.
- Doesn't show DE content in /en/ subtree if language node EN is not available.


Config 2:
```
<localesdefault>
        <locale>de</locale>
        <locale>en</locale>
</localesdefault>
```

OpenCms 10:
- Shows EN content in /de/ subtree if language node DE is not available.
- Shows DE content in /en/ subtree if language node EN is not available.

OpenCms 14:
- Doesn't show EN content in /de/ subtree if language node DE is not available.
- Shows DE content in /en/ subtree if language node EN is not available.

**Comment by gWestenberger** [comment]
As I suspected, you have "en" in your locale property. You need "en,de" if you want "de" as a fallback. The OpenCms 10 behavior was a bug. Fixed with commit 07cc622d38d76018007e9f7d2e529cfb477eec1f , in OpenCms 11.

**Comment by tobias-karrer** [comment]
Ok.
But then why fallback to "en" works even if I don't have "de,en" ?

**Comment by tobias-karrer** [comment]
And why is it possible wo define multiples <localesdefault> in opencms-system.xmml (as shown in documentation: https://documentation.opencms.org/opencms-documentation/template-development/localization/multilingual-websites/)
