### ISSUE TITLE
filter query "search_exclude" is set again even if set before

### ISSUE THREAD

**Issue by tobias-karrer** [alkacon/opencms-core#764]
Query param &fq=search_exclude:"false" will be set in CmsSolrIndex#search() even if CmsSolrQuery query passed already contains the param.

There should be a check if already set before adding it here:
https://github.com/alkacon/opencms-core/blob/master/src/org/opencms/search/solr/CmsSolrIndex.java#L882

**Comment by gWestenberger** [comment]
This is the intended behavior.

**Comment by tobias-karrer** [comment]
> This is the intended behavior.

Really?!?
Queries like &fq=search_exclude:"false"&fq=search_exclude:"false"&fq=search_exclude:"false" ... are intented?

**Comment by tobias-karrer** [comment]
I do so to search in batches (where only "start" changes), as the search is limited to 400 resources.
Increasing maxProcessedResults is in parts possible, but does not help everywhere.
Rebuilding the whole query would not be effective.

As workaround I now remove the filter query for "search_exclude" before searching again.
But it would be better if CmsSolrIndex.java wouldn't set it multiple times.

**Comment by gWestenberger** [comment]
Good point. Done.
