### ISSUE TITLE
CMS_ONLINE_URLNAME_MAPPINGS should distinguish name mapping by siteroot

### ISSUE THREAD

**Issue by tobias-karrer** [alkacon/opencms-core#765]
We had following problem with mapping of detail page urls:

On a OpenCms multi site setup for several railway companies, serveral of them use "Grooved Rail Tournouts".

As NAME needs to be unique this results in urls like
- Grooved-Rail-Turnouts
- Grooved-Rail-Turnouts-00001
- Grooved-Rail-Turnouts-00002
- Grooved-Rail-Turnouts-00003
- Grooved-Rail-Turnouts-00004

So just one company can use the "nice" name.

By using siteroot the same way as done for locales it would be possible all companies use "Grooved-Rail-Turnouts"

**Comment by gWestenberger** [comment]
This would be complicated to implement and not backward compatible (currently, you can have 'cross-site' detail pages, i.e. display a detail content in site A on a detail page in site B if your system is configured appropriately).
