### ISSUE TITLE
[Opencms 14/15/16] Unlock bug for detail page container resources (on logout)

### ISSUE THREAD

**Issue by tobias-karrer** [alkacon/opencms-core#768]
I once reported a problem of detail page container not being unlocked:
https://github.com/alkacon/opencms-core/issues/740

Seems fine so far when closing the tab or go to a different page - the then file is unlocked.

We now experienced, that a lot of user often directly log out after editing detail pages, e.g. news or events. The lock then remains and publishing is blocked in the publish dialog.

Isn't it possible to do the unlock on logout, too? (same behaviour as when closing the tab or the browser)

**Comment by gWestenberger** [comment]
Still can't reproduce this. Logging out via the menu on the top right of the toolbar (behind the user icon) should invalidate the session, which removes all temporary locks on resources for that user.

The only scenario I can think of where this doesn't happen is if you have configured a custom <logoutUri> in your opencms-system.xml, and the page behind that URI doesn't invalidate the session correctly. 

Regardless of whether this is the case, the session should still be invalidated after the session timeout configured in web.xml. So the resources should eventually be unlocked.

**Comment by tobias-karrer** [comment]
Prerquisites:
User1 - tobias.karrer.ext - default user for demo system
User2 - tobias.karrer - with Project Manager role:
![image](https://github.com/alkacon/opencms-core/assets/59998109/f2b00c00-8d10-4ad8-8f5c-f5eddd27d335)

Steps to reproduce:

1) Login to OpenCms - User1 with Chrome, User2 with Firefox

2) Open event, e.g. https://demo.opencms.org/230704/ld_4om1s140qf/mercury-demo/detail-pages/event/Gathering-of-Repetitive-Users-00041/?instancedate=1697706000000 with User 2 and add+edit content section, without closing browser window .
According container page in .detailContainer is locked:
![image](https://github.com/alkacon/opencms-core/assets/59998109/51dda666-cbdd-43fd-99be-ad3ceef0eda5)

3) Log out User2. Resource still is locked for User1:
![image](https://github.com/alkacon/opencms-core/assets/59998109/50d1b804-ac97-400f-9d17-084adb0be872)

**Comment by gWestenberger** [comment]
If I do this, the resource gets unlocked at the end (though you need to reload the explorer to notice).

One interesting point: The unlocking only happens on logout if it's the last session for that user. If the servlet container still has an older active session for the same user (which happens e.g. if they don't log out directly, but just clear their cookies), the lock will not be removed at that time. But all of the sessions will eventually time out - the lock is removed then.

**Comment by tobias-karrer** [comment]
Hmm, did you try with different users?

I wanted to try it again with current cms version, but seems the opencms demo isn't working correctly.
We already registerered with different mail addresses and got the note, the demo instance will be created, but never got a mail to confirm the user or to access the demo instance.

**Comment by gWestenberger** [comment]
I couldn't reproduce this before because I kept reusing the same test page. It only happens for newly created detail-only container pages. The preceding commit should fix it.

**Comment by tobias-karrer** [comment]
Great. Thanks a lot!
