### ISSUE TITLE
Resource type for detail pages

### ISSUE THREAD

**Issue by AnnJul** [alkacon/opencms-core#769]
While creating the link for a detail page (CmsDefaultDetailPageHandler.java), the resource type of the resource is not read from the resource itself but from the parent folder (defined in the module config). If more than one resource type is in the same content folder, the link creation fails, because the latest entry in the config overrides the other.

Example:
Resource types in module config
```
<ResourceType>
      <TypeName><![CDATA[announcement]]></TypeName>
      <Disabled><![CDATA[false]]></Disabled>
      <Folder>
        <Name><![CDATA[support]]></Name>
      </Folder>
      <NamePattern><![CDATA[announcement_%(number).xml]]></NamePattern>
      <ElementView/>
</ResourceType>
<ResourceType>
      <TypeName><![CDATA[faq]]></TypeName>
      <Disabled><![CDATA[false]]></Disabled>
      <Folder>
        <Name><![CDATA[support]]></Name>
      </Folder>
      <NamePattern><![CDATA[faq_%(number).xml]]></NamePattern>
      <ElementView/>
</ResourceType>
```
JSP for announcement entry with a link to its detail page:
`<cms:link>${content.filename}</cms:link> `
--> filename: /support/announcement_00001.xml
```
public String getDetailPage(
        CmsADEManager manager,
        CmsObject cms,
        String contentRootPath,
        String originPath,
        String targetDetailPage) {

        boolean online = cms.getRequestContext().getCurrentProject().isOnlineProject();
        String resType = manager.getParentFolderType(online, contentRootPath);
...
```
`CmsADEManager.getParentFolderType(true, '/.content/support/')` 
--> faq (not announcement)
--> no detail page link created

**Comment by gWestenberger** [comment]
Implemented in master branch.
