### ISSUE TITLE
Migration from Wordpress/static XML to OpenCMS

### ISSUE THREAD

**Issue by Thlenzi** [alkacon/opencms-core#771]
Hi!

I have a question.

We have some large websites to do the migration from Wordpress and other static XML websites to OpenCMS. 

So i would like to know if there are some tools or process to recommend us to do these migration by script or tools.

Thank you in advance.

Best regards from Italy!

**Comment by gWestenberger** [comment]
We don't know of any such tools.

**Comment by veggie4ever** [comment]
@Thlenzi if you need support on this issue you can send me a message via our company website (check my profile for that). We have no ready to use tools but might be able to help.
