### ISSUE TITLE
Webp image format

### ISSUE THREAD

**Issue by glonis** [alkacon/opencms-core#775]
HI,
on opencms version 14 there are problems displaying images in webp format.
In particular, in the preview inside content the image is not resized,
unlike the jpg ones.
Also the scaling of the image with the command
image.webp?__scale=w:1200,h:1200,t:2,c:transparent,p:0 does not work (it
should become a square image instead it keeps the original format).
Finally, due to this problem the image gallery is very slow to load.

A thousand thanks
Greetings Joseph

**Comment by gWestenberger** [comment]
The image scaler doesn't support webp.
