### ISSUE TITLE
Cannot find any XMPP support in opencms

### ISSUE THREAD

**Issue by mabra** [alkacon/opencms-core#776]
Though BOSH is not the up-to-date functionality, I've hoped, there would be at least this. Are the any plans to support xmpp, say in form of pannels - anyway, any would be better then none!

**Comment by gWestenberger** [comment]
No, there are no plans to support this.
I have no idea how an instant messaging protocol would be useful for a CMS.

**Comment by mabra** [comment]
> No, there are no plans to support this. I have no idea how an instant messaging protocol would be useful for a CMS.

1) It would it make very eays to post something from your xmpp-client. Hoped on at least this.
2) could be used to enhance a comment function.
3) could used to interactively ask/talk to the admin.
4) could used to publish some live-data, which does not origin on database.
