### ISSUE TITLE
Notify OS (Linux) about repeatedly happening access errors

### ISSUE THREAD

**Issue by mabra** [alkacon/opencms-core#777]
I am new to opencms, coming from asp.net.
The latter has an exciting infrastructure, which is easyly extendable to enhance security. For example, if the same access error from same client happens, say more then 10 times in 5 seconds, a custom module in the request processing chain is calling a shell script, which add the clients ip-address to an ipset which blocks further attempts for (a near) future.
Looking for something similar (at best, with code snippet, because I left java 20 years ago, where I was no able to do something like this).

**Comment by gWestenberger** [comment]
Something like that should be implementable as a custom servlet filter, as long as you don't need particularly deep integration with OpenCms (https://www.oracle.com/java/technologies/filters.html).

**Comment by mabra** [comment]
> Something like that should be implementable as a custom servlet filter, as long as you don't need particularly deep integration with OpenCms (https://www.oracle.com/java/technologies/filters.html).

Thanks, nearly, what I need and similar to asp.net modules.
