### ISSUE TITLE
Return 404 error if we access with /opencms/ in URL

### ISSUE THREAD

**Issue by acastmae** [alkacon/opencms-core#785]
Hello

I have installed OpenCMS on my website and I have the following problem:
If I want to access the front page, the URL would be the following:
www.example.com/home/
But it also allows me to access if I type the following: www.example.com/opencms/home/

I would like to know if there is any way that you can not access if you enter the URL /opencms/ and you get a 404 error.

Thank you very much
Best regards

**Comment by gWestenberger** [comment]
No. If you want to do that, you will have to do it in a reverse proxy which is sitting in front of Tomcat.
