### ISSUE TITLE
 The gradle-wrapper.jar should be updated.

### ISSUE THREAD

**Issue by HappyHacker123** [alkacon/opencms-core#787]
# Problem Description
Currently akhq is using gradle 8.4 as mentioned in gradle-wrapper.properties and the checksum of current wrapper.jar is 91a239400bb638f36a1795d8fdf7939d532cdc7d794d1119b7261aac158b1e60. However, as can be seen from official doc https://gradle.org/release-checksums/, the expected checksum of wrapper.jar 8.4 should be 0336f591bc0ec9aa0c9988929b93ecc916b3c1d52aed202c7381db144aa0ef15. The inconsistency means that the wrapper.jar is stale and should be updated.

# Possible Solution 
As mentioned in gradle official document https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper, you will need to run the wrapper task a second time to make sure the wrapper.jar is updated. You can run the below command in the root project. Automatically the wrapper scripts will be generated by gradle with corresponding version.
```
bash gradlew wrapper
```

**Comment by gWestenberger** [comment]
Fixed in master branch.
