### ISSUE TITLE
[OpenCms14] Content changes on container page don't index contents for containerpage in Solr

### ISSUE THREAD

**Issue by tobias-karrer** [alkacon/opencms-core#795]
We are currently running OpenCms14 using our own template set.

Whenever content gets edited, solr fields content_de and content_en get deleted and not index again.

The container page stores formatter with prefix "schema_formatter":
![image](https://github.com/alkacon/opencms-core/assets/59998109/d0521737-d550-460a-a547-bdbfda770268)

I debugged into and ended in CmsSolrDocumentContainerPage#extractContent (https://github.com/alkacon/opencms-core/blob/master/src/org/opencms/search/solr/CmsSolrDocumentContainerPage.java#L162)

The _if_ here 
![image](https://github.com/alkacon/opencms-core/assets/59998109/264ebef2-a5d5-46c1-8e02-7cbbc5cd13eb)
fails, as element.getFormatterId() is null and _else if_ can't find the formatter, as null is returned for findFormatter in CmsADEConfigData when given name starts with schema_formatter:
![image](https://github.com/alkacon/opencms-core/assets/59998109/62fc88a8-ebb6-44ba-aeed-aaaf81f3ffd4)

So shouldExtractElement here https://github.com/alkacon/opencms-core/blob/master/src/org/opencms/search/solr/CmsSolrDocumentContainerPage.java#L162 always is false and content is not indexed.

The only way so far is to re-index the whole Solr Core (which takes quite a lot of time for Solr Offline)

Is this a bug that is fixed in OpenCms 15 or 16?
Or what could be the problem?

**Comment by gWestenberger** [comment]
Don't use formatters configured in schemas, they are outdated. Use formatter configurations instead : https://documentation.opencms.org/opencms-documentation/template-development/formatters-and-their-configuration/introduction/index.html
