### ISSUE TITLE
Data view widget error

### ISSUE THREAD

**Issue by kokkoz80** [alkacon/opencms-core#796]
On OpenCms 16 with the Mercury Template, the “asset connection > imgur” type that utilizes the “Data view widget” with the configuration “org.opencms.widgets.CmsDataViewWidget” returns the following error message:

![Screenshot 2024-03-26 124206](https://github.com/alkacon/opencms-core/assets/165014761/05208959-8b16-4355-9d81-faa6da0b1b2e)

However, the same type works correctly on OpenCms 14.

The error can be replicated with the demo installed via the Official OpenCms Docker Image

I attach the error log.
[error.txt](https://github.com/alkacon/opencms-core/files/14771042/error.txt)

**Comment by gWestenberger** [comment]
Fixed in master branch.
