### ISSUE TITLE
Siblings issues after upgrading to v15

### ISSUE THREAD

**Issue by angelocappelletti** [alkacon/opencms-core#797]
After upgrading from v10 to v15 of OpenCMS, we have noticed the following issues:

-  When publishing a new resource created as a sibling, if both available publishing options (“Include linked resources” and “Include siblings”) are selected, only the main resource is being published. However, if only the “Include siblings” option is checked while the “Include associated resources” option is not selected, the system correctly detects changes and related siblings in Publish stage. The feature should allow changes to be marked as “siblings” in Publish stage even when both checkboxes are checked.
- When creating a resource as a copy of an existing one, in the related path of the new resource, the complete path (which is assumed by default) does not appear and it is not indicated. The feature should display the complete path on the VFS of the Publish stage, allowing users to edit it as desired without getting the entire path each time. This feature could make easier siblings management, putting itself language code as prefix in the path (e.g. /es/{path}, /de/{path}).

I'll waiting for your feedback. Thanks.

**Comment by tobias-karrer** [comment]
Hi @gWestenberger, @aKandzior (or someone form Alkacon)

Any updates here?

I have the same problem:
![image](https://github.com/user-attachments/assets/568aa0be-0a3e-4d9c-8f11-2bebce90b649)
![image](https://github.com/user-attachments/assets/393ec290-c17f-4f90-b42a-d7032841a083)

Basically need to manually check changes on a daily base as siblings aren't published...

**Comment by gWestenberger** [comment]
Fixed "include siblings" option in master branch. Regarding the filename in the copy dialog, no, we won't change that.
