### ISSUE TITLE
Cannot compile v17 to java8 target due to caffeine 3.1.8 requires java11

### ISSUE THREAD

**Issue by hudejo** [alkacon/opencms-core#800]
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.github.ben-manes.caffeine:caffeine:3.1.8.
     Required by:
         project :
      > No matching variant of com.github.ben-manes.caffeine:caffeine:3.1.8 was found. The consumer was configured to find an API of a library compatible with Java 8, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally but:
          - Variant 'apiElements' capability com.github.ben-manes.caffeine:caffeine:3.1.8 declares an API of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'javadocElements' capability com.github.ben-manes.caffeine:caffeine:3.1.8 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
          - Variant 'runtimeElements' capability com.github.ben-manes.caffeine:caffeine:3.1.8 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'sourcesElements' capability com.github.ben-manes.caffeine:caffeine:3.1.8 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by hudejo** [comment]
by ben-manes: 2.x supports java8, 3.x requires java11:
https://github.com/ben-manes/caffeine/issues/514#issuecomment-797591842

**Comment by hudejo** [comment]
Next error; solr 9.x also requires java11, so I give up to compile v17 with java8 :-(

**Comment by gWestenberger** [comment]
We only updated the dependencies after the tag build_17_0_0, you should be able to build the tagged revision with Java 8.
