### ISSUE TITLE
[OpenCms 14] Error with locales in detail pages

### ISSUE THREAD

**Issue by tobias-karrer** [alkacon/opencms-core#803]
We configured news as detail pages and have the problem, that it shows content instead of the 404 error page - even if there's no content for language in context and no urlmapping available

Example:

Press release "News nur in DE" doesn't have content for langage "en":
```
<Newss xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="opencms://system/modules/com.pagetemplates.common/schemas/news.xsd">
  <News language="de">
    <UrlName><![CDATA[News nur in DE]]></UrlName>
    <Title><![CDATA[News nur in DE]]></Title>
    <Description name="Description0">
      <links/>
      <content><![CDATA[<p>lorem ipsum dolor sit amet</p>]]></content>
    </Description>
    <Date>1723294320000</Date>
    <ShowTime>false</ShowTime>
    <NewsCategory><![CDATA[--]]></NewsCategory>
  </News>
</Newss>
```

It's correctyl listed on /de/media/presseaussendungen/

![image](https://github.com/user-attachments/assets/625b6a27-8487-4f0f-9964-3a2281cc9f2f)

but not visible on /en/media/press-releases/

![image](https://github.com/user-attachments/assets/beda6352-19c8-4c49-bfb5-5a240ee04c00)

A mapping for locale "en" does not exist neither:

![image](https://github.com/user-attachments/assets/7b443b54-ff64-4729-8626-898242a497a4)

Everything is fine for /de/media/presseaussendungen/News-nur-in-DE/ showing content "de":

![image](https://github.com/user-attachments/assets/73fe0dbe-463e-4d14-9ecc-8ad5632e3482)

But instead of displaying a 404 error, /en/media/press-releases/News-nur-in-DE/ tries to shows content for "en":

![image](https://github.com/user-attachments/assets/8a7c661d-a9e6-4879-8bfe-f7ccefd73604)
(date of today is shown, as their is no check in jsp if date is available)

**Comment by gWestenberger** [comment]
The detail content resolution does not take locales into account. The locale in the URL name mapping is only used for constructing links via the <cms:link> tag or similar. That's simply how it works.
