### ISSUE TITLE
Error in OpenCms ADE: Disappearance of Editing Markers After AJAX Reload

### ISSUE THREAD

**Issue by chemajf** [alkacon/opencms-core#804]
Hello,

There is an error on the **ADE** screen, when a part of the page is reloaded via AJAX, the editing markers for the resources disappear.

This can be easily seen on the "**OpenCms Live Demo**", for example on the page **/mercury-demo/lists/elaborate/**:
![image](https://github.com/user-attachments/assets/e21b7e71-da5f-4fb0-a950-9e24f0af1f49)

 If we sort the list, for example by title, the editing markers for the listed resources disappear:
![image](https://github.com/user-attachments/assets/90d66d88-ec34-4a4f-91af-8acae1a225f2)

When the page is loaded, we see the following error in the browser console:
`[Deprecation] Listener added for a 'DOMNodeInserted' mutation event. Support for this event type has been removed, and this event will no longer be fired. See https://chromestatus.com/feature/5083947249172480 for more information`:
![image](https://github.com/user-attachments/assets/b96f5bcd-4d40-4dee-ab5d-881f4bdeb134)

I'll waiting for your feedback.
Thanks.

**Comment by gWestenberger** [comment]
This is fixed in the master branch and will be part of the next release.
